from comum import conceito, openstax, referencia, salvar

GOV = "cid_openstax_governo"
ECO = "cid_openstax_economia"
PLA = "cid_planalto_legislacao"
TSE = "cid_tse"
CAM = "cid_camara"
SEN = "cid_senado"
STF = "cid_stf"
BCB = "cid_bcb"
RFB = "cid_receita_federal"
MTE = "cid_mte"
INSS = "cid_inss"
PYD = "cid_python_docs"
CERT = "cid_cert_cartilha"
ANPD = "cid_anpd"
TERMOS = "https://www.gov.br/pt-br/termos-de-uso"

FONTES = [
    openstax(GOV, "American Government 3e", "american-government-3e",
             "OpenStax, Rice University; Glen Krutz, Sylvie Waskiewicz"),
    openstax(ECO, "Principles of Economics 3e", "principles-economics-3e",
             "OpenStax, Rice University; Steven A. Greenlaw, David Shapiro, Daniel MacDonald"),
    referencia(PLA, "Portal da Legislação do Governo Federal (Planalto)", "https://www.planalto.gov.br/",
               "Presidência da República", TERMOS),
    referencia(TSE, "Tribunal Superior Eleitoral (TSE)", "https://www.tse.jus.br/",
               "Tribunal Superior Eleitoral", "https://www.tse.jus.br/"),
    referencia(CAM, "Câmara dos Deputados", "https://www.camara.leg.br/",
               "Câmara dos Deputados", "https://www.camara.leg.br/"),
    referencia(SEN, "Senado Federal", "https://www12.senado.leg.br/",
               "Senado Federal", "https://www12.senado.leg.br/"),
    referencia(STF, "Supremo Tribunal Federal", "https://portal.stf.jus.br/",
               "Supremo Tribunal Federal", "https://portal.stf.jus.br/"),
    referencia(BCB, "Banco Central do Brasil", "https://www.bcb.gov.br/",
               "Banco Central do Brasil", "https://www.bcb.gov.br/"),
    referencia(RFB, "Receita Federal do Brasil", "https://www.gov.br/receitafederal/pt-br",
               "Receita Federal do Brasil, Ministério da Fazenda", TERMOS),
    referencia(MTE, "Ministério do Trabalho e Emprego", "https://www.gov.br/trabalho-e-emprego/pt-br",
               "Ministério do Trabalho e Emprego", TERMOS),
    referencia(INSS, "Instituto Nacional do Seguro Social (INSS)", "https://www.gov.br/inss/pt-br",
               "Instituto Nacional do Seguro Social", TERMOS),
    referencia(PYD, "Python 3 Documentation", "https://docs.python.org/3/",
               "Python Software Foundation", "https://docs.python.org/3/license.html"),
    referencia(CERT, "Cartilha de Segurança para Internet (CERT.br)", "https://cartilha.cert.br/",
               "CERT.br / NIC.br", "https://cartilha.cert.br/"),
    referencia(ANPD, "Autoridade Nacional de Proteção de Dados (ANPD)", "https://www.gov.br/anpd/pt-br",
               "Autoridade Nacional de Proteção de Dados", TERMOS),
]
S = "social"
C = "cientifico"
POL = "politica"
DIR = "direito"
ECN = "economia"
TEC = "tecnologia"

ITENS = [
    # ---------------- Poderes e cargos ----------------
    conceito("mundo_poder_executivo", "Poder Executivo", POL, PLA, S,
             "Poder Executivo é o poder do Estado responsável por governar e administrar o país, executando as leis e as políticas públicas.",
             "No Brasil, o Poder Executivo federal é chefiado pelo presidente da República, auxiliado pelos ministros de Estado.",
             "O Poder Executivo existe nos três níveis da federação: é chefiado pelo presidente na União, pelos governadores nos estados e no Distrito Federal e pelos prefeitos nos municípios.",
             "O Poder Executivo cuida de serviços como saúde, educação e segurança, arrecada tributos, executa o orçamento e pode propor projetos de lei; o presidente também pode editar medidas provisórias.",
             aliases=["Executivo", "poder executivo federal"]),
    conceito("mundo_poder_legislativo", "Poder Legislativo", POL, CAM, S,
             "Poder Legislativo é o poder do Estado responsável por elaborar as leis e fiscalizar o Poder Executivo.",
             "No Brasil, o Poder Legislativo federal é exercido pelo Congresso Nacional, que é bicameral: formado pela Câmara dos Deputados e pelo Senado Federal.",
             "O Poder Legislativo também aprova o orçamento público, pode criar comissões parlamentares de inquérito (CPIs) e julgar o presidente em processos de impeachment.",
             "Nos estados, o Poder Legislativo é exercido pelas Assembleias Legislativas; nos municípios, pelas Câmaras Municipais; no Distrito Federal, pela Câmara Legislativa.",
             aliases=["Legislativo", "Congresso Nacional"]),
    conceito("mundo_poder_judiciario", "Poder Judiciário", DIR, STF, S,
             "Poder Judiciário é o poder do Estado responsável por julgar conflitos, interpretar e aplicar as leis aos casos concretos.",
             "No Brasil, o órgão máximo do Poder Judiciário é o Supremo Tribunal Federal (STF), guardião da Constituição.",
             "O Poder Judiciário brasileiro inclui ainda o Conselho Nacional de Justiça, o Superior Tribunal de Justiça (STJ), os tribunais superiores do Trabalho, Eleitoral e Militar, os tribunais regionais e os tribunais de Justiça dos estados.",
             "Para garantir sua independência, os juízes do Poder Judiciário têm vitaliciedade, inamovibilidade e irredutibilidade de salário, e a maioria ingressa na carreira por concurso público.",
             aliases=["Judiciário", "Justiça brasileira"]),
    conceito("mundo_presidente_republica", "presidente da República", POL, PLA, S,
             "Presidente da República é o chefe de Estado e de governo do Brasil, que comanda o Poder Executivo federal.",
             "O presidente da República é eleito por voto direto para um mandato de quatro anos, junto com o vice-presidente, e pode ser reeleito uma única vez para o período seguinte.",
             "A reeleição para presidente da República foi permitida pela Emenda Constitucional 16, de 1997.",
             "Para ser presidente da República é preciso ser brasileiro nato, ter pelo menos 35 anos e estar filiado a um partido político.",
             "O presidente da República faz a gestão do governo federal: nomeia ministros, sanciona ou veta leis, edita medidas provisórias, comanda as Forças Armadas e representa o Brasil no exterior.",
             "Se nenhum candidato a presidente da República obtiver mais da metade dos votos válidos no primeiro turno, os dois mais votados disputam um segundo turno.",
             aliases=["presidente", "presidente do Brasil", "Presidência da República"]),
    conceito("mundo_deputado_federal", "deputado federal", POL, CAM, S,
             "Deputado federal é o representante do povo eleito para a Câmara dos Deputados, uma das casas do Congresso Nacional.",
             "A Câmara dos Deputados tem 513 deputados federais, eleitos pelo sistema proporcional para mandatos de quatro anos, com reeleição permitida sem limite.",
             "O número de deputados federais por estado é proporcional à população, com mínimo de 8 e máximo de 70 por unidade da federação.",
             "Para ser deputado federal é preciso ter pelo menos 21 anos; cabe aos deputados propor e votar leis, fiscalizar o governo e autorizar a abertura de processo de impeachment do presidente.",
             aliases=["deputados federais", "Câmara dos Deputados"]),
    conceito("mundo_senador", "senador", POL, SEN, S,
             "Senador é o parlamentar eleito para o Senado Federal, casa do Congresso Nacional que representa os estados e o Distrito Federal.",
             "O Senado Federal tem 81 senadores: três por estado e três pelo Distrito Federal, eleitos pelo sistema majoritário.",
             "O mandato de senador é de oito anos; a cada quatro anos o Senado renova alternadamente um terço e dois terços das cadeiras.",
             "Para ser senador é preciso ter pelo menos 35 anos; o Senado aprova indicações como as de ministros do STF e julga o presidente da República em processos de impeachment.",
             aliases=["senadores", "Senado Federal"]),
    conceito("mundo_vereador", "vereador", POL, CAM, S,
             "Vereador é o representante eleito para a Câmara Municipal, o Poder Legislativo de um município.",
             "O vereador tem mandato de quatro anos, é eleito pelo sistema proporcional e pode ser reeleito sem limite.",
             "O vereador faz as leis municipais, vota o orçamento do município e fiscaliza o trabalho do prefeito.",
             "O número de vereadores de cada cidade depende da população, variando de 9 a 55; a idade mínima para ser vereador é 18 anos.",
             aliases=["vereadores", "Câmara Municipal", "Câmara de Vereadores"]),
    conceito("mundo_prefeito", "prefeito", POL, TSE, S,
             "Prefeito é o chefe do Poder Executivo de um município, responsável por administrar a cidade.",
             "O prefeito é eleito com o vice-prefeito para mandato de quatro anos e pode ser reeleito uma única vez para o período seguinte.",
             "Em municípios com mais de 200 mil eleitores, a eleição para prefeito pode ter segundo turno; a idade mínima para o cargo é 21 anos.",
             "O prefeito cuida de serviços locais como transporte urbano, coleta de lixo, ensino infantil e fundamental, postos de saúde e ordenamento da cidade.",
             aliases=["prefeitos", "prefeitura"]),
    conceito("mundo_governador", "governador", POL, TSE, S,
             "Governador é o chefe do Poder Executivo de um estado brasileiro ou do Distrito Federal.",
             "O Brasil tem 27 governadores: um para cada um dos 26 estados e um para o Distrito Federal.",
             "O governador é eleito com o vice-governador para mandato de quatro anos, pode ser reeleito uma única vez e precisa ter pelo menos 30 anos.",
             "O governador comanda áreas como as polícias Militar e Civil, o ensino médio estadual e hospitais estaduais.",
             aliases=["governadores", "governo estadual"]),
    conceito("mundo_titulo_de_eleitor", "título de eleitor", DIR, TSE, S,
             "Título de eleitor é o documento emitido pela Justiça Eleitoral que comprova que a pessoa está alistada para votar no Brasil.",
             "O alistamento eleitoral é obrigatório a partir dos 18 anos e facultativo para jovens de 16 e 17 anos e para pessoas com mais de 70 anos.",
             "O título de eleitor indica a zona e a seção onde a pessoa vota; existe também a versão digital, o aplicativo e-Título.",
             "Quem é obrigado a votar e não vota nem justifica a ausência pode ter o título de eleitor cancelado após três eleições seguidas sem regularizar a situação.",
             aliases=["título eleitoral", "e-Título"]),

    # ---------------- Trabalho e previdência ----------------
    conceito("mundo_clt", "CLT", DIR, PLA, S,
             "CLT, ou Consolidação das Leis do Trabalho, é a lei que reúne as principais regras das relações de trabalho com carteira assinada no Brasil.",
             "A CLT foi aprovada pelo Decreto-Lei 5.452, de 1º de maio de 1943, no governo de Getúlio Vargas.",
             "A CLT trata de temas como jornada de trabalho, férias, salário, demissão, segurança no trabalho e proteção ao trabalho da mulher e do menor.",
             "A Constituição de 1988 fixou a jornada normal em até 8 horas diárias e 44 horas semanais, e a Lei 13.467, de 2017, conhecida como reforma trabalhista, alterou vários pontos da CLT.",
             aliases=["Consolidação das Leis do Trabalho", "leis trabalhistas"]),
    conceito("mundo_carteira_de_trabalho", "carteira de trabalho", DIR, MTE, S,
             "Carteira de trabalho, ou Carteira de Trabalho e Previdência Social (CTPS), é o documento que registra a vida profissional do trabalhador no Brasil.",
             "Na carteira de trabalho ficam registrados os contratos de emprego, com datas de admissão e saída, cargo e salário.",
             "Desde 2019 a carteira de trabalho é digital, acessada por aplicativo ou site do governo, usando o CPF como identificação.",
             "Ter a carteira de trabalho assinada garante direitos como FGTS, férias, 13º salário e contribuição ao INSS.",
             aliases=["CTPS", "carteira de trabalho digital", "carteira assinada"]),
    conceito("mundo_fgts", "FGTS", ECN, MTE, S,
             "FGTS, ou Fundo de Garantia do Tempo de Serviço, é uma poupança formada por depósitos mensais do empregador em nome do trabalhador com carteira assinada.",
             "O empregador deposita no FGTS, todo mês, 8% da remuneração do trabalhador, em conta vinculada administrada pela Caixa Econômica Federal; o valor não é descontado do salário.",
             "O FGTS foi criado em 1966 e hoje é regido pela Lei 8.036, de 1990.",
             "O trabalhador pode sacar o FGTS em situações como demissão sem justa causa, quando recebe também multa de 40% sobre o saldo, aposentadoria, compra da casa própria e algumas doenças graves.",
             aliases=["Fundo de Garantia", "Fundo de Garantia do Tempo de Serviço"]),
    conceito("mundo_inss", "INSS", ECN, INSS, S,
             "INSS, ou Instituto Nacional do Seguro Social, é a autarquia federal que paga as aposentadorias e demais benefícios da Previdência Social aos trabalhadores do setor privado no Brasil.",
             "O INSS administra o Regime Geral de Previdência Social, que é financiado por contribuições de trabalhadores, empregadores e do governo.",
             "Entre os benefícios pagos pelo INSS estão aposentadorias, auxílio por incapacidade temporária, salário-maternidade e pensão por morte.",
             "O INSS foi criado em 1990, e o trabalhador pode consultar seus benefícios e contribuições pelo aplicativo ou site Meu INSS.",
             aliases=["Instituto Nacional do Seguro Social", "Previdência Social"]),
    conceito("mundo_aposentadoria", "aposentadoria", ECN, INSS, S,
             "Aposentadoria é o benefício pago mensalmente ao trabalhador que deixa de trabalhar após cumprir os requisitos de idade e de tempo de contribuição.",
             "No Brasil, a aposentadoria dos trabalhadores do setor privado é paga pelo INSS, dentro do Regime Geral de Previdência Social.",
             "Desde a reforma da Previdência de 2019, a idade mínima para se aposentar pelo INSS é de 65 anos para homens e 62 anos para mulheres, com regras de transição para quem já contribuía.",
             "Além da idade, a aposentadoria exige tempo mínimo de contribuição, que é de 15 anos para mulheres e de 20 anos para homens que começaram a contribuir após a reforma de 2019.",
             aliases=["aposentar", "reforma da Previdência"]),
    conceito("mundo_decimo_terceiro_salario", "13º salário", DIR, PLA, S,
             "13º salário, ou gratificação natalina, é um pagamento extra anual, equivalente a um salário mensal, garantido aos trabalhadores com carteira assinada no Brasil.",
             "O 13º salário foi instituído pela Lei 4.090, de 1962.",
             "O 13º salário é pago em duas parcelas: a primeira até 30 de novembro e a segunda até 20 de dezembro.",
             "Quem trabalhou menos de um ano recebe o 13º salário proporcional: um doze avos do salário por mês trabalhado com pelo menos 15 dias; aposentados e pensionistas do INSS também recebem o abono.",
             aliases=["décimo terceiro salário", "décimo terceiro", "gratificação natalina", "13º"]),
    conceito("mundo_ferias_trabalhistas", "férias trabalhistas", DIR, PLA, S,
             "Férias trabalhistas são o período de descanso remunerado de 30 dias a que o trabalhador com carteira assinada tem direito a cada 12 meses de trabalho.",
             "Nas férias trabalhistas, o trabalhador recebe o salário acrescido de pelo menos um terço, adicional garantido pela Constituição de 1988.",
             "Desde a reforma trabalhista de 2017, as férias podem ser divididas em até três períodos, sendo um de pelo menos 14 dias e os demais de pelo menos 5 dias cada.",
             aliases=["férias", "férias remuneradas", "um terço de férias"]),
    conceito("mundo_seguro_desemprego", "seguro-desemprego", ECN, MTE, S,
             "Seguro-desemprego é um benefício temporário pago ao trabalhador com carteira assinada demitido sem justa causa, para ajudá-lo enquanto procura novo emprego.",
             "O seguro-desemprego é pago em três a cinco parcelas, conforme o tempo trabalhado e o número de vezes que a pessoa já pediu o benefício.",
             "O seguro-desemprego é financiado pelo Fundo de Amparo ao Trabalhador (FAT) e pode ser solicitado pela internet, pelo aplicativo da Carteira de Trabalho Digital.",
             aliases=["seguro desemprego"]),
    conceito("mundo_salario_minimo", "salário mínimo", ECN, PLA, S,
             "Salário mínimo é o menor valor que um empregador pode pagar mensalmente a um trabalhador por uma jornada completa de trabalho.",
             "No Brasil, o salário mínimo foi instituído em 1940, no governo de Getúlio Vargas, e a Constituição de 1988 o fixou como nacionalmente unificado.",
             "O valor do salário mínimo no Brasil em 2026 é de R$ 1.621 por mês; o salário mínimo é reajustado anualmente por decreto do governo federal.",
             "O salário mínimo serve de referência para o piso de aposentadorias e benefícios do INSS e para outros valores, como o abono salarial.",
             aliases=["piso salarial nacional", "salário mínimo nacional"]),

    # ---------------- Tributos, documentos e dinheiro ----------------
    conceito("mundo_imposto_de_renda", "imposto de renda", ECN, RFB, S,
             "Imposto de renda é o tributo federal cobrado sobre os rendimentos de pessoas e empresas, administrado no Brasil pela Receita Federal.",
             "O imposto de renda da pessoa física é progressivo: as alíquotas da tabela mensal vão de zero a 27,5%, crescendo conforme a renda.",
             "Grande parte do imposto de renda é retida na fonte pelo empregador; anualmente, quem se enquadra nos critérios faz a declaração, geralmente entre março e o fim de maio, e pode ter imposto a pagar ou a restituir.",
             "O imposto de renda foi criado no Brasil em 1922; a partir de 2026, quem recebe até R$ 5 mil por mês ficou isento do imposto de renda da pessoa física.",
             aliases=["IRPF", "declaração do imposto de renda"]),
    conceito("mundo_cpf", "CPF", DIR, RFB, S,
             "CPF, ou Cadastro de Pessoas Físicas, é o número de identificação fiscal de cada pessoa no Brasil, administrado pela Receita Federal.",
             "O número do CPF tem 11 dígitos, sendo os dois últimos dígitos verificadores, calculados a partir dos anteriores.",
             "O CPF é exigido para abrir conta em banco, trabalhar com carteira assinada, declarar imposto de renda e fazer muitas compras e cadastros.",
             "Desde 2023, o CPF é o número único de identificação do cidadão em documentos, e a nova Carteira de Identidade Nacional usa o CPF como número; a inscrição no CPF é gratuita.",
             aliases=["Cadastro de Pessoas Físicas", "número do CPF"]),
    conceito("mundo_pix", "Pix", ECN, BCB, S,
             "Pix é o sistema de pagamentos instantâneos criado pelo Banco Central do Brasil, que transfere dinheiro entre contas em poucos segundos.",
             "O Pix entrou em funcionamento em novembro de 2020 e opera 24 horas por dia, todos os dias, inclusive fins de semana e feriados.",
             "Para receber um Pix basta informar uma chave, que pode ser CPF ou CNPJ, número de celular, e-mail ou uma chave aleatória; também é possível pagar lendo um QR Code.",
             "O Pix é gratuito para pessoas físicas na maioria das operações, e quem cai em golpe pode pedir ao banco a devolução pelo Mecanismo Especial de Devolução (MED).",
             aliases=["transferência Pix", "chave Pix"]),
    conceito("mundo_cartao_de_credito", "cartão de crédito", ECN, BCB, S,
             "Cartão de crédito é um meio de pagamento que permite comprar agora e pagar depois, na fatura mensal, até um limite definido pelo banco ou emissor.",
             "O cartão de crédito reúne as compras do mês em uma fatura com data de vencimento; pagar o valor total em dia evita a cobrança de juros.",
             "Compras no cartão de crédito podem ser parceladas; atrasar ou pagar só parte da fatura gera juros, multa e encargos.",
             aliases=["cartões de crédito", "fatura do cartão"]),
    conceito("mundo_rotativo_cartao", "rotativo do cartão de crédito", ECN, BCB, S,
             "Rotativo do cartão de crédito é o crédito usado quando o cliente paga menos que o valor total da fatura; o saldo restante passa para o mês seguinte com juros.",
             "Os juros do rotativo do cartão de crédito estão entre os mais altos do mercado brasileiro, por isso ele é considerado uma das formas mais caras de dívida.",
             "Desde 2017, o saldo no rotativo do cartão de crédito só pode ficar até o vencimento da fatura seguinte; depois disso o banco deve oferecer um parcelamento com juros menores.",
             "Desde janeiro de 2024, por lei, juros e encargos do rotativo do cartão de crédito não podem ultrapassar 100% do valor original da dívida.",
             aliases=["juros do rotativo", "crédito rotativo", "rotativo"]),
    conceito("mundo_criptomoeda", "criptomoeda", ECN, BCB, C,
             "Criptomoeda é um tipo de dinheiro digital que usa criptografia para registrar e proteger transações, geralmente sem um banco central que a emita.",
             "As transações de uma criptomoeda costumam ser registradas em uma blockchain, um livro-razão público e distribuído entre muitos computadores.",
             "Os preços das criptomoedas costumam variar muito, e golpes com promessas de lucro fácil são comuns; no Brasil, a Lei 14.478, de 2022, regulou os prestadores de serviços de criptoativos.",
             "As criptomoedas não têm curso legal no Brasil, ou seja, ninguém é obrigado a aceitá-las como pagamento; o Bitcoin e o Ether são as mais conhecidas.",
             aliases=["criptomoedas", "criptoativo", "moeda digital", "blockchain"]),
    conceito("mundo_bitcoin", "Bitcoin", ECN, BCB, C,
             "Bitcoin é a primeira e mais conhecida criptomoeda, uma moeda digital descentralizada que funciona sem banco central.",
             "O Bitcoin foi proposto em 2008 em um artigo assinado por Satoshi Nakamoto, pseudônimo de autoria desconhecida, e sua rede começou a funcionar em janeiro de 2009.",
             "As transações de Bitcoin são registradas em uma blockchain e validadas por mineradores, que usam computadores para resolver cálculos e recebem novas moedas como recompensa.",
             "A quantidade máxima de Bitcoin que poderá existir é de 21 milhões de unidades, regra definida no próprio protocolo.",
             aliases=["BTC"]),

    # ---------------- Tecnologia do dia a dia ----------------
    conceito("mundo_malware", "malware", TEC, CERT, C,
             "Malware, ou software malicioso, é qualquer programa feito para causar danos, roubar dados ou tomar o controle de computadores e celulares.",
             "Vírus de computador é um tipo de malware que se anexa a arquivos ou programas e se espalha quando eles são executados; outros tipos são worms, cavalos de troia, spyware e ransomware.",
             "Um malware pode chegar por anexos e links em e-mails ou mensagens, programas piratas, aplicativos de fontes desconhecidas e dispositivos USB infectados.",
             "Para se proteger de malware, recomenda-se manter sistema e aplicativos atualizados, usar antivírus, baixar programas só de fontes oficiais e desconfiar de links e anexos inesperados.",
             aliases=["vírus de computador", "software malicioso", "cavalo de troia"]),
    conceito("mundo_ransomware", "ransomware", TEC, CERT, C,
             "Ransomware é um tipo de malware que bloqueia o acesso a arquivos ou sistemas, geralmente criptografando os dados, e exige um resgate para liberá-los.",
             "O resgate pedido por criminosos que usam ransomware costuma ser cobrado em criptomoeda, e pagar não garante a recuperação dos dados.",
             "A principal proteção contra ransomware é manter cópias de segurança (backup) atualizadas e guardadas fora do computador, além de manter os sistemas atualizados.",
             "Em 2017, o ransomware WannaCry infectou centenas de milhares de computadores em mais de 150 países.",
             aliases=["sequestro de dados"]),
    conceito("mundo_backup", "backup", TEC, CERT, C,
             "Backup, ou cópia de segurança, é uma cópia de arquivos e dados guardada em outro lugar para que possam ser recuperados em caso de perda.",
             "O backup protege contra falhas de equipamento, roubo, exclusão acidental e ataques de ransomware.",
             "Um backup pode ser feito em HD externo, pendrive ou em serviços de armazenamento em nuvem; uma prática recomendada é ter pelo menos uma cópia fora do local principal.",
             aliases=["cópia de segurança", "becape"]),
    conceito("mundo_engenharia_social", "engenharia social", TEC, CERT, C,
             "Engenharia social é a técnica de manipular pessoas, explorando confiança, medo ou pressa, para que revelem informações ou realizem ações que beneficiam um golpista.",
             "Golpes de engenharia social incluem falsos funcionários de banco ao telefone, mensagens de falsos parentes pedindo dinheiro e sites falsos que imitam lojas ou órgãos públicos.",
             "Para evitar a engenharia social, recomenda-se desconfiar de pedidos urgentes, confirmar a identidade por outro canal e nunca informar senhas ou códigos de verificação.",
             aliases=["golpe de engenharia social"]),
    conceito("mundo_golpe_do_pix", "golpe do Pix", TEC, BCB, S,
             "Golpe do Pix é qualquer fraude em que criminosos enganam a vítima para que ela faça transferências por Pix para contas controladas por eles.",
             "Formas comuns do golpe do Pix são o falso parente que pede dinheiro por aplicativo de mensagens, a falsa central do banco, o falso vendedor e o falso boleto ou QR Code.",
             "Para evitar o golpe do Pix, recomenda-se confirmar pedidos de dinheiro por ligação ou pessoalmente e conferir o nome do recebedor antes de concluir a transferência.",
             "Quem cai em golpe do Pix deve avisar o banco o quanto antes, pedir a devolução pelo Mecanismo Especial de Devolução (MED) e registrar boletim de ocorrência.",
             aliases=["golpe via Pix", "golpe do falso parente"]),
    conceito("mundo_aplicativo", "aplicativo", TEC, CERT, C,
             "Aplicativo, ou app, é um programa de computador feito para realizar tarefas específicas, especialmente em celulares, tablets e computadores.",
             "Em celulares, os aplicativos são baixados em lojas oficiais, como a Google Play, no Android, e a App Store, no iPhone.",
             "Ao instalar um aplicativo, convém verificar as permissões que ele pede, como acesso a câmera, contatos e localização, e preferir apps de desenvolvedores confiáveis.",
             aliases=["app", "aplicativos", "apps"]),
    conceito("mundo_rede_social", "rede social", TEC, CERT, S,
             "Rede social, no sentido digital, é uma plataforma na internet em que pessoas criam perfis, publicam conteúdos e interagem umas com as outras.",
             "Exemplos de redes sociais são Facebook, criado em 2004, YouTube, de 2005, Instagram, de 2010, e TikTok, lançado internacionalmente em 2017.",
             "As redes sociais usam algoritmos que escolhem o que cada usuário vê com base em seu comportamento, o que pode favorecer conteúdos que geram mais engajamento.",
             "Riscos das redes sociais incluem desinformação, golpes, exposição excessiva de dados pessoais e cyberbullying; recomenda-se ajustar as configurações de privacidade.",
             aliases=["redes sociais", "mídias sociais", "mídia social"]),
    conceito("mundo_lgpd", "LGPD", DIR, ANPD, S,
             "LGPD, ou Lei Geral de Proteção de Dados Pessoais, é a lei brasileira que regula como empresas e governos coletam, usam e guardam dados pessoais.",
             "A LGPD é a Lei 13.709, de 2018, e entrou em vigor em setembro de 2020.",
             "A LGPD garante ao titular direitos como saber quais dados seus são usados, corrigi-los e pedir sua exclusão, e exige base legal, como o consentimento, para o tratamento de dados.",
             "A fiscalização da LGPD cabe à Autoridade Nacional de Proteção de Dados (ANPD), que pode aplicar multas de até 2% do faturamento, limitadas a R$ 50 milhões por infração.",
             aliases=["Lei Geral de Proteção de Dados", "proteção de dados pessoais"]),
    conceito("mundo_marco_civil_internet", "Marco Civil da Internet", DIR, PLA, S,
             "Marco Civil da Internet é a lei brasileira que estabelece princípios, direitos e deveres para o uso da internet no Brasil.",
             "O Marco Civil da Internet é a Lei 12.965, de 2014.",
             "O Marco Civil da Internet garante a neutralidade da rede, a proteção da privacidade dos usuários e a liberdade de expressão.",
             aliases=["Lei 12.965", "Marco Civil"]),
]

# Aspecto de cada fato (índice na ficha), usado pela busca para perguntas como
# "para que serve", "como funciona" e "como surgiu".
ASPECTOS = {
    "mundo_poder_executivo": {3: "funcao"},
    "mundo_poder_legislativo": {2: "funcao"},
    "mundo_poder_judiciario": {0: "funcao"},
    "mundo_presidente_republica": {2: "formacao", 4: "funcao"},
    "mundo_deputado_federal": {3: "funcao"},
    "mundo_senador": {3: "funcao"},
    "mundo_vereador": {2: "funcao"},
    "mundo_prefeito": {3: "funcao"},
    "mundo_governador": {3: "funcao"},
    "mundo_clt": {1: "formacao"},
    "mundo_fgts": {1: "funcionamento", 2: "formacao"},
    "mundo_inss": {1: "funcionamento", 2: "funcao"},
        "mundo_decimo_terceiro_salario": {1: "formacao", 2: "funcionamento"},
    "mundo_seguro_desemprego": {1: "funcionamento"},
    "mundo_salario_minimo": {1: "formacao", 3: "funcao"},
    "mundo_imposto_de_renda": {1: "funcionamento", 2: "funcionamento"},
    "mundo_cpf": {2: "funcao"},
    "mundo_pix": {1: "formacao", 2: "funcionamento"},
    "mundo_cartao_de_credito": {1: "funcionamento"},
    "mundo_rotativo_cartao": {2: "funcionamento"},
    "mundo_criptomoeda": {1: "funcionamento"},
    "mundo_bitcoin": {1: "formacao", 2: "funcionamento"},
    "mundo_malware": {2: "funcionamento"},
    "mundo_ransomware": {0: "funcionamento"},
    "mundo_backup": {1: "funcao"},
    "mundo_aplicativo": {1: "funcionamento"},
    "mundo_rede_social": {2: "funcionamento"},
    "mundo_lgpd": {1: "formacao"},
}
for _it in ITENS:
    for _i, _asp in ASPECTOS.get(_it["id"], {}).items():
        _it["fatos"][_i]["aspecto"] = _asp

if __name__ == "__main__":
    import sys
    salvar(sys.argv[1], "Sínteses próprias sobre cidadania, instituições políticas, direitos trabalhistas, economia pessoal e "
           "tecnologia do dia a dia no Brasil, a partir de legislação federal, órgãos públicos (TSE, Câmara, Senado, STF, "
           "Banco Central, Receita Federal, INSS), manuais abertos OpenStax (CC BY 4.0) e da cartilha "
           "do CERT.br. Valores e regras podem mudar por lei; números são os vigentes em 2026.", FONTES, ITENS)
