from comum import conceito, openstax, salvar

Q = "openstax_quimica_2e"
M = "openstax_matematica_contemporanea"
E = "openstax_economia_3e"
FONTES = [
    openstax(Q, "Chemistry 2e", "chemistry-2e", "OpenStax, Rice University; Paul Flowers, Klaus Theopold, Richard Langley, William R. Robinson"),
    openstax(M, "Contemporary Mathematics", "contemporary-mathematics", "OpenStax, Rice University; Donna Kirk e outros"),
    openstax(E, "Principles of Economics 3e", "principles-economics-3e", "OpenStax, Rice University; Steven A. Greenlaw, David Shapiro, Daniel MacDonald"),
]
C = "cientifico"
S = "social"

QUIMICA = [
    conceito("mundo_quimica", "química", "quimica", Q, C,
             "Química é a ciência que estuda a composição, a estrutura, as propriedades e as transformações da matéria.",
             "Divide-se em áreas como química orgânica, inorgânica, físico-química, analítica e bioquímica."),
    conceito("mundo_atomo", "átomo", "quimica", Q, C,
             "Átomo é a menor unidade de um elemento químico que conserva suas propriedades.",
             "É formado por um núcleo com prótons e nêutrons, cercado por elétrons.",
             "O número de prótons, chamado número atômico, define qual é o elemento.",
             aliases=["átomos"]),
    conceito("mundo_elemento_quimico", "elemento químico", "quimica", Q, C,
             "Elemento químico é o conjunto de átomos com o mesmo número de prótons.",
             "Hoje são conhecidos 118 elementos, dos quais cerca de 90 ocorrem naturalmente.",
             "Hidrogênio e hélio são os elementos mais abundantes no universo; na crosta terrestre, oxigênio e silício.",
             aliases=["elementos químicos"]),
    conceito("mundo_tabela_periodica", "tabela periódica", "quimica", Q, C,
             "Tabela periódica é a organização dos elementos químicos em ordem crescente de número atômico, em linhas (períodos) e colunas (grupos).",
             "Elementos do mesmo grupo têm propriedades químicas semelhantes, porque têm configurações eletrônicas externas parecidas.",
             "Dmitri Mendeleiev publicou uma versão em 1869 e previu propriedades de elementos ainda não descobertos.",
             papeis={0: "causa"}),
    conceito("mundo_molecula", "molécula", "quimica", Q, C,
             "Molécula é um grupo de dois ou mais átomos unidos por ligações covalentes.",
             "A água, H₂O, tem dois átomos de hidrogênio ligados a um de oxigênio.",
             aliases=["moléculas"], papeis={0: "exemplo"}),
    conceito("mundo_ligacao_quimica", "ligação química", "quimica", Q, C,
             "Ligação química é a força que mantém átomos unidos em substâncias.",
             "Na ligação iônica, há transferência de elétrons e atração entre íons de cargas opostas, como no sal de cozinha.",
             "Na ligação covalente, átomos compartilham pares de elétrons; na metálica, elétrons se movem livremente entre átomos.",
             aliases=["ligações químicas", "ligação covalente", "ligação iônica"]),
    conceito("mundo_reacao_quimica", "reação química", "quimica", Q, C,
             "Reação química é uma transformação em que substâncias, os reagentes, se convertem em novas substâncias, os produtos.",
             "Os átomos são rearranjados, mas não criados nem destruídos: a massa total se conserva, como estabeleceu Lavoisier.",
             "Sinais comuns de reação são formação de gás, mudança de cor, liberação de calor ou luz e formação de precipitado.",
             aliases=["reações químicas"]),
    conceito("mundo_acido_base", "pH", "quimica", Q, C,
             "Ácidos e bases são classes de substâncias: na definição de Brønsted-Lowry, ácidos doam prótons (H⁺) e bases os recebem.",
             "A escala de pH vai, em geral, de 0 a 14: abaixo de 7 é ácido, 7 é neutro e acima de 7 é básico.",
             "Vinagre e suco de limão são ácidos; bicarbonato de sódio e sabão são básicos.",
             aliases=["ácidos e bases", "ácido", "base química"]),
    conceito("mundo_estados_da_materia", "estados da matéria", "quimica", Q, C,
             "Estados da matéria são as formas em que a matéria se apresenta: sólido, líquido e gasoso, além do plasma.",
             "No sólido, as partículas vibram em posições fixas; no líquido, deslizam umas sobre as outras; no gás, movem-se livremente e ocupam todo o recipiente.",
             "Mudanças de estado incluem fusão, solidificação, vaporização, condensação e sublimação.",
             aliases=["estados físicos da matéria", "mudanças de estado"]),
    conceito("mundo_mol", "mol", "quimica", Q, C,
             "Mol é a unidade de quantidade de matéria do Sistema Internacional, que contém exatamente 6,02214076 × 10²³ entidades.",
             "Esse número é a constante de Avogadro; permite relacionar massas medidas em laboratório ao número de átomos ou moléculas.",
             aliases=["constante de Avogadro"]),
    conceito("mundo_quimica_organica", "química orgânica", "quimica", Q, C,
             "Química orgânica é a área da química que estuda compostos de carbono, em geral ligados a hidrogênio.",
             "O carbono forma quatro ligações e longas cadeias, o que permite uma enorme variedade de moléculas.",
             "Proteínas, açúcares, gorduras, plásticos e combustíveis são compostos orgânicos."),
]

MATEMATICA = [
    conceito("mundo_matematica", "matemática", "matematica", M, C,
             "Matemática é a ciência que estuda quantidades, estruturas, formas, padrões e relações por meio de raciocínio lógico.",
             "Suas afirmações são estabelecidas por demonstração a partir de definições e axiomas.",
             "Áreas tradicionais incluem aritmética, álgebra, geometria, análise, probabilidade e estatística."),
    conceito("mundo_numero_primo", "número primo", "matematica", M, C,
             "Número primo é um número natural maior que 1 que só é divisível por 1 e por ele mesmo.",
             "Os primeiros são 2, 3, 5, 7, 11 e 13; o 2 é o único primo par.",
             "Euclides demonstrou, há mais de dois mil anos, que existem infinitos números primos.",
             "Todo número natural maior que 1 pode ser escrito de forma única como produto de primos.",
             aliases=["números primos", "primo"]),
    conceito("mundo_fracao", "fração", "matematica", M, C,
             "Fração é a representação de uma parte de um todo, na forma a/b, em que b é diferente de zero.",
             "O numerador indica quantas partes são tomadas; o denominador, em quantas partes iguais o todo foi dividido.",
             "Frações equivalentes representam a mesma quantidade, como 1/2 e 2/4.",
             aliases=["frações"]),
    conceito("mundo_porcentagem", "porcentagem", "matematica", M, C,
             "Porcentagem é uma razão com denominador 100, indicada pelo símbolo %.",
             "Calcular 15% de 200 é multiplicar 200 por 15/100, o que dá 30.",
             "Aumentos e descontos sucessivos não se somam: subir 10% e depois cair 10% resulta em 1% a menos que o valor inicial.",
             aliases=["percentual", "por cento"], papeis={1: "exemplo", 2: "limite"}),
    conceito("mundo_teorema_de_pitagoras", "teorema de Pitágoras", "matematica", M, C,
             "Teorema de Pitágoras afirma que, num triângulo retângulo, o quadrado da hipotenusa é igual à soma dos quadrados dos catetos: a² = b² + c².",
             "Um triângulo com catetos 3 e 4 tem hipotenusa 5, porque 9 + 16 = 25.",
             "Vale apenas para triângulos retângulos.",
             aliases=["Pitágoras"], papeis={1: "exemplo", 2: "limite"}),
    conceito("mundo_pi", "número pi", "matematica", M, C,
             "Pi (π) é a razão entre o comprimento de uma circunferência e seu diâmetro, aproximadamente 3,14159.",
             "É um número irracional: sua representação decimal é infinita e não periódica.",
             "A área de um círculo de raio r é πr², e seu comprimento é 2πr.",
             aliases=["pi"]),
    conceito("mundo_equacao", "equação", "matematica", M, C,
             "Equação é uma igualdade que contém uma ou mais incógnitas, valores desconhecidos a serem descobertos.",
             "Resolver 2x + 3 = 11 significa encontrar x = 4, que torna a igualdade verdadeira.",
             "Uma equação do segundo grau, ax² + bx + c = 0, pode ser resolvida pela fórmula de Bhaskara, como é chamada no Brasil.",
             aliases=["equações"], papeis={1: "exemplo"}),
    conceito("mundo_funcao_matematica", "função matemática", "matematica", M, C,
             "Função é uma relação que associa cada elemento de um conjunto, o domínio, a exatamente um elemento de outro conjunto.",
             "Na função f(x) = 2x, cada número é associado ao seu dobro.",
             "Funções podem ser representadas por fórmulas, tabelas ou gráficos.",
             aliases=["função (matemática)"], papeis={1: "exemplo"}),
    conceito("mundo_probabilidade", "probabilidade", "matematica", M, C,
             "Probabilidade é a medida da chance de um evento ocorrer, expressa entre 0 (impossível) e 1 (certo).",
             "Num dado honesto, a probabilidade de sair 3 é 1/6.",
             "A falácia do apostador é achar que resultados passados de eventos independentes mudam a chance do próximo.",
             papeis={1: "exemplo", 2: "limite"}),
    conceito("mundo_estatistica", "estatística", "matematica", M, C,
             "Estatística é a área que coleta, organiza, analisa e interpreta dados para tirar conclusões e tomar decisões.",
             "Média, mediana e moda são medidas de tendência central; a mediana é menos afetada por valores extremos.",
             "Correlação entre duas variáveis não prova que uma cause a outra.",
             papeis={2: "limite"}),
    conceito("mundo_logaritmo", "logaritmo", "matematica", M, C,
             "Logaritmo é o expoente a que uma base deve ser elevada para obter um número: log₁₀ 1000 = 3, porque 10³ = 1000.",
             "Transforma multiplicações em somas, o que facilitou cálculos antes das calculadoras.",
             "Escalas como a do pH e a de magnitude de terremotos são logarítmicas.",
             aliases=["logaritmos"]),
]

ECONOMIA = [
    conceito("mundo_economia", "economia", "economia", E, S,
             "Economia é a ciência que estuda como pessoas, empresas e governos fazem escolhas diante de recursos escassos.",
             "A microeconomia analisa decisões de indivíduos e empresas; a macroeconomia, a economia como um todo, com produção, inflação e emprego.",
             aliases=["ciência econômica"]),
    conceito("mundo_escassez", "escassez", "economia", E, S,
             "Escassez é a situação em que os recursos disponíveis são insuficientes para satisfazer todos os desejos humanos.",
             "Por causa dela, toda escolha envolve renunciar a outra alternativa.",
             papeis={1: "causa"}),
    conceito("mundo_custo_de_oportunidade", "custo de oportunidade", "economia", E, S,
             "Custo de oportunidade é o valor da melhor alternativa de que se abre mão ao fazer uma escolha.",
             "Se você passa a tarde estudando em vez de trabalhar, o custo de oportunidade inclui o dinheiro que deixaria de ganhar.",
             papeis={1: "exemplo"}),
    conceito("mundo_oferta_e_demanda", "preço de equilíbrio", "economia", E, S,
             "Oferta e demanda é o modelo que explica como preços e quantidades se formam num mercado.",
             "Em geral, quanto maior o preço, menor a quantidade demandada e maior a quantidade ofertada.",
             "O preço de equilíbrio é aquele em que a quantidade demandada iguala a ofertada.",
             aliases=["oferta e demanda", "lei da oferta e da procura", "oferta e procura"]),
    conceito("mundo_inflacao", "inflação", "economia", E, S,
             "Inflação é o aumento geral e contínuo dos preços, que reduz o poder de compra do dinheiro.",
             "No Brasil, o índice oficial é o IPCA, calculado pelo IBGE.",
             "O Brasil viveu hiperinflação no fim dos anos 1980 e início dos 1990, controlada pelo Plano Real, de 1994.",
             aliases=["alta de preços"]),
    conceito("mundo_pib", "PIB", "economia", E, S,
             "PIB, produto interno bruto, é o valor de mercado de todos os bens e serviços finais produzidos num país em um período.",
             "O PIB per capita divide esse valor pela população, mas não mostra como a renda está distribuída.",
             aliases=["produto interno bruto"], papeis={1: "limite"}),
    conceito("mundo_juros", "juros", "economia", E, S,
             "Juros são o preço pago pelo uso de dinheiro emprestado ao longo do tempo.",
             "Nos juros compostos, os juros de cada período passam a render juros nos períodos seguintes.",
             "No Brasil, a taxa básica de juros é a Selic, definida pelo Banco Central.",
             aliases=["taxa de juros", "juros compostos"]),
    conceito("mundo_desigualdade_de_renda", "desigualdade de renda", "economia", E, S,
             "Desigualdade de renda é a distribuição desigual dos rendimentos entre pessoas ou famílias de uma sociedade.",
             "O índice de Gini a mede de 0, igualdade total, a 1, desigualdade máxima.",
             "O Brasil está entre os países com maior desigualdade de renda do mundo.",
             aliases=["índice de Gini"]),
    conceito("mundo_mercado", "mercado", "economia", E, S,
             "Mercado é qualquer arranjo em que compradores e vendedores trocam bens, serviços ou recursos.",
             "Em concorrência perfeita há muitos vendedores; em monopólio, um único vendedor controla a oferta.",
             "Falhas de mercado, como poluição, justificam regulação ou ação do governo.",
             papeis={2: "limite"}),
]

if __name__ == "__main__":
    import sys
    salvar(sys.argv[1], "Sínteses próprias de química, matemática e economia de nível introdutório e universitário, com "
           "manuais abertos da OpenStax (CC BY 4.0). Exemplos numéricos foram conferidos à mão.",
           FONTES, QUIMICA + MATEMATICA + ECONOMIA)
