from comum import conceito, openstax, referencia, dominio_publico, salvar

CF = "cc_openstax_fisica_universitaria"
FI = "cc_openstax_fisica"
QU = "cc_openstax_quimica"
OMS = "cc_oms_sodio"
NASA = "cc_nasa_clima"
FONTES = [
    openstax(CF, "College Physics 2e", "college-physics-2e",
             "OpenStax, Rice University; Paul Peter Urone, Roger Hinrichs"),
    openstax(FI, "Physics", "physics", "OpenStax, Rice University; Paul Peter Urone, Roger Hinrichs"),
    openstax(QU, "Chemistry 2e", "chemistry-2e",
             "OpenStax, Rice University; Paul Flowers, Klaus Theopold, Richard Langley, William R. Robinson"),
    referencia(OMS, "Organização Mundial da Saúde — redução do consumo de sódio",
               "https://www.who.int/news-room/fact-sheets/detail/sodium-reduction",
               "Organização Mundial da Saúde (OMS)", "https://www.who.int/about/policies/publishing/copyright"),
    dominio_publico(NASA, "NASA — Climate Change: Vital Signs (Carbon Dioxide)",
                    "https://science.nasa.gov/climate-change/", "NASA",
                    "https://www.nasa.gov/nasa-brand-center/images-and-media/"),
]
C = "cientifico"
F = "fisica"
Q = "quimica"


def com_fonte(item, indice, fonte):
    """Troca a fonte de um fato específico da ficha."""
    item["fatos"][indice]["fonte"] = fonte
    return item


ITENS = [
    conceito("mundo_velocidade_da_luz", "velocidade da luz", F, CF, C,
             "A velocidade da luz no vácuo é de exatamente 299.792.458 metros por segundo, cerca de 300 mil quilômetros por segundo.",
             "A velocidade da luz no vácuo é representada pela letra c e é a mesma para qualquer observador, segundo a teoria da relatividade de Einstein.",
             "A luz do Sol leva cerca de 8 minutos e 20 segundos para chegar à Terra, e a luz da Lua leva pouco mais de 1 segundo.",
             "Nenhum objeto com massa pode alcançar a velocidade da luz; ela é o limite máximo de velocidade para matéria e informação.",
             "Em meios materiais a luz é mais lenta que no vácuo: na água ela viaja a cerca de 225 mil quilômetros por segundo.",
             aliases=["velocidade da luz no vácuo", "constante c"]),
    conceito("mundo_luz", "luz", F, CF, C,
             "Luz é a radiação eletromagnética que o olho humano consegue perceber, com comprimentos de onda entre cerca de 400 e 700 nanômetros.",
             "A luz se propaga mesmo no vácuo, sem precisar de um meio material, ao contrário do som.",
             "A luz branca do Sol é uma mistura de todas as cores, como Isaac Newton mostrou ao separá-la com um prisma.",
             "A luz se comporta ao mesmo tempo como onda e como partícula; as partículas de luz são chamadas fótons.",
             "As cores da luz visível vão do vermelho, de maior comprimento de onda, ao violeta, de menor comprimento de onda.",
             aliases=["luz visível", "o que é a luz"]),
    conceito("mundo_som", "som", F, FI, C,
             "Som é uma onda mecânica que se propaga como vibração em um meio material, como o ar, a água ou um sólido.",
             "O som não se propaga no vácuo, porque precisa de matéria para transmitir a vibração; por isso não há som no espaço.",
             "A velocidade do som no ar, a cerca de 20 °C, é de cerca de 343 metros por segundo; na água, a velocidade do som é de cerca de 1.500 metros por segundo.",
             "O ouvido humano percebe sons com frequência entre cerca de 20 hertz e 20 mil hertz; acima disso é ultrassom e abaixo é infrassom.",
             "A frequência do som define se ele é grave ou agudo, e a intensidade, medida em decibéis, define se é fraco ou forte.",
             aliases=["onda sonora", "ondas sonoras", "o que é o som"]),
    conceito("mundo_eletricidade", "eletricidade", F, CF, C,
             "Eletricidade é o conjunto de fenômenos ligados às cargas elétricas, que podem ser positivas ou negativas.",
             "Na eletricidade, cargas de mesmo sinal se repelem e cargas de sinais opostos se atraem.",
             "Nos átomos, os elétrons têm carga negativa e os prótons têm carga positiva; a unidade de carga elétrica é o coulomb.",
             "A eletricidade usada em casa é gerada em usinas, como hidrelétricas, eólicas e solares, e chega por fios de cobre ou alumínio.",
             aliases=["energia elétrica", "carga elétrica"]),
    conceito("mundo_corrente_eletrica", "corrente elétrica", F, CF, C,
             "Corrente elétrica é o fluxo ordenado de cargas elétricas através de um condutor, como um fio de metal.",
             "A corrente elétrica é medida em ampères (A); um ampère corresponde a um coulomb de carga passando por segundo.",
             "Nos fios metálicos, a corrente elétrica é formada pelo movimento dos elétrons livres do metal.",
             "Corrente contínua flui sempre no mesmo sentido, como em pilhas; corrente alternada inverte o sentido periodicamente, como nas tomadas, que no Brasil usam 60 hertz.",
             "Uma corrente elétrica de poucos centésimos de ampère passando pelo corpo humano já pode ser perigosa e afetar o coração.",
             aliases=["corrente contínua", "corrente alternada", "amperagem"]),
    conceito("mundo_magnetismo", "magnetismo", F, CF, C,
             "Magnetismo é o fenômeno de atração e repulsão entre ímãs e materiais magnéticos, causado pelo movimento de cargas elétricas.",
             "Todo ímã tem um polo norte e um polo sul; polos opostos se atraem e polos iguais se repelem, e não existe ímã com um polo só.",
             "Um ímã funciona porque os pequenos campos magnéticos de seus átomos estão alinhados na mesma direção e se somam em um campo magnético que atrai ferro.",
             "Ferro, níquel e cobalto são os metais comuns fortemente atraídos por ímãs.",
             "A Terra funciona como um grande ímã, e por isso a agulha da bússola aponta aproximadamente para o norte geográfico.",
             "Em 1820, Hans Christian Oersted mostrou que uma corrente elétrica cria um campo magnético, ligando eletricidade e magnetismo.",
             aliases=["ímã", "ímãs", "imã", "campo magnético"]),
    conceito("mundo_temperatura", "temperatura", F, CF, C,
             "Temperatura é a grandeza que indica o quão quente ou frio está um corpo e está ligada à agitação média de suas partículas.",
             "A temperatura é medida com termômetros, nas escalas Celsius (°C), Fahrenheit (°F) e Kelvin (K).",
             "Para converter temperatura de Celsius para Fahrenheit, multiplica-se por 1,8 e soma-se 32; assim, 100 °C equivalem a 212 °F.",
             "O zero absoluto, a menor temperatura possível, é 0 kelvin, o que equivale a −273,15 °C.",
             "A temperatura normal do corpo humano fica em torno de 36 °C a 37 °C.",
             aliases=["escalas de temperatura", "graus Celsius", "Fahrenheit"]),
    conceito("mundo_calor", "calor", F, CF, C,
             "Calor é a energia transferida de um corpo para outro por causa da diferença de temperatura entre eles.",
             "O calor flui espontaneamente do corpo mais quente para o mais frio, até que os dois atinjam a mesma temperatura.",
             "Calor e temperatura são diferentes: temperatura mede o estado de agitação das partículas, e calor é a energia em trânsito.",
             "O calor se propaga por condução, através do contato; por convecção, pelo movimento de líquidos e gases; e por radiação, como a luz do Sol.",
             "O calor é medido em joules; uma caloria equivale a cerca de 4,19 joules.",
             aliases=["energia térmica", "transmissão de calor", "propagação do calor"]),
    conceito("mundo_energia_fisica", "energia na física", F, CF, C,
             "Energia na física é a capacidade de um sistema de realizar trabalho ou provocar mudanças.",
             "A unidade de energia no Sistema Internacional é o joule (J); na conta de luz usa-se o quilowatt-hora, que equivale a 3,6 milhões de joules.",
             "A energia aparece em várias formas, como cinética, potencial, térmica, química, elétrica, luminosa e nuclear.",
             "Pela conservação da energia, a energia não é criada nem destruída, apenas transformada de uma forma em outra.",
             aliases=["energia", "conceito de energia"]),
    conceito("mundo_agua_substancia", "água", Q, QU, C,
             "Água é a substância química de fórmula H2O, formada por dois átomos de hidrogênio ligados a um átomo de oxigênio.",
             "Ao nível do mar, a água pura ferve à temperatura de 100 °C e congela à temperatura de 0 °C.",
             "A água é mais densa a cerca de 4 °C; o gelo é menos denso que a água líquida e por isso flutua.",
             "A água é chamada de solvente universal porque dissolve grande número de substâncias, como sais e açúcares.",
             "A água cobre cerca de 71% da superfície da Terra, e cerca de 97% dessa água é salgada, nos oceanos.",
             aliases=["H2O", "molécula de água", "fórmula da água"]),
    conceito("mundo_ponto_ebulicao", "ponto de ebulição", Q, QU, C,
             "Ponto de ebulição é a temperatura em que um líquido ferve, transformando-se em vapor em todo o seu volume.",
             "O ponto de ebulição depende da pressão: ao nível do mar a água ferve a 100 °C, mas em lugares altos, com menos pressão, ferve abaixo disso.",
             "A panela de pressão aumenta a pressão interna e eleva o ponto de ebulição da água para cerca de 120 °C, cozinhando mais rápido.",
             "Cada substância tem seu ponto de ebulição: o álcool etílico ferve a cerca de 78 °C ao nível do mar.",
             aliases=["temperatura de ebulição", "ebulição", "fervura"]),
    conceito("mundo_ponto_fusao", "ponto de fusão", Q, QU, C,
             "Ponto de fusão é a temperatura em que uma substância sólida se transforma em líquida.",
             "O ponto de fusão do gelo é 0 °C ao nível do mar; o do ferro é de cerca de 1.538 °C.",
             "Substâncias puras têm ponto de fusão fixo, por isso ele é usado para identificar substâncias e verificar sua pureza.",
             "Adicionar sal ao gelo baixa a temperatura de fusão da água, e por isso sal é usado para derreter gelo em estradas.",
             aliases=["temperatura de fusão", "derretimento"]),
    conceito("mundo_oxigenio", "oxigênio", Q, QU, C,
             "Oxigênio é o elemento químico de símbolo O e número atômico 8.",
             "Na forma de gás oxigênio (O2), o oxigênio forma cerca de 21% do ar que respiramos.",
             "O oxigênio é usado pelos seres vivos na respiração celular para obter energia dos alimentos e é liberado pelas plantas na fotossíntese.",
             "O oxigênio é o elemento mais abundante da crosta terrestre em massa, presente na água e em muitos minerais.",
             "O ozônio (O3), outra forma do oxigênio, forma na alta atmosfera uma camada que filtra a radiação ultravioleta do Sol.",
             aliases=["O2", "gás oxigênio", "elemento oxigênio"]),
    com_fonte(conceito("mundo_gas_carbonico", "gás carbônico", Q, QU, C,
             "Gás carbônico, ou dióxido de carbono, é a substância de fórmula CO2, formada por um átomo de carbono e dois de oxigênio.",
             "O gás carbônico é liberado na respiração dos seres vivos e na queima de combustíveis, e é absorvido pelas plantas na fotossíntese.",
             "O gás carbônico é um gás de efeito estufa; sua concentração no ar passou de cerca de 280 partes por milhão antes da Revolução Industrial para mais de 420 partes por milhão nos anos 2020.",
             "O gelo seco é gás carbônico sólido, que passa direto para gás a cerca de −78 °C.",
             "O gás carbônico dissolvido sob pressão é o que forma as bolhas de refrigerantes e águas gaseificadas.",
             aliases=["dióxido de carbono", "CO2", "anidrido carbônico"]), 2, NASA),
    conceito("mundo_ferrugem", "ferrugem", Q, QU, C,
             "Ferrugem é o óxido de ferro hidratado, de cor marrom-avermelhada, que se forma quando o ferro reage com oxigênio e água.",
             "A formação de ferrugem é uma reação de oxidação, um tipo de corrosão que enfraquece peças de ferro e aço.",
             "A ferrugem se forma porque o ferro reage com o oxigênio do ar na presença de água ou umidade, formando óxido de ferro.",
             "A ferrugem se forma mais rápido em ambientes úmidos e com sal, como regiões litorâneas com maresia.",
             "A ferrugem pode ser evitada com pintura, revestimento de zinco (galvanização) ou uso de aço inoxidável, que contém cromo.",
             aliases=["corrosão do ferro", "oxidação do ferro", "enferrujar"]),
    conceito("mundo_combustao", "combustão", Q, QU, C,
             "Combustão é a reação química entre um combustível e um comburente, geralmente o oxigênio, que libera calor e luz.",
             "O fogo é a manifestação visível da combustão; as chamas são gases quentes que emitem luz.",
             "O triângulo do fogo mostra que a combustão precisa de combustível, comburente e calor; retirar um deles apaga o fogo.",
             "A combustão completa de combustíveis com carbono produz gás carbônico e água.",
             "A combustão incompleta, com pouco oxigênio, produz monóxido de carbono, um gás tóxico, inodoro e invisível.",
             aliases=["fogo", "triângulo do fogo"]),
    conceito("mundo_pressao_atmosferica", "pressão atmosférica", F, CF, C,
             "Pressão atmosférica é a pressão exercida pelo peso do ar da atmosfera sobre a superfície da Terra e tudo o que está nela.",
             "Ao nível do mar, a pressão atmosférica média é de cerca de 101 mil pascals, o que corresponde a 1 atmosfera ou 760 milímetros de mercúrio.",
             "A pressão atmosférica diminui com a altitude, porque há menos ar acima; por isso os ouvidos podem tampar em aviões e serras.",
             "Evangelista Torricelli mediu a pressão atmosférica em 1643 com uma coluna de mercúrio, inventando o barômetro.",
             aliases=["pressão do ar", "barômetro"]),
    conceito("mundo_densidade", "densidade", F, CF, C,
             "Densidade é a razão entre a massa de um corpo e o volume que ele ocupa (d = m/V).",
             "A densidade da água líquida é de cerca de 1 grama por centímetro cúbico, ou 1.000 quilos por metro cúbico.",
             "Um objeto flutua em um líquido quando sua densidade média é menor que a do líquido; por isso o óleo fica sobre a água.",
             "O ouro tem densidade de cerca de 19,3 gramas por centímetro cúbico, quase vinte vezes a da água.",
             aliases=["massa específica", "densidade da água"]),
    conceito("mundo_ceu_azul", "céu azul", F, CF, C,
             "O céu é azul porque as moléculas do ar espalham muito mais a luz azul do Sol do que a luz vermelha, fenômeno chamado espalhamento de Rayleigh.",
             "No espalhamento de Rayleigh, a intensidade da luz espalhada cresce muito quando o comprimento de onda diminui, por isso o azul é mais espalhado.",
             "O violeta é espalhado ainda mais que o azul, mas o Sol emite menos violeta e o olho humano é menos sensível a essa cor.",
             "No nascer e no pôr do sol, a luz atravessa uma camada maior de ar, o azul se perde pelo caminho e o céu fica alaranjado ou avermelhado.",
             "Na Lua, que não tem atmosfera, o céu é preto mesmo durante o dia.",
             aliases=["por que o céu é azul", "espalhamento de Rayleigh", "cor do céu"]),
    conceito("mundo_arco_iris", "arco-íris", F, CF, C,
             "Arco-íris é um fenômeno óptico em que a luz do Sol é separada em cores ao atravessar gotas de chuva.",
             "No arco-íris, a luz sofre refração ao entrar na gota, reflexão no fundo dela e nova refração ao sair; cada cor se desvia um pouco diferente.",
             "Para ver um arco-íris, o Sol precisa estar atrás do observador e a chuva à sua frente; o arco forma um ângulo de cerca de 42 graus.",
             "No arco-íris principal, o vermelho fica na parte de fora e o violeta na de dentro; no arco secundário, mais fraco, a ordem se inverte.",
             aliases=["arco íris", "cores do arco-íris"]),
    com_fonte(conceito("mundo_sal_de_cozinha", "sal de cozinha", Q, QU, C,
             "Sal de cozinha é o nome comum do cloreto de sódio, substância de fórmula NaCl formada por íons de sódio e de cloro.",
             "O sal de cozinha é um composto iônico que forma cristais cúbicos e funde a cerca de 801 °C.",
             "O sal de cozinha é obtido pela evaporação da água do mar em salinas ou pela mineração de depósitos de sal-gema.",
             "A Organização Mundial da Saúde recomenda que adultos consumam menos de 5 gramas de sal por dia, o equivalente a uma colher de chá.",
             "No Brasil, o sal de cozinha vendido para consumo humano é obrigatoriamente iodado, para prevenir o bócio e outras doenças por falta de iodo.",
             aliases=["cloreto de sódio", "NaCl", "sal comum", "sal de mesa"]), 3, OMS),
    conceito("mundo_metais", "metais", Q, QU, C,
             "Metais são elementos e materiais com brilho característico que conduzem bem calor e eletricidade, como ferro, cobre, alumínio e ouro.",
             "Os metais são maleáveis e dúcteis: podem ser martelados em lâminas e esticados em fios.",
             "Nos metais, parte dos elétrons fica livre para se mover entre os átomos, o que explica a boa condução elétrica.",
             "Cerca de três quartos dos elementos da tabela periódica são metais; o mercúrio é o único metal líquido à temperatura ambiente.",
             "Ligas metálicas são misturas de metais com outros elementos: o aço é ferro com carbono, o bronze é cobre com estanho e o latão é cobre com zinco.",
             aliases=["metal", "elementos metálicos", "ligas metálicas"]),
    conceito("mundo_vidro", "vidro", Q, QU, C,
             "Vidro é um sólido amorfo, sem estrutura cristalina organizada, geralmente transparente.",
             "O vidro comum é feito principalmente de areia (sílica), barrilha (carbonato de sódio) e calcário, fundidos a cerca de 1.500 °C.",
             "O vidro pode ser reciclado indefinidamente sem perder qualidade.",
             "A ideia de que o vidro de janelas antigas escorre lentamente com o tempo é um mito; a irregularidade vem da forma como era fabricado.",
             aliases=["vidros", "do que é feito o vidro"]),
    conceito("mundo_petroleo", "petróleo", Q, QU, C,
             "Petróleo é um óleo natural formado por uma mistura de hidrocarbonetos, compostos de carbono e hidrogênio.",
             "O petróleo se formou ao longo de milhões de anos a partir de restos de organismos marinhos, como o plâncton, soterrados sob calor e pressão.",
             "Nas refinarias, o petróleo é separado por destilação fracionada em produtos como gás de cozinha (GLP), gasolina, querosene, óleo diesel e asfalto.",
             "O petróleo é um combustível fóssil e não renovável, e sua queima libera gás carbônico, que contribui para o aquecimento global.",
             "O petróleo também é matéria-prima de plásticos, borrachas sintéticas, tintas e fertilizantes.",
             aliases=["óleo cru", "petróleo bruto"]),
    conceito("mundo_reflexao_luz", "reflexão da luz", F, FI, C,
             "Reflexão da luz é o fenômeno em que a luz bate em uma superfície e volta para o meio de onde veio.",
             "Na reflexão da luz, o ângulo de incidência é igual ao ângulo de reflexão, medidos em relação à reta perpendicular à superfície.",
             "Espelhos produzem reflexão regular e formam imagens nítidas; superfícies ásperas espalham a luz em várias direções.",
             "Enxergamos a maioria dos objetos porque eles refletem parte da luz que recebem até nossos olhos.",
             aliases=["espelho plano", "reflexão luminosa"]),
    conceito("mundo_refracao_luz", "refração da luz", F, CF, C,
             "Refração da luz é a mudança de direção da luz ao passar de um meio para outro, causada pela mudança de sua velocidade.",
             "A refração da luz faz um canudo dentro de um copo de água parecer quebrado.",
             "O índice de refração indica quantas vezes a luz é mais lenta em um meio do que no vácuo; o da água é cerca de 1,33.",
             "Lentes de óculos, lupas, câmeras e o cristalino do olho funcionam por refração da luz.",
             aliases=["refração", "índice de refração"]),
    conceito("mundo_hidrogenio", "hidrogênio", Q, QU, C,
             "Hidrogênio é o elemento químico de símbolo H e número atômico 1, o mais leve de todos.",
             "O hidrogênio é o elemento mais abundante do universo, formando cerca de três quartos da massa da matéria comum.",
             "O gás hidrogênio (H2) é muito inflamável e, ao queimar, produz apenas água.",
             "As estrelas, como o Sol, produzem energia fundindo núcleos de hidrogênio em hélio.",
             aliases=["H2", "gás hidrogênio", "elemento hidrogênio"]),
    conceito("mundo_nitrogenio", "nitrogênio", Q, QU, C,
             "Nitrogênio é o elemento químico de símbolo N e número atômico 7.",
             "O gás nitrogênio (N2) forma cerca de 78% do ar e é pouco reativo.",
             "O nitrogênio é essencial para os seres vivos, pois faz parte das proteínas e do DNA.",
             "O nitrogênio líquido ferve a cerca de −196 °C e é usado para congelar e conservar materiais biológicos.",
             "O nitrogênio do ar é transformado em amônia pelo processo Haber-Bosch para produzir fertilizantes.",
             aliases=["N2", "gás nitrogênio", "azoto"]),
    conceito("mundo_condutores_isolantes", "condutores e isolantes", F, CF, C,
             "Condutores são materiais que deixam a eletricidade ou o calor passar com facilidade, e isolantes são os que dificultam essa passagem.",
             "Metais como cobre e alumínio são bons condutores elétricos, por isso são usados em fios.",
             "Borracha, plástico, vidro e madeira seca são isolantes elétricos e revestem fios e ferramentas.",
             "A água pura conduz mal a eletricidade, mas a água comum, com sais dissolvidos, conduz bem, por isso aparelhos elétricos e água são uma combinação perigosa.",
             "Semicondutores, como o silício, têm condução intermediária e são a base dos chips eletrônicos.",
             aliases=["condutor elétrico", "isolante elétrico", "isolante térmico"]),
    conceito("mundo_eletricidade_estatica", "eletricidade estática", F, FI, C,
             "Eletricidade estática é o acúmulo de carga elétrica na superfície de um objeto, geralmente causado por atrito.",
             "Esfregar um balão no cabelo transfere elétrons e deixa ambos carregados, por isso o balão gruda e os fios se levantam.",
             "O pequeno choque ao tocar uma maçaneta ou porta de carro é a descarga da eletricidade estática acumulada no corpo.",
             "A eletricidade estática se acumula mais em dias secos, porque o ar úmido ajuda a dissipar as cargas.",
             "O raio é uma descarga elétrica gigantesca causada pelo acúmulo de cargas nas nuvens de tempestade.",
             aliases=["eletrização por atrito", "choque estático"]),
]

if __name__ == "__main__":
    import sys
    salvar(sys.argv[1], "Sínteses próprias de física e química do dia a dia, com fatos consolidados em manuais abertos "
           "(OpenStax, CC BY 4.0) e referências institucionais (OMS, NASA). Valores numéricos são aproximações correntes "
           "nas condições indicadas.", FONTES, ITENS)
