"""Catálogo de cultura brasileira, cotidiano, meio ambiente, alimentos e engenharia do dia a dia."""
from comum import conceito, openstax, referencia, dominio_publico, salvar

ABL = "cul_abl"
IPHAN = "cul_iphan"
MMA = "cul_mma"
EMB = "cul_embrapa"
MS = "cul_ministerio_saude"
PLAN = "cul_planalto"
NASA = "cul_nasa_aeronautica"
FIS = "cul_openstax_fisica"
BIO = "cul_openstax_biologia"
QUI = "cul_openstax_quimica"
SOC = "cul_openstax_sociologia"
PSI = "cul_openstax_psicologia"
OMS = "cul_oms"
GOV = "https://www.gov.br/pt-br/termos-de-uso"

FONTES = [
    referencia(ABL, "Academia Brasileira de Letras — acadêmicos, autores e obras", "https://www.academia.org.br/",
               "Academia Brasileira de Letras", "https://www.academia.org.br/"),
    referencia(IPHAN, "IPHAN — patrimônio cultural imaterial brasileiro", "https://www.gov.br/iphan/pt-br",
               "Instituto do Patrimônio Histórico e Artístico Nacional (IPHAN)", GOV),
    referencia(MMA, "Ministério do Meio Ambiente e Mudança do Clima", "https://www.gov.br/mma/pt-br",
               "Ministério do Meio Ambiente e Mudança do Clima (Brasil)", GOV),
    referencia(EMB, "Embrapa — Empresa Brasileira de Pesquisa Agropecuária", "https://www.embrapa.br/",
               "Embrapa", GOV),
    referencia(MS, "Ministério da Saúde — saúde de A a Z e Guia Alimentar para a População Brasileira",
               "https://www.gov.br/saude/pt-br", "Ministério da Saúde (Brasil)", GOV),
    referencia(PLAN, "Portal da Legislação do Planalto", "https://www.planalto.gov.br/",
               "Presidência da República (Brasil)", GOV),
    referencia(OMS, "Organização Mundial da Saúde — poluição do ar", "https://www.who.int/",
               "Organização Mundial da Saúde", "https://www.who.int/"),
    dominio_publico(NASA, "NASA Glenn Research Center — Beginner's Guide to Aeronautics",
                    "https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/",
                    "NASA Glenn Research Center", "https://www.nasa.gov/nasa-brand-center/images-and-media/"),
    openstax(FIS, "College Physics 2e", "college-physics-2e",
             "OpenStax, Rice University; Paul Peter Urone, Roger Hinrichs"),
    openstax(BIO, "Biology 2e", "biology-2e",
             "OpenStax, Rice University; Mary Ann Clark, Matthew Douglas, Jung Choi"),
    openstax(QUI, "Chemistry 2e", "chemistry-2e",
             "OpenStax, Rice University; Paul Flowers, Klaus Theopold, Richard Langley, William R. Robinson"),
    openstax(SOC, "Introduction to Sociology 3e", "introduction-sociology-3e",
             "OpenStax, Rice University; Tonja R. Conerly, Kathleen Holmes, Asha Lal Tamang"),
    openstax(PSI, "Psychology 2e", "psychology-2e",
             "OpenStax, Rice University; Rose M. Spielman, William J. Jenkins, Marilyn D. Lovett"),
]
S = "social"
C = "cientifico"

ITENS = [
    # ---------- festas e comidas ----------
    conceito("mundo_carnaval", "Carnaval", "artes", IPHAN, S,
             "Carnaval é a festa popular que acontece nos dias que antecedem a Quarta-feira de Cinzas, início da Quaresma cristã, e é uma das maiores celebrações culturais do Brasil.",
             "O Carnaval tem data móvel: a terça-feira de Carnaval cai 47 dias antes do domingo de Páscoa.",
             "O Carnaval brasileiro tem raízes no entrudo, brincadeira trazida pelos portugueses no período colonial, e ganhou elementos africanos e indígenas.",
             "No Rio de Janeiro, o Carnaval é marcado pelos desfiles das escolas de samba no Sambódromo da Marquês de Sapucaí, inaugurado em 1984 com projeto de Oscar Niemeyer.",
             "Em Salvador, o Carnaval é dominado pelos trios elétricos, criados por Dodô e Osmar em 1950; em Recife e Olinda, destacam-se o frevo e o maracatu.",
             "O frevo, ritmo do Carnaval pernambucano, foi reconhecido pela UNESCO como Patrimônio Cultural Imaterial da Humanidade em 2012.",
             aliases=["carnaval brasileiro", "festa de Carnaval"]),
    conceito("mundo_festa_junina", "festa junina", "artes", IPHAN, S,
             "Festa junina é o conjunto de celebrações populares realizadas em junho no Brasil em homenagem a santos católicos, sobretudo Santo Antônio, São João e São Pedro.",
             "Na festa junina, os dias de Santo Antônio, São João e São Pedro são comemorados em 13, 24 e 29 de junho.",
             "A festa junina veio com os portugueses, a partir de festas europeias ligadas ao solstício e às colheitas, e ganhou no Brasil elementos da vida rural.",
             "A festa junina tem fogueira, quadrilha, roupas caipiras, bandeirinhas e comidas de milho, como pamonha, canjica e curau, além de quentão e pé de moleque.",
             "As maiores festas juninas do Brasil acontecem no Nordeste, com destaque para Campina Grande, na Paraíba, e Caruaru, em Pernambuco.",
             aliases=["festas juninas", "São João", "festa de São João", "arraial"]),
    conceito("mundo_natal", "Natal", "sociologia", SOC, S,
             "Natal é a festa cristã que celebra o nascimento de Jesus Cristo, comemorada em 25 de dezembro na maioria das igrejas cristãs.",
             "A data de 25 de dezembro para o Natal foi fixada em Roma no século IV; parte das igrejas ortodoxas comemora o Natal em 7 de janeiro, por seguir o calendário juliano.",
             "Símbolos do Natal incluem o presépio, popularizado por São Francisco de Assis em 1223, a árvore de Natal e o Papai Noel, inspirado em São Nicolau.",
             "No Brasil, o Natal acontece no verão, porque as estações do Hemisfério Sul são opostas às do Hemisfério Norte.",
             "No Brasil, o Natal é feriado nacional, e a ceia da noite de 24 de dezembro costuma ter peru, chester, rabanada e panetone.",
             aliases=["festa de Natal", "dia de Natal", "noite de Natal"]),
    conceito("mundo_pascoa", "Páscoa", "sociologia", SOC, S,
             "Páscoa é a principal festa cristã, que celebra a ressurreição de Jesus Cristo.",
             "A Páscoa tem data móvel: cai no primeiro domingo depois da primeira lua cheia que ocorre a partir de 21 de março, sempre entre 22 de março e 25 de abril.",
             "A regra de cálculo da data da Páscoa remonta ao Concílio de Niceia, em 325.",
             "A Páscoa cristã está ligada ao Pessach, a Páscoa judaica, que lembra a libertação dos hebreus da escravidão no Egito.",
             "A data da Páscoa define outras datas do calendário, como o Carnaval, 47 dias antes, a Sexta-feira Santa, dois dias antes, e Corpus Christi, 60 dias depois.",
             "No Brasil, a Páscoa é associada à troca de ovos de chocolate, e a Sexta-feira Santa, que a antecede, é feriado nacional.",
             aliases=["domingo de Páscoa", "Pascoa"]),
    conceito("mundo_feijoada", "feijoada", "alimentos", IPHAN, S,
             "Feijoada é um prato típico brasileiro feito de feijão-preto cozido com carnes de porco salgadas e defumadas, linguiça e carne-seca.",
             "A feijoada costuma ser servida com arroz branco, couve refogada, farofa, torresmo e laranja em fatias.",
             "A ideia de que a feijoada nasceu nas senzalas, com sobras de carne dadas aos escravizados, é contestada por historiadores, que a relacionam a cozidos europeus como o cozido português.",
             "Em muitos restaurantes do Rio de Janeiro e de São Paulo, a feijoada é tradicionalmente servida às quartas-feiras e aos sábados.",
             aliases=["feijoada completa"]),
    conceito("mundo_arroz_e_feijao", "arroz e feijão", "alimentos", MS, C,
             "Arroz e feijão é a combinação básica da alimentação brasileira, presente diariamente na mesa de grande parte da população.",
             "Arroz e feijão se completam nutricionalmente: o feijão é rico no aminoácido lisina, escasso no arroz, e o arroz fornece metionina, escassa no feijão, formando uma proteína de boa qualidade.",
             "O Guia Alimentar para a População Brasileira, do Ministério da Saúde (2014), cita o arroz com feijão como exemplo de refeição baseada em alimentos in natura ou minimamente processados.",
             "O feijão-carioca é o tipo de feijão mais consumido no Brasil; o feijão-preto predomina no Rio de Janeiro e no Sul.",
             "A Embrapa Arroz e Feijão, centro de pesquisa dedicado às duas culturas, fica em Santo Antônio de Goiás, em Goiás.",
             aliases=["arroz com feijão", "feijão com arroz"]),
    conceito("mundo_cacau", "cacau", "alimentos", EMB, C,
             "Cacau é o fruto do cacaueiro (Theobroma cacao), árvore nativa da América tropical cujas sementes são a matéria-prima do chocolate.",
             "As sementes de cacau são fermentadas, secas e torradas para produzir a massa de cacau, a manteiga de cacau e o cacau em pó.",
             "Costa do Marfim e Gana são os maiores produtores mundiais de cacau; no Brasil, os principais produtores são o Pará e a Bahia.",
             "No sul da Bahia, o cacau é cultivado tradicionalmente no sistema cabruca, sob a sombra de árvores da Mata Atlântica.",
             "A doença vassoura-de-bruxa, causada por um fungo, devastou as lavouras de cacau da Bahia a partir de 1989.",
             aliases=["cacaueiro", "Theobroma cacao"]),
    conceito("mundo_chocolate", "chocolate", "alimentos", EMB, C,
             "Chocolate é um alimento que vem do cacau: é feito de derivados das sementes de cacau, como massa e manteiga de cacau, geralmente misturados com açúcar.",
             "O chocolate amargo tem mais cacau; o chocolate ao leite leva leite; o chocolate branco é feito de manteiga de cacau, sem a massa escura do cacau.",
             "Maias e astecas consumiam uma bebida amarga de cacau; o chocolate chegou à Europa no século XVI, levado pelos espanhóis.",
             "No Brasil, uma lei de 2026, em vigor a partir de maio de 2027, exige que o produto chamado chocolate tenha pelo menos 35% de sólidos de cacau (25% no chocolate ao leite); até lá vale a regra da Anvisa de no mínimo 25% de sólidos totais de cacau.",
             "O chocolate contém teobromina, substância estimulante que é tóxica para cães e gatos.",
             aliases=["chocolates"]),
    conceito("mundo_cafe", "café", "alimentos", EMB, C,
             "Café é a bebida feita com sementes torradas e moídas do cafeeiro, planta do gênero Coffea, e também o nome desses grãos.",
             "As duas espécies de café mais cultivadas são o arábica (Coffea arabica), originário da Etiópia, e o robusta ou conilon (Coffea canephora).",
             "O café chegou ao Brasil em 1727, trazido para o Pará por Francisco de Melo Palheta, e foi a base da economia brasileira no século XIX e início do XX.",
             "O Brasil é o maior produtor e exportador de café do mundo; Minas Gerais é o maior estado produtor, e o Espírito Santo lidera a produção de conilon.",
             "O café contém cafeína, estimulante que reduz a sensação de cansaço ao bloquear os receptores de adenosina no cérebro.",
             aliases=["cafeeiro", "grão de café"]),
    conceito("mundo_gluten", "glúten", "alimentos", MS, C,
             "Glúten é a rede de proteínas (gliadinas e gluteninas) que se forma quando a farinha de trigo é misturada com água e dá elasticidade às massas.",
             "O glúten está presente no trigo, no centeio, na cevada e no malte; arroz, milho, mandioca e batata não contêm glúten.",
             "Pessoas com doença celíaca, que afeta cerca de 1% da população, têm uma reação autoimune ao glúten que lesa o intestino delgado e precisam evitá-lo por toda a vida.",
             "No Brasil, a Lei 10.674 de 2003 obriga os rótulos de alimentos a informar \"contém glúten\" ou \"não contém glúten\".",
             aliases=["gluten", "sem glúten"]),
    conceito("mundo_lactose", "lactose", "alimentos", BIO, C,
             "Lactose é o açúcar natural do leite, um dissacarídeo formado pela união de glicose e galactose.",
             "A lactose é digerida no intestino delgado pela enzima lactase, que a separa em glicose e galactose.",
             "O leite de vaca tem cerca de 5% de lactose; queijos curados e iogurtes têm bem menos, porque parte da lactose é consumida na fermentação.",
             aliases=["açúcar do leite"]),
    conceito("mundo_intolerancia_lactose", "intolerância à lactose", "alimentos", MS, C,
             "Intolerância à lactose é a dificuldade de digerir a lactose, o açúcar do leite, por produção insuficiente da enzima lactase.",
             "Na intolerância à lactose, a lactose não digerida fermenta no intestino grosso e causa gases, inchaço, cólicas e diarreia.",
             "Intolerância à lactose não é alergia: a alergia à proteína do leite de vaca é uma reação do sistema imunológico, que pode ser grave.",
             "A redução da lactase depois da infância é comum: a maioria dos adultos no mundo tem algum grau de intolerância à lactose.",
             "No Brasil, a Anvisa permite o rótulo \"zero lactose\" para alimentos com até 100 mg de lactose por 100 g ou 100 ml.",
             aliases=["intolerante à lactose", "intolerância ao leite"]),
    # ---------- língua e literatura ----------
    conceito("mundo_alfabeto_portugues", "alfabeto da língua portuguesa", "linguistica", PLAN, S,
             "O alfabeto da língua portuguesa tem 26 letras, de A a Z, desde o Acordo Ortográfico de 1990.",
             "O Acordo Ortográfico de 1990 reincorporou ao alfabeto português as letras K, W e Y, que antes não faziam parte oficialmente dele, quando o alfabeto tinha 23 letras.",
             "No Brasil, o Acordo Ortográfico de 1990 entrou em vigor em 1º de janeiro de 2009 e passou a ser obrigatório em 2016.",
             "O alfabeto da língua portuguesa tem 5 vogais (A, E, I, O, U) e 21 consoantes.",
             "As letras K, W e Y são usadas em nomes estrangeiros e seus derivados e em símbolos, como km, kg e W (watt).",
             "Ç, á, â, ã e outras letras com sinais gráficos não são letras separadas do alfabeto português: são letras com diacríticos, como cedilha, acentos e til.",
             aliases=["alfabeto português", "quantas letras tem o alfabeto", "letras do alfabeto"]),
    conceito("mundo_os_lusiadas", "Os Lusíadas", "literatura", ABL, S,
             "Os Lusíadas é o poema épico de Luís de Camões, publicado em 1572, considerado a obra máxima da literatura em língua portuguesa.",
             "Os Lusíadas narra a viagem de Vasco da Gama às Índias (1497–1498) e exalta a história de Portugal.",
             "Os Lusíadas tem 10 cantos e 1.102 estrofes em oitava rima, com versos decassílabos, num total de 8.816 versos.",
             "Os Lusíadas começa com o verso \"As armas e os barões assinalados\".",
             "Episódios famosos de Os Lusíadas são os de Inês de Castro, do Gigante Adamastor, do Velho do Restelo e da Ilha dos Amores.",
             aliases=["Lusíadas", "Lusiadas"]),
    conceito("mundo_luis_de_camoes", "Luís de Camões", "literatura", ABL, S,
             "Luís de Camões foi um poeta português do século XVI (c. 1524–1580), autor de Os Lusíadas e o maior nome da poesia clássica em língua portuguesa.",
             "Luís de Camões também escreveu poesia lírica, com sonetos célebres como \"Amor é fogo que arde sem se ver\".",
             "Luís de Camões perdeu um olho em combate no norte da África e viveu anos no Oriente, em lugares como Goa e Macau.",
             "Luís de Camões morreu em Lisboa em 10 de junho de 1580; a data é o Dia de Portugal, de Camões e das Comunidades Portuguesas.",
             "O Prêmio Camões, criado em 1988 por Portugal e Brasil, é o principal prêmio literário da língua portuguesa e homenageia Luís de Camões.",
             aliases=["Camões", "Camoes", "Luis de Camões"]),
    conceito("mundo_carlos_drummond", "Carlos Drummond de Andrade", "literatura", ABL, S,
             "Carlos Drummond de Andrade (1902–1987) foi um poeta, cronista e contista mineiro, considerado um dos maiores poetas brasileiros do século XX.",
             "Carlos Drummond de Andrade nasceu em Itabira, Minas Gerais, em 31 de outubro de 1902, e morreu no Rio de Janeiro em 17 de agosto de 1987.",
             "Carlos Drummond de Andrade estreou em livro com Alguma Poesia (1930), que traz o \"Poema de Sete Faces\" e o poema \"No meio do caminho\", sobre a pedra no caminho.",
             "Obras importantes de Carlos Drummond de Andrade incluem Sentimento do Mundo (1940), José (1942), com o verso \"E agora, José?\", e A Rosa do Povo (1945).",
             "Carlos Drummond de Andrade trabalhou como funcionário público no Ministério da Educação e escreveu crônicas para jornais por décadas.",
             aliases=["Drummond", "Carlos Drummond"]),
    conceito("mundo_cecilia_meireles", "Cecília Meireles", "literatura", ABL, S,
             "Cecília Meireles (1901–1964) foi uma poeta, professora e jornalista carioca, uma das maiores vozes da poesia brasileira.",
             "Cecília Meireles nasceu no Rio de Janeiro em 7 de novembro de 1901, ficou órfã cedo e foi criada pela avó; morreu no Rio em 9 de novembro de 1964.",
             "O livro Viagem (1939), de Cecília Meireles, recebeu o prêmio de poesia da Academia Brasileira de Letras.",
             "Obras conhecidas de Cecília Meireles incluem Romanceiro da Inconfidência (1953) e Ou Isto ou Aquilo (1964), de poesia para crianças.",
             "Cecília Meireles criou em 1934, no Rio de Janeiro, uma das primeiras bibliotecas infantis do Brasil.",
             aliases=["Cecilia Meireles"]),
    conceito("mundo_jorge_amado", "Jorge Amado", "literatura", ABL, S,
             "Jorge Amado (1912–2001) foi um romancista baiano, um dos escritores brasileiros mais lidos e traduzidos no mundo.",
             "Jorge Amado nasceu em 10 de agosto de 1912, numa fazenda de cacau na região de Itabuna, na Bahia, e morreu em Salvador em 6 de agosto de 2001.",
             "Obras famosas de Jorge Amado incluem Capitães da Areia (1937), Gabriela, Cravo e Canela (1958), Dona Flor e Seus Dois Maridos (1966) e Tieta do Agreste (1977).",
             "Os romances de Jorge Amado retratam a Bahia, a região do cacau, a cultura afro-brasileira e a vida popular de Salvador, e muitos viraram novelas e filmes.",
             "Jorge Amado foi deputado federal constituinte em 1946 e eleito para a Academia Brasileira de Letras em 1961; foi casado com a escritora Zélia Gattai.",
             aliases=["Jorge Leal Amado de Faria"]),
    conceito("mundo_monteiro_lobato", "Monteiro Lobato", "literatura", ABL, S,
             "Monteiro Lobato (1882–1948) foi um escritor e editor paulista, considerado o pai da literatura infantil brasileira.",
             "Monteiro Lobato nasceu em Taubaté, São Paulo, em 18 de abril de 1882, e morreu em São Paulo em 4 de julho de 1948; o Dia Nacional do Livro Infantil, 18 de abril, homenageia seu nascimento.",
             "Monteiro Lobato criou o Sítio do Picapau Amarelo, com personagens como Emília, Narizinho, Pedrinho, Dona Benta, Tia Nastácia e o Visconde de Sabugosa.",
             "Para adultos, Monteiro Lobato escreveu Urupês (1918), que criou o personagem Jeca Tatu, e defendeu a exploração do petróleo no Brasil, o que o levou à prisão em 1941, no Estado Novo.",
             "Parte da obra de Monteiro Lobato é hoje debatida por conter representações racistas, sobretudo de personagens negros.",
             aliases=["Lobato", "José Bento Monteiro Lobato"]),
    conceito("mundo_tom_jobim", "Tom Jobim", "artes", ABL, S,
             "Tom Jobim (1927–1994) foi um compositor, pianista e cantor carioca, um dos criadores da bossa nova.",
             "Tom Jobim, nome artístico de Antônio Carlos Brasileiro de Almeida Jobim, nasceu no Rio de Janeiro em 25 de janeiro de 1927 e morreu em Nova York em 8 de dezembro de 1994.",
             "Canções de Tom Jobim incluem \"Garota de Ipanema\" e \"Chega de Saudade\", ambas com Vinicius de Moraes, além de \"Águas de Março\", \"Wave\" e \"Desafinado\".",
             "A gravação de \"Chega de Saudade\" por João Gilberto, em 1958, é considerada o marco inicial da bossa nova, e o álbum Getz/Gilberto (1964), com Tom Jobim, levou o gênero ao mundo.",
             "O Aeroporto Internacional do Rio de Janeiro, o Galeão, recebeu o nome de Tom Jobim em sua homenagem.",
             aliases=["Antônio Carlos Jobim", "Antonio Carlos Jobim", "Jobim"]),
    # ---------- sociedade e mente ----------
    conceito("mundo_racismo", "racismo", "sociologia", SOC, S,
             "Racismo é a crença de que existem grupos humanos superiores ou inferiores por sua raça, cor ou origem étnica, e a discriminação que resulta dessa crença.",
             "A genética mostra que não existem raças humanas biologicamente distintas: a variação genética dentro de cada grupo é maior do que entre grupos; raça é uma construção social.",
             "No Brasil, a Constituição de 1988 define a prática do racismo como crime inafiançável e imprescritível, e a Lei 7.716 de 1989, conhecida como Lei Caó, define esses crimes.",
             "Desde a Lei 14.532 de 2023, a injúria racial, ofensa a uma pessoa por sua raça ou cor, é tratada no Brasil como crime de racismo.",
             "O dia 20 de novembro, Dia Nacional de Zumbi e da Consciência Negra, tornou-se feriado nacional no Brasil a partir de 2024.",
             aliases=["discriminação racial", "preconceito racial"]),
    conceito("mundo_preconceito", "preconceito", "sociologia", SOC, S,
             "Preconceito é uma opinião ou atitude negativa formada previamente sobre uma pessoa ou grupo, com base apenas em seu pertencimento a esse grupo e não no conhecimento real.",
             "A sociologia distingue preconceito, que é uma atitude, de estereótipo, que é uma generalização simplificada, e de discriminação, que é o tratamento desigual na prática.",
             "O preconceito pode se basear em cor, origem, religião, gênero, orientação sexual, idade, classe social, deficiência ou forma de falar.",
             "No Brasil, a Lei 7.716 de 1989 pune a discriminação por raça, cor, etnia, religião e procedência nacional; em 2019, o STF enquadrou a homofobia e a transfobia nessa lei.",
             "Segundo a hipótese do contato, proposta pelo psicólogo Gordon Allport em 1954, a convivência em condições de igualdade entre grupos tende a reduzir o preconceito.",
             aliases=["preconceitos"]),
    conceito("mundo_inteligencia_emocional", "inteligência emocional", "psicologia", PSI, C,
             "Inteligência emocional é a capacidade de perceber, compreender, usar e controlar as próprias emoções e de reconhecer e lidar com as emoções dos outros.",
             "O conceito de inteligência emocional foi proposto pelos psicólogos Peter Salovey e John Mayer em 1990 e popularizado pelo livro Inteligência Emocional, de Daniel Goleman, em 1995.",
             "Daniel Goleman descreveu a inteligência emocional em cinco componentes: autoconsciência, autocontrole, automotivação, empatia e habilidades sociais.",
             "A medição e o poder de previsão da inteligência emocional ainda são debatidos na psicologia, e o conceito é distinto do QI, que mede habilidades cognitivas.",
             aliases=["QE", "quociente emocional"]),
    # ---------- meio ambiente ----------
    conceito("mundo_chuva_acida", "chuva ácida", "ambiente", QUI, C,
             "Chuva ácida é a precipitação com acidez acima do normal, com pH abaixo de cerca de 5,6, causada por poluentes lançados na atmosfera.",
             "A chuva ácida se forma quando o dióxido de enxofre (SO2) e os óxidos de nitrogênio (NOx), liberados pela queima de combustíveis fósseis, reagem com a água do ar e formam ácidos sulfúrico e nítrico.",
             "A chuva ácida acidifica lagos e solos, prejudica florestas e corrói monumentos de mármore e calcário, metais e construções.",
             "A chuva ácida é reduzida com combustíveis com menos enxofre, filtros nas chaminés das indústrias e catalisadores nos veículos.",
             "A chuva normal já é levemente ácida, com pH perto de 5,6, porque o gás carbônico do ar se dissolve na água e forma ácido carbônico."),
    conceito("mundo_reciclagem", "reciclagem", "ambiente", MMA, C,
             "Reciclagem é o processo de transformar materiais descartados, como papel, plástico, vidro e metal, em matéria-prima para fabricar novos produtos.",
             "Reciclagem é diferente de reutilização: reutilizar é usar o objeto de novo sem transformá-lo, enquanto reciclar envolve reprocessar o material.",
             "A reciclagem economiza recursos naturais, água e energia e diminui a quantidade de resíduos enviados a aterros: reciclar alumínio gasta cerca de 5% da energia necessária para produzi-lo a partir do minério.",
             "O Brasil recicla quase todas as latas de alumínio que consome, com índices acima de 95%, em grande parte graças ao trabalho dos catadores.",
             "Na Política Nacional de Resíduos Sólidos (Lei 12.305 de 2010), a ordem de prioridade é não gerar, reduzir, reutilizar, reciclar, tratar e, por último, dispor os rejeitos.",
             aliases=["reciclar", "reciclável", "materiais recicláveis"]),
    conceito("mundo_coleta_seletiva", "coleta seletiva", "ambiente", MMA, C,
             "Coleta seletiva é o recolhimento de resíduos previamente separados conforme o tipo, como recicláveis, orgânicos e rejeitos, para facilitar a reciclagem e a compostagem.",
             "Pelas cores da coleta seletiva definidas pela Resolução Conama 275 de 2001, azul é papel, vermelho é plástico, verde é vidro, amarelo é metal, marrom é orgânico e preto é madeira.",
             "Na coleta seletiva, a lixeira cinza recebe o lixo não reciclável, a laranja resíduos perigosos, a branca resíduos de saúde e a roxa resíduos radioativos.",
             "A coleta seletiva é prevista pela Política Nacional de Resíduos Sólidos (Lei 12.305 de 2010), e muitos municípios a fazem com cooperativas de catadores.",
             "Para a coleta seletiva funcionar, as embalagens devem ser descartadas limpas e secas, separadas dos restos de comida.",
             aliases=["separação do lixo", "cores da reciclagem", "lixo reciclável"]),
    conceito("mundo_residuos_solidos", "resíduos sólidos", "ambiente", MMA, C,
             "Resíduos sólidos, chamados popularmente de lixo, são os materiais descartados pelas atividades humanas em casas, comércio, indústrias e serviços.",
             "Cada brasileiro gera em média cerca de 1 kg de resíduos sólidos por dia, e cerca de metade desse total é matéria orgânica, como restos de comida.",
             "O destino adequado dos rejeitos de resíduos sólidos é o aterro sanitário, que tem solo impermeabilizado e drenagem do chorume e dos gases; o lixão é um despejo a céu aberto que contamina solo e água.",
             "A Política Nacional de Resíduos Sólidos (Lei 12.305 de 2010) determina o fim dos lixões e cria a responsabilidade compartilhada entre governos, empresas e consumidores.",
             "Restos orgânicos dos resíduos sólidos podem virar adubo pela compostagem, em vez de ir para o aterro.",
             aliases=["lixo", "lixo urbano", "resíduos sólidos urbanos"]),
    conceito("mundo_desmatamento", "desmatamento", "ambiente", MMA, C,
             "Desmatamento é a remoção da vegetação nativa de uma área, geralmente para pastagens, agricultura, mineração, extração de madeira ou expansão urbana.",
             "Na Amazônia brasileira, o desmatamento é monitorado pelo INPE por satélites, com o sistema PRODES, que mede a taxa anual, e o DETER, que emite alertas diários.",
             "Cerca de um quinto da área original da floresta amazônica no Brasil já foi desmatada, sobretudo para a criação de gado.",
             "O desmatamento causa perda de biodiversidade, erosão do solo, alterações no regime de chuvas e emissão de gás carbônico, sendo uma das maiores fontes de emissões de gases de efeito estufa do Brasil.",
             "A Mata Atlântica foi o bioma brasileiro mais desmatado: restam cerca de 12% de sua cobertura original em fragmentos bem conservados.",
             aliases=["desflorestamento", "devastação das florestas"]),
    conceito("mundo_poluicao", "poluição", "ambiente", MMA, C,
             "Poluição é a introdução no ambiente de substâncias ou formas de energia que causam danos à saúde humana, aos seres vivos e aos ecossistemas.",
             "Os principais tipos de poluição são a do ar, da água, do solo, a sonora, a luminosa, a visual e a térmica.",
             "Segundo a Organização Mundial da Saúde, a poluição do ar, externa e doméstica, está ligada a cerca de 7 milhões de mortes prematuras por ano no mundo.",
             "Os principais poluentes do ar são o material particulado fino, o ozônio, o dióxido de nitrogênio, o dióxido de enxofre e o monóxido de carbono.",
             "No Brasil, a falta de tratamento de esgoto é uma das principais causas de poluição da água: cerca de metade do esgoto gerado não é tratado.",
             aliases=["poluição ambiental"]),
    # ---------- engenharia do dia a dia ----------
    conceito("mundo_sustentacao_aviao", "sustentação aerodinâmica", "engenharia", NASA, C,
             "Sustentação aerodinâmica é a força, produzida principalmente pelas asas, que mantém um avião no ar ao se opor ao seu peso; é assim que um avião voa.",
             "A asa do avião gera sustentação ao desviar o ar para baixo: pela terceira lei de Newton, o ar empurra a asa para cima, e a pressão fica menor sobre a asa do que embaixo dela.",
             "Em voo, quatro forças atuam sobre um avião: sustentação, peso, tração (empuxo dos motores) e arrasto (resistência do ar).",
             "A sustentação aumenta com a velocidade, a densidade do ar, a área da asa e o ângulo de ataque; ângulo excessivo faz o fluxo se descolar da asa e causa o estol.",
             "A explicação de que o ar de cima e o de baixo da asa precisam chegar juntos ao bordo de fuga é falsa, segundo a NASA; o ar de cima chega antes.",
             "Flaps e slats, partes móveis das asas, aumentam a sustentação em baixa velocidade, durante a decolagem e o pouso.",
             aliases=["como um avião voa", "força de sustentação", "voo do avião", "como o avião voa"]),
    conceito("mundo_motor_combustao", "motor a combustão interna", "engenharia", FIS, C,
             "Motor a combustão interna é a máquina que queima combustível dentro de cilindros e usa a expansão dos gases quentes para empurrar pistões e gerar movimento.",
             "O motor a combustão de quatro tempos, ou ciclo Otto (1876), funciona em admissão, compressão, combustão (explosão) e escape; o virabrequim transforma o vaivém dos pistões em rotação.",
             "Nos motores a gasolina e a etanol, a mistura é acesa por uma vela de ignição; no motor a diesel, criado por Rudolf Diesel na década de 1890, o combustível se inflama pela alta compressão do ar.",
             "A maior parte da energia do combustível num motor a combustão vira calor: motores de carro a gasolina aproveitam tipicamente cerca de 20% a 35% dela como trabalho.",
             "O motor flex, lançado no Brasil em 2003, funciona com etanol, gasolina ou qualquer mistura dos dois; a gasolina brasileira tem etanol anidro misturado, 30% desde agosto de 2025.",
             aliases=["motor a combustão", "motor de explosão", "motor de quatro tempos"]),
    conceito("mundo_carro_eletrico", "carro elétrico", "engenharia", FIS, C,
             "Carro elétrico é um veículo movido por um ou mais motores elétricos alimentados por baterias recarregáveis, em vez de um motor a combustão.",
             "Os carros elétricos usam geralmente baterias de íon-lítio, recarregadas em tomadas comuns, de forma lenta, ou em carregadores rápidos de corrente contínua.",
             "O motor elétrico de um carro elétrico converte cerca de 85% a 90% da energia em movimento, muito mais que um motor a combustão, e a frenagem regenerativa recupera energia ao frear.",
             "Carro elétrico não emite poluentes pelo escapamento; suas emissões totais dependem de como a eletricidade é gerada, e a matriz elétrica brasileira é majoritariamente renovável.",
             "Carros híbridos combinam motor a combustão e motor elétrico; os híbridos plug-in também podem ser recarregados na tomada.",
             aliases=["carros elétricos", "veículo elétrico", "carro híbrido"]),
    conceito("mundo_geladeira", "geladeira", "engenharia", FIS, C,
             "Geladeira, ou refrigerador, é o eletrodoméstico que conserva alimentos; a geladeira funciona retirando calor de seu interior e liberando-o para o ambiente externo.",
             "A geladeira funciona pelo ciclo de refrigeração: um fluido refrigerante evapora em tubos internos (evaporador), absorvendo o calor dos alimentos, e depois é comprimido pelo compressor.",
             "Comprimido e quente, o refrigerante da geladeira passa pela grade traseira (condensador), onde perde calor e volta a ser líquido; uma válvula ou tubo capilar baixa sua pressão e o ciclo recomeça.",
             "A geladeira não produz frio: ela transporta calor do frio para o quente, o que só é possível gastando energia elétrica, como prevê a segunda lei da termodinâmica.",
             "Os gases CFC, que destroem a camada de ozônio, foram abandonados nas geladeiras após o Protocolo de Montreal (1987) e substituídos por gases como o isobutano (R-600a).",
             aliases=["refrigerador", "como funciona a geladeira", "frigorífico"]),
    conceito("mundo_barragem", "barragem", "engenharia", MMA, C,
             "Barragem é uma estrutura construída para reter água ou outros materiais, como rejeitos de mineração, formando um reservatório.",
             "Barragens de água servem para gerar energia em usinas hidrelétricas, abastecer cidades, irrigar lavouras e controlar enchentes.",
             "As barragens podem ser de concreto, de terra ou de enrocamento (blocos de rocha), conforme o terreno e os materiais disponíveis.",
             "Os rompimentos das barragens de rejeitos de mineração de Fundão, em Mariana (MG), em 2015, e do Córrego do Feijão, em Brumadinho (MG), em 2019, mataram 19 e cerca de 270 pessoas.",
             "A Política Nacional de Segurança de Barragens (Lei 12.334 de 2010) foi reforçada em 2020, quando a Lei 14.066 proibiu barragens de rejeitos construídas pelo método a montante.",
             aliases=["barragens", "represa"]),
]

if __name__ == "__main__":
    import sys
    salvar(sys.argv[1], "Sínteses próprias sobre cultura brasileira, festas, literatura, sociedade, meio ambiente, alimentos e "
           "engenharia do cotidiano, com base em manuais abertos (OpenStax, CC BY 4.0), material de domínio público da NASA e "
           "referências institucionais brasileiras. Números são aproximações correntes e podem mudar.", FONTES, ITENS)
