from comum import conceito, referencia, salvar

FIFA = "esp_fifa"
COI = "esp_coi"
COB = "esp_cob"
FIA = "esp_fia"
TERMOS = "https://www.gov.br/pt-br/termos-de-uso"
FONTES = [
    referencia(FIFA, "FIFA — Fédération Internationale de Football Association", "https://www.fifa.com/",
               "FIFA", "https://inside.fifa.com/legal/terms-of-service"),
    referencia(COI, "Comitê Olímpico Internacional — olympics.com", "https://www.olympics.com/",
               "Comitê Olímpico Internacional (COI)", "https://www.olympics.com/en/legal/terms-of-service"),
    referencia(COB, "Comitê Olímpico do Brasil", "https://www.cob.org.br/",
               "Comitê Olímpico do Brasil (COB)", "https://www.cob.org.br/"),
    referencia(FIA, "Federação Internacional de Automobilismo", "https://www.fia.com/",
               "Fédération Internationale de l'Automobile (FIA)", "https://www.fia.com/"),
]
S = "social"
E = "esporte"
P = "pessoas"

ITENS = [
    conceito("mundo_futebol", "futebol", E, FIFA, S,
             "Futebol é um esporte coletivo disputado por dois times de 11 jogadores cada, que tentam marcar gols chutando ou cabeceando a bola para dentro da meta adversária.",
             "No futebol, uma partida oficial tem 90 minutos, divididos em dois tempos de 45 minutos, com intervalo de 15 minutos e acréscimos definidos pelo árbitro.",
             "No futebol, apenas o goleiro pode tocar a bola com as mãos, e somente dentro da própria grande área; os demais jogadores usam pés, cabeça e corpo.",
             "As regras do futebol moderno foram codificadas na Inglaterra em 1863, com a fundação da Football Association; a FIFA, que governa o esporte no mundo, foi criada em 1904.",
             "O futebol é o esporte mais popular do Brasil; chegou ao país no fim do século XIX, e Charles Miller é tradicionalmente apontado como seu principal introdutor, em 1894.",
             aliases=["futebol de campo", "soccer", "regras do futebol"]),
    conceito("mundo_copa_do_mundo", "Copa do Mundo FIFA", E, FIFA, S,
             "Copa do Mundo FIFA é o principal torneio internacional de seleções de futebol masculino, organizado pela FIFA a cada quatro anos.",
             "A primeira Copa do Mundo FIFA foi disputada em 1930, no Uruguai, que também foi o campeão.",
             "O Brasil ganhou cinco Copas do Mundo FIFA, em 1958, 1962, 1970, 1994 e 2002, e é o maior vencedor do torneio; por isso é chamado de pentacampeão.",
             "O Brasil sediou a Copa do Mundo FIFA em 1950 e em 2014; em 1950 perdeu a final para o Uruguai no Maracanã, episódio conhecido como Maracanazo.",
             "A Copa do Mundo FIFA de 2026, disputada nos Estados Unidos, no Canadá e no México, foi a primeira com 48 seleções.",
             "A Copa do Mundo Feminina da FIFA é disputada desde 1991.",
             aliases=["Copa do Mundo", "Copa do Mundo de futebol", "Mundial de futebol", "Copa FIFA"]),
    conceito("mundo_selecao_brasileira", "seleção brasileira de futebol", E, FIFA, S,
             "Seleção brasileira de futebol é a equipe que representa o Brasil em competições internacionais de futebol, organizada pela Confederação Brasileira de Futebol (CBF).",
             "A seleção brasileira de futebol é a única que participou de todas as edições da Copa do Mundo FIFA.",
             "A seleção brasileira de futebol venceu cinco Copas do Mundo, em 1958, 1962, 1970, 1994 e 2002, e por isso é chamada de pentacampeã.",
             "A seleção brasileira de futebol joga tradicionalmente com camisa amarela, calção azul e meias brancas; o uniforme amarelo foi adotado em 1954.",
             "A seleção brasileira de futebol conquistou a medalha de ouro olímpica masculina nos Jogos do Rio 2016 e de Tóquio 2020.",
             aliases=["seleção brasileira", "Seleção Canarinho", "seleção do Brasil", "Canarinho"]),
    conceito("mundo_brasileirao", "Campeonato Brasileiro de futebol", E, FIFA, S,
             "Campeonato Brasileiro de futebol, conhecido como Brasileirão, é a principal competição nacional de clubes de futebol do Brasil, organizada pela CBF.",
             "O Campeonato Brasileiro de futebol é disputado desde 1971 com esse formato nacional; a CBF reconhece também os títulos da Taça Brasil e do Torneio Roberto Gomes Pedrosa, de 1959 a 1970.",
             "Desde 2003, o Campeonato Brasileiro de futebol é disputado em pontos corridos e, desde 2006, com 20 clubes que jogam entre si em turno e returno; o que somar mais pontos é campeão.",
             "No Campeonato Brasileiro de futebol, os quatro últimos colocados da Série A são rebaixados para a Série B.",
             aliases=["Brasileirão", "Campeonato Brasileiro", "Série A do Brasileiro"]),
    conceito("mundo_jogos_olimpicos", "Jogos Olímpicos", E, COI, S,
             "Jogos Olímpicos são o maior evento multiesportivo do mundo, organizado pelo Comitê Olímpico Internacional (COI), com edições de verão e de inverno a cada quatro anos.",
             "Os Jogos Olímpicos têm origem na Grécia Antiga, onde eram disputados em Olímpia, em honra a Zeus, a partir de 776 a.C., segundo a tradição.",
             "Os Jogos Olímpicos da era moderna começaram em 1896, em Atenas, por iniciativa do francês Pierre de Coubertin, fundador do COI em 1894.",
             "O Rio de Janeiro sediou os Jogos Olímpicos de 2016, os primeiros realizados na América do Sul.",
             "O símbolo dos Jogos Olímpicos são cinco anéis entrelaçados, nas cores azul, amarelo, preto, verde e vermelho, que representam a união dos continentes.",
             "Os Jogos Olímpicos de Paris foram em 2024, e os de Los Angeles estão marcados para 2028.",
             aliases=["Olimpíadas", "Olimpíada", "Jogos Olímpicos de verão", "Rio 2016"]),
    conceito("mundo_jogos_paralimpicos", "Jogos Paralímpicos", E, COI, S,
             "Jogos Paralímpicos são o principal evento multiesportivo para atletas com deficiência, realizados logo após os Jogos Olímpicos e na mesma cidade-sede.",
             "Os Jogos Paralímpicos têm origem nos Jogos de Stoke Mandeville, criados em 1948 na Inglaterra pelo médico Ludwig Guttmann para veteranos de guerra com lesão medular.",
             "A primeira edição dos Jogos Paralímpicos foi realizada em Roma, em 1960.",
             "Os Jogos Paralímpicos são organizados pelo Comitê Paralímpico Internacional; no Brasil, o esporte paralímpico é dirigido pelo Comitê Paralímpico Brasileiro.",
             "O Rio de Janeiro sediou os Jogos Paralímpicos de 2016.",
             aliases=["Paralimpíadas", "Paraolimpíadas", "Jogos Paraolímpicos", "Paralimpíada"]),
    conceito("mundo_jogos_pan_americanos", "Jogos Pan-Americanos", E, COB, S,
             "Jogos Pan-Americanos são uma competição multiesportiva entre países das Américas, realizada a cada quatro anos, no ano anterior aos Jogos Olímpicos.",
             "A primeira edição dos Jogos Pan-Americanos foi realizada em Buenos Aires, na Argentina, em 1951.",
             "O Brasil sediou os Jogos Pan-Americanos em São Paulo, em 1963, e no Rio de Janeiro, em 2007.",
             "Os Jogos Pan-Americanos são organizados pela Panam Sports, a organização dos comitês olímpicos das Américas.",
             aliases=["Pan-Americano", "Jogos Pan", "Pan-Americanos"]),
    conceito("mundo_volei", "voleibol", E, COB, S,
             "Voleibol, ou vôlei, é um esporte coletivo em que duas equipes de seis jogadores, separadas por uma rede, tentam fazer a bola tocar o chão da quadra adversária.",
             "O voleibol foi criado em 1895 nos Estados Unidos por William G. Morgan, professor de educação física da ACM.",
             "No voleibol, cada equipe pode dar até três toques na bola antes de passá-la; as partidas são em melhor de cinco sets, de 25 pontos, com o quinto set de 15 pontos.",
             "O vôlei de praia é disputado em duplas na areia e é esporte olímpico desde 1996.",
             "O Brasil é uma das maiores potências do voleibol, com medalhas de ouro olímpicas no masculino e no feminino.",
             aliases=["vôlei", "volei", "volleyball"]),
    conceito("mundo_basquete", "basquete", E, COI, S,
             "Basquete, ou basquetebol, é um esporte coletivo em que duas equipes de cinco jogadores tentam fazer a bola passar pela cesta adversária, presa a 3,05 metros do chão.",
             "O basquete foi inventado em 1891 nos Estados Unidos por James Naismith, professor canadense de educação física.",
             "No basquete, uma cesta vale 2 pontos, ou 3 pontos se arremessada de trás da linha de três pontos; cada lance livre vale 1 ponto.",
             "A NBA, liga profissional dos Estados Unidos e do Canadá, é a principal liga de basquete do mundo.",
             aliases=["basquetebol", "basketball", "bola ao cesto"]),
    conceito("mundo_tenis", "tênis", E, COI, S,
             "Tênis é um esporte de raquete disputado em quadra dividida por uma rede, entre dois jogadores (simples) ou duas duplas.",
             "A pontuação do tênis segue a sequência 15, 30, 40 e game; games formam sets, e o jogador precisa vencer 2 ou 3 sets, conforme o torneio.",
             "Os quatro torneios mais importantes do tênis, chamados Grand Slam, são o Aberto da Austrália, Roland Garros, Wimbledon e o Aberto dos Estados Unidos.",
             "O tênis moderno se desenvolveu na Inglaterra no século XIX; Wimbledon, o torneio mais antigo, é disputado desde 1877 em quadras de grama.",
             aliases=["tênis de campo", "tennis"]),
    conceito("mundo_formula_1", "Fórmula 1", E, FIA, S,
             "Fórmula 1 é a principal categoria do automobilismo mundial, com carros monopostos de rodas expostas, organizada pela Federação Internacional de Automobilismo (FIA).",
             "O Campeonato Mundial de Fórmula 1 existe desde 1950; cada temporada reúne dezenas de corridas chamadas Grandes Prêmios, disputadas em vários países.",
             "Na Fórmula 1, há dois títulos por temporada: o de pilotos e o de construtores, concedido às equipes.",
             "O Brasil tem três campeões mundiais de Fórmula 1: Emerson Fittipaldi (1972 e 1974), Nelson Piquet (1981, 1983 e 1987) e Ayrton Senna (1988, 1990 e 1991).",
             "O Grande Prêmio do Brasil de Fórmula 1 é disputado no Autódromo de Interlagos, em São Paulo.",
             aliases=["F1", "Formula 1", "Fórmula Um"]),
    conceito("mundo_natacao", "natação", E, COI, S,
             "Natação é o esporte de se deslocar na água usando braços e pernas, disputado em provas de velocidade e resistência.",
             "A natação competitiva tem quatro estilos: livre (geralmente o crawl), costas, peito e borboleta; o medley combina os quatro.",
             "As provas olímpicas de natação são disputadas em piscina de 50 metros; a maratona aquática, de 10 km, é nadada em águas abertas.",
             "A natação está presente nos Jogos Olímpicos desde a primeira edição moderna, em 1896.",
             "O americano Michael Phelps é o maior medalhista da história olímpica, com 28 medalhas, 23 delas de ouro, conquistadas na natação.",
             aliases=["natação competitiva", "esporte natação"]),
    conceito("mundo_atletismo", "atletismo", E, COI, S,
             "Atletismo é o conjunto de esportes de corrida, salto, arremesso e lançamento, considerado a base dos Jogos Olímpicos.",
             "O atletismo inclui provas de pista (corridas de velocidade, meio-fundo, fundo, com barreiras e revezamentos), provas de campo (saltos e lançamentos) e provas de rua, como a maratona.",
             "O decatlo masculino reúne dez provas de atletismo, e o heptatlo feminino, sete.",
             "Adhemar Ferreira da Silva foi bicampeão olímpico do salto triplo pelo Brasil, em 1952 e 1956.",
             aliases=["esportes de pista e campo", "atletismo olímpico"]),
    conceito("mundo_maratona", "maratona", E, COI, S,
             "Maratona é uma corrida de longa distância com percurso oficial de 42,195 quilômetros.",
             "O nome maratona vem da lenda grega de Fidípides, mensageiro que teria corrido da cidade de Maratona até Atenas para anunciar a vitória sobre os persas, em 490 a.C.",
             "A maratona foi disputada na primeira edição dos Jogos Olímpicos modernos, em 1896; a distância de 42,195 km foi fixada a partir dos Jogos de Londres de 1908.",
             "A Corrida Internacional de São Silvestre, em São Paulo, não é maratona: tem cerca de 15 km e é disputada no último dia do ano.",
             aliases=["corrida de maratona", "42 km"]),
    conceito("mundo_ginastica_artistica", "ginástica artística", E, COB, S,
             "Ginástica artística é um esporte olímpico em que atletas executam séries acrobáticas em aparelhos, avaliadas por notas de dificuldade e execução.",
             "Na ginástica artística feminina, os aparelhos são salto, barras assimétricas, trave e solo.",
             "Na ginástica artística masculina, os aparelhos são solo, cavalo com alças, argolas, salto, barras paralelas e barra fixa.",
             "Na ginástica artística, o Brasil conquistou ouros olímpicos com Arthur Zanetti, nas argolas, em Londres 2012, e Rebeca Andrade, no salto, em Tóquio 2020.",
             aliases=["ginástica olímpica"]),
    conceito("mundo_judo", "judô", E, COB, S,
             "Judô é uma arte marcial e esporte de combate criado no Japão em 1882 por Jigoro Kano, baseado em projeções, imobilizações e chaves.",
             "No judô, a vitória mais completa é o ippon, obtido por uma projeção perfeita, imobilização por 20 segundos ou desistência do adversário.",
             "Os judocas usam um uniforme chamado judogi, e a graduação é indicada pela cor da faixa, da branca à preta.",
             "O judô é esporte olímpico desde 1964 e é uma das modalidades que mais deram medalhas olímpicas ao Brasil.",
             aliases=["judo"]),
    conceito("mundo_surfe", "surfe", E, COB, S,
             "Surfe é o esporte de deslizar sobre as ondas do mar em pé sobre uma prancha.",
             "O surfe tem origem na Polinésia e no Havaí, onde era praticado há séculos antes da chegada dos europeus.",
             "O surfe estreou nos Jogos Olímpicos em Tóquio 2020, e o brasileiro Italo Ferreira foi o primeiro campeão olímpico masculino.",
             "Nas competições de surfe, juízes dão notas às ondas surfadas, considerando dificuldade, variedade de manobras e velocidade.",
             aliases=["surf"]),
    conceito("mundo_skate", "skate", E, COB, S,
             "Skate é o esporte praticado sobre uma prancha com quatro rodas, em que o atleta executa manobras em ruas, pistas e rampas.",
             "O skate surgiu na Califórnia, nos Estados Unidos, por volta dos anos 1950, inspirado no surfe.",
             "O skate estreou nos Jogos Olímpicos em Tóquio 2020, nas modalidades street e park.",
             "Em Tóquio 2020, a brasileira Rayssa Leal, então com 13 anos, ganhou a medalha de prata no skate street.",
             aliases=["skateboard", "skatismo"]),
    conceito("mundo_capoeira", "capoeira", E, COB, S,
             "Capoeira é uma manifestação cultural afro-brasileira que combina luta, dança, música e acrobacias, criada por africanos escravizados e seus descendentes no Brasil.",
             "Na capoeira, os participantes jogam em uma roda, ao som do berimbau, do atabaque e do pandeiro, com cantos em coro.",
             "A capoeira foi reprimida e chegou a ser crime no Código Penal de 1890; foi legalizada na década de 1930.",
             "As duas principais vertentes da capoeira são a Angola, associada a Mestre Pastinha, e a Regional, criada por Mestre Bimba.",
             "A roda de capoeira foi reconhecida pela UNESCO como Patrimônio Cultural Imaterial da Humanidade em 2014.",
             aliases=["roda de capoeira", "capoeirista"]),
    conceito("mundo_xadrez", "xadrez", E, COI, S,
             "Xadrez é um jogo de tabuleiro de estratégia para dois jogadores, reconhecido como esporte pelo Comitê Olímpico Internacional.",
             "O xadrez é jogado em um tabuleiro de 64 casas; cada jogador tem 16 peças: rei, dama, duas torres, dois bispos, dois cavalos e oito peões.",
             "O objetivo do xadrez é dar xeque-mate, isto é, atacar o rei adversário de modo que ele não possa escapar.",
             "O xadrez surgiu na Índia por volta do século VI, a partir de um jogo chamado chaturanga, e chegou à Europa pela Pérsia e pelo mundo árabe.",
             "O xadrez é organizado internacionalmente pela FIDE, fundada em 1924, que realiza o Campeonato Mundial e as Olimpíadas de Xadrez.",
             aliases=["jogo de xadrez", "chess"]),

    # pessoas
    conceito("mundo_pele_jogador", "Edson Arantes do Nascimento", P, FIFA, S,
             "Edson Arantes do Nascimento, o Pelé, foi um jogador de futebol brasileiro, considerado um dos maiores de todos os tempos e chamado de Rei do Futebol.",
             "Pelé nasceu em 23 de outubro de 1940, em Três Corações (MG), e morreu em 29 de dezembro de 2022, em São Paulo.",
             "Pelé é o único jogador a ganhar três Copas do Mundo: 1958, 1962 e 1970.",
             "Pelé jogou quase toda a carreira no Santos, de 1956 a 1974, e encerrou-a no New York Cosmos, dos Estados Unidos, em 1977.",
             "Pelé marcou mais de mil gols na carreira; o milésimo, segundo a contagem tradicional, foi de pênalti no Maracanã, em 1969.",
             aliases=["Pelé", "Rei do Futebol", "Edson Arantes"]),
    conceito("mundo_garrincha", "Garrincha", P, FIFA, S,
             "Garrincha, apelido de Manuel Francisco dos Santos, foi um ponta-direita brasileiro, famoso pelos dribles, bicampeão mundial de futebol em 1958 e 1962.",
             "Garrincha nasceu em 1933, em Pau Grande (RJ), e morreu em 1983, no Rio de Janeiro.",
             "Garrincha foi o principal destaque do Brasil na Copa do Mundo de 1962, quando Pelé se machucou no início do torneio.",
             "Garrincha jogou a maior parte da carreira no Botafogo e era chamado de Anjo das Pernas Tortas.",
             aliases=["Mané Garrincha", "Manuel Francisco dos Santos", "Anjo das Pernas Tortas"]),
    conceito("mundo_ayrton_senna", "Ayrton Senna", P, FIA, S,
             "Ayrton Senna foi um piloto brasileiro de Fórmula 1, tricampeão mundial em 1988, 1990 e 1991, todos pela equipe McLaren.",
             "Ayrton Senna nasceu em 21 de março de 1960, em São Paulo, e morreu em 1º de maio de 1994, após um acidente no Grande Prêmio de San Marino, em Ímola, na Itália.",
             "Ayrton Senna venceu 41 Grandes Prêmios e conquistou 65 pole positions na Fórmula 1.",
             "Ayrton Senna venceu seis vezes o Grande Prêmio de Mônaco, recorde da corrida.",
             "O Instituto Ayrton Senna, criado em 1994, atua na educação de crianças e jovens no Brasil.",
             aliases=["Senna", "Ayrton Senna da Silva"]),
    conceito("mundo_marta_futebol", "Marta Vieira da Silva", P, FIFA, S,
             "Marta Vieira da Silva, conhecida como Marta, é uma jogadora de futebol brasileira, eleita seis vezes a melhor jogadora do mundo pela FIFA.",
             "Marta nasceu em 1986, em Dois Riachos, Alagoas.",
             "Marta recebeu o prêmio de melhor jogadora do mundo da FIFA em 2006, 2007, 2008, 2009, 2010 e 2018.",
             "Marta é a maior artilheira da história das Copas do Mundo, somando homens e mulheres, com 17 gols.",
             "Com a seleção brasileira, Marta conquistou medalhas de prata olímpicas em 2004, 2008 e 2024.",
             aliases=["Marta", "Rainha Marta", "Marta jogadora"]),
    conceito("mundo_usain_bolt", "Usain Bolt", P, COI, S,
             "Usain Bolt é um ex-velocista jamaicano, considerado o maior corredor de provas de velocidade da história do atletismo.",
             "Usain Bolt detém os recordes mundiais dos 100 metros (9,58 segundos) e dos 200 metros (19,19 segundos), ambos de 2009.",
             "Usain Bolt ganhou oito medalhas de ouro olímpicas, sendo campeão dos 100 m e dos 200 m em Pequim 2008, Londres 2012 e Rio 2016.",
             "Usain Bolt nasceu em 1986, na Jamaica, e encerrou a carreira em 2017.",
             aliases=["Bolt"]),
    conceito("mundo_michael_jordan", "Michael Jordan", P, COI, S,
             "Michael Jordan é um ex-jogador de basquete norte-americano, considerado por muitos o maior jogador da história do esporte.",
             "Michael Jordan foi seis vezes campeão da NBA pelo Chicago Bulls, em 1991, 1992, 1993, 1996, 1997 e 1998.",
             "Michael Jordan ganhou duas medalhas de ouro olímpicas, em 1984 e em 1992, esta com o Dream Team dos Estados Unidos.",
             "Michael Jordan nasceu em 1963, no Brooklyn, em Nova York, e encerrou definitivamente a carreira em 2003.",
             aliases=["Jordan", "Air Jordan"]),
    conceito("mundo_maradona", "Diego Maradona", P, FIFA, S,
             "Diego Maradona foi um jogador de futebol argentino, considerado um dos maiores da história, campeão da Copa do Mundo de 1986.",
             "Diego Maradona nasceu em 1960, em Lanús, na Argentina, e morreu em 25 de novembro de 2020.",
             "Na Copa de 1986, contra a Inglaterra, Diego Maradona marcou o gol de mão chamado 'La Mano de Dios' e outro, driblando vários adversários, eleito o gol do século.",
             "Diego Maradona brilhou no Boca Juniors e no Napoli, da Itália, onde conquistou dois campeonatos italianos.",
             aliases=["Maradona", "Diego Armando Maradona"]),
    conceito("mundo_oscar_schmidt", "Oscar Schmidt", P, COB, S,
             "Oscar Schmidt, conhecido como Mão Santa, foi um jogador de basquete brasileiro, um dos maiores cestinhas da história do esporte.",
             "Oscar Schmidt marcou mais de 49 mil pontos na carreira, número considerado por muito tempo o recorde do basquete profissional.",
             "Oscar Schmidt disputou cinco Jogos Olímpicos e é o maior pontuador da história olímpica do basquete, com 1.093 pontos.",
             "Oscar Schmidt liderou o Brasil na vitória sobre os Estados Unidos na final dos Jogos Pan-Americanos de 1987, em Indianápolis.",
             aliases=["Mão Santa", "Oscar do basquete"]),
    conceito("mundo_gustavo_kuerten", "Gustavo Kuerten", P, COB, S,
             "Gustavo Kuerten, o Guga, é um ex-tenista brasileiro, tricampeão do torneio de Roland Garros, em 1997, 2000 e 2001.",
             "Gustavo Kuerten nasceu em 1976, em Florianópolis (SC), e encerrou a carreira em 2008.",
             "Gustavo Kuerten foi o primeiro brasileiro a ocupar o primeiro lugar do ranking mundial de tênis da ATP, terminando o ano de 2000 como número 1.",
             "Gustavo Kuerten ficou conhecido por desenhar um coração no saibro de Roland Garros após a vitória de 2001.",
             aliases=["Guga", "Guga Kuerten"]),
]

LIGACOES = []
COMPARACOES = []

if __name__ == "__main__":
    import sys
    salvar(sys.argv[1], "Sínteses próprias de esporte (modalidades, competições e atletas falecidos ou com carreira "
           "encerrada), com fatos consolidados e referências institucionais (FIFA, COI, COB, FIA). Recordes e números "
           "refletem a situação consolidada até 2026.", FONTES, ITENS, LIGACOES, COMPARACOES)
