from comum import conceito, referencia, salvar

IB = "eb_ibge_cidades_estados"
FONTES = [
    referencia(IB, "IBGE Cidades e Estados — panorama das unidades da federação", "https://cidades.ibge.gov.br/",
               "Instituto Brasileiro de Geografia e Estatística (IBGE)", "https://www.gov.br/pt-br/termos-de-uso"),
]
S = "social"
A = "geografia"


def estado(ident, nome, *fatos, aliases=()):
    return conceito(ident, nome, A, IB, S, *fatos, aliases=aliases)


ITENS = [
    # Regiões
    estado("mundo_regiao_norte", "região Norte",
           "A região Norte é a maior das cinco regiões do Brasil em área, formada por Acre, Amapá, Amazonas, Pará, Rondônia, Roraima e Tocantins.",
           "A região Norte ocupa cerca de 45% do território brasileiro e tem cerca de 17 milhões de habitantes, a menor densidade demográfica do país.",
           "A região Norte é dominada pela Floresta Amazônica e pela bacia do rio Amazonas.",
           "As maiores cidades da região Norte são Manaus e Belém.",
           aliases=["Norte do Brasil", "região Norte do Brasil"]),
    estado("mundo_regiao_nordeste", "região Nordeste",
           "A região Nordeste é uma das cinco regiões do Brasil, formada por nove estados: Maranhão, Piauí, Ceará, Rio Grande do Norte, Paraíba, Pernambuco, Alagoas, Sergipe e Bahia.",
           "A região Nordeste tem cerca de 55 milhões de habitantes, a segunda região mais populosa do Brasil, e ocupa cerca de 18% do território.",
           "No interior da região Nordeste fica o Sertão, de clima semiárido e vegetação de Caatinga; o litoral é conhecido por praias e pelo turismo.",
           "A região Nordeste foi o centro da colonização portuguesa nos séculos XVI e XVII, com a economia do açúcar, e Salvador foi a primeira capital do Brasil.",
           aliases=["Nordeste", "Nordeste brasileiro", "Nordeste do Brasil"]),
    estado("mundo_regiao_centro_oeste", "região Centro-Oeste",
           "A região Centro-Oeste é uma das cinco regiões do Brasil, formada por Goiás, Mato Grosso, Mato Grosso do Sul e o Distrito Federal, onde fica Brasília.",
           "A região Centro-Oeste é a menos populosa do Brasil, com cerca de 16 milhões de habitantes, e ocupa cerca de 19% do território.",
           "A região Centro-Oeste é grande produtora de soja, milho, algodão e carne bovina.",
           "Na região Centro-Oeste predominam o Cerrado e o Pantanal.",
           aliases=["Centro-Oeste", "Centro-Oeste brasileiro"]),
    estado("mundo_regiao_sudeste", "região Sudeste",
           "A região Sudeste é uma das cinco regiões do Brasil, formada por São Paulo, Rio de Janeiro, Minas Gerais e Espírito Santo.",
           "A região Sudeste é a mais populosa do Brasil, com cerca de 85 milhões de habitantes, perto de 42% da população, em cerca de 11% do território.",
           "A região Sudeste concentra a maior parte do PIB brasileiro, com indústria, serviços, finanças e agropecuária.",
           "As maiores cidades da região Sudeste são São Paulo, Rio de Janeiro e Belo Horizonte.",
           aliases=["Sudeste", "Sudeste brasileiro"]),
    estado("mundo_regiao_sul", "região Sul",
           "A região Sul é a menor das cinco regiões do Brasil em área, formada por Paraná, Santa Catarina e Rio Grande do Sul.",
           "A região Sul ocupa cerca de 7% do território brasileiro e tem cerca de 30 milhões de habitantes.",
           "A região Sul tem clima subtropical, com as quatro estações bem marcadas e invernos mais frios, com geada e às vezes neve nas serras.",
           "A região Sul recebeu muitos imigrantes europeus nos séculos XIX e XX, sobretudo alemães, italianos, poloneses e ucranianos.",
           aliases=["Sul do Brasil", "região Sul do Brasil"]),

    # Região Norte
    estado("mundo_estado_acre", "Acre",
           "O Acre é um estado brasileiro que fica na região Norte, de sigla AC, na fronteira com o Peru e a Bolívia.",
           "A capital do Acre é Rio Branco.",
           "O Acre tem cerca de 830 mil habitantes e área de cerca de 164 mil km², quase toda coberta pela Floresta Amazônica.",
           "A economia do Acre se baseia no extrativismo, como borracha e castanha, na pecuária e no serviço público.",
           "O Acre pertencia à Bolívia e foi incorporado ao Brasil pelo Tratado de Petrópolis, em 1903; o seringueiro Chico Mendes, defensor da floresta, era acriano.",
           aliases=["estado do Acre"]),
    estado("mundo_estado_amapa", "Amapá",
           "O Amapá é um estado brasileiro que fica na região Norte, de sigla AP, no extremo norte do país, na fronteira com a Guiana Francesa e o Suriname.",
           "A capital do Amapá é Macapá.",
           "O Amapá tem cerca de 730 mil habitantes, um dos estados menos populosos, e área de cerca de 142 mil km².",
           "O Amapá é cortado pela linha do Equador, que passa por Macapá, e tem grande parte do território preservado em áreas protegidas.",
           "O Amapá foi território federal até 1988, quando a Constituição o transformou em estado.",
           aliases=["estado do Amapá"]),
    estado("mundo_estado_amazonas", "Amazonas",
           "O Amazonas é um estado brasileiro que fica na região Norte, de sigla AM, e o maior estado brasileiro em área.",
           "A capital do Amazonas é Manaus.",
           "O Amazonas tem cerca de 1,56 milhão de km², quase um quinto do território nacional, e cerca de 3,9 milhões de habitantes, metade deles em Manaus.",
           "O Amazonas é coberto em grande parte pela Floresta Amazônica e cortado pelos rios Negro, Solimões e Amazonas; a Zona Franca de Manaus concentra sua indústria.",
           "O Amazonas tem a maior população indígena do Brasil, e o Festival de Parintins, com os bois Garantido e Caprichoso, é sua festa mais famosa.",
           aliases=["estado do Amazonas"]),
    estado("mundo_estado_para", "Pará",
           "O Pará é um estado brasileiro que fica na região Norte, de sigla PA, e o segundo maior estado brasileiro em área.",
           "A capital do Pará é Belém.",
           "O Pará tem cerca de 1,25 milhão de km² e cerca de 8,1 milhões de habitantes, o estado mais populoso da região Norte.",
           "A economia do Pará se destaca pela mineração, com a Serra dos Carajás, maior produtora de minério de ferro do país, e pela usina hidrelétrica de Tucuruí.",
           "O Pará é conhecido pelo Círio de Nazaré, grande procissão católica em Belém, e pela culinária com açaí, tacacá e pato no tucupi.",
           aliases=["estado do Pará"]),
    estado("mundo_estado_rondonia", "estado de Rondônia",
           "Rondônia é um estado brasileiro que fica na região Norte, de sigla RO, na fronteira com a Bolívia.",
           "A capital de Rondônia é Porto Velho.",
           "A população de Rondônia é de cerca de 1,6 milhão de habitantes, e a área do estado é de cerca de 238 mil km².",
           "A economia de Rondônia se baseia na agropecuária, com gado e soja, e em hidrelétricas no rio Madeira, como Santo Antônio e Jirau.",
           "O nome Rondônia homenageia o marechal Cândido Rondon; a região foi marcada pela Estrada de Ferro Madeira-Mamoré, construída no início do século XX.",
           aliases=["Rondônia"]),
    estado("mundo_estado_roraima", "estado de Roraima",
           "Roraima é um estado brasileiro que fica na região Norte, de sigla RR, no extremo norte do país, na fronteira com a Venezuela e a Guiana.",
           "A capital de Roraima é Boa Vista.",
           "Roraima é o estado menos populoso do Brasil, com cerca de 640 mil habitantes, e tem área de cerca de 224 mil km².",
           "Roraima abriga o Monte Roraima, na tríplice fronteira com Venezuela e Guiana, e grande parte do estado é terra indígena, como a Yanomami e a Raposa Serra do Sol.",
           "A cidade de Boa Vista, capital de Roraima, é a única capital brasileira totalmente ao norte da linha do Equador.",
           aliases=["Roraima"]),
    estado("mundo_estado_tocantins", "Tocantins",
           "O Tocantins é um estado brasileiro que fica na região Norte, de sigla TO, criado em 1988 a partir do norte de Goiás.",
           "A capital do Tocantins é Palmas.",
           "O Tocantins tem cerca de 1,5 milhão de habitantes e área de cerca de 277 mil km².",
           "O Tocantins fica numa área de transição entre o Cerrado e a Amazônia e abriga o Jalapão, conhecido pelas dunas e fervedouros, e a Ilha do Bananal.",
           "A cidade de Palmas, capital do Tocantins, foi planejada e fundada em 1989, sendo a capital estadual mais nova do Brasil.",
           aliases=["estado do Tocantins"]),

    # Região Nordeste
    estado("mundo_estado_maranhao", "Maranhão",
           "O Maranhão é um estado brasileiro que fica na região Nordeste, de sigla MA, na transição entre o Nordeste e a Amazônia.",
           "A capital do Maranhão é São Luís.",
           "O Maranhão tem cerca de 6,8 milhões de habitantes e área de cerca de 330 mil km², o segundo maior estado do Nordeste.",
           "O Maranhão abriga os Lençóis Maranhenses, parque de dunas brancas com lagoas de água doce, e o Centro de Lançamento de Alcântara.",
           "A cidade de São Luís, capital do Maranhão, foi fundada por franceses em 1612 e tem centro histórico com casarões de azulejos, Patrimônio Mundial; o bumba meu boi é a festa típica do estado.",
           aliases=["estado do Maranhão"]),
    estado("mundo_estado_piaui", "Piauí",
           "O Piauí é um estado brasileiro que fica na região Nordeste, de sigla PI.",
           "A capital do Piauí é Teresina.",
           "O Piauí tem cerca de 3,3 milhões de habitantes e área de cerca de 251 mil km², com o menor litoral entre os estados costeiros brasileiros, de cerca de 66 km.",
           "O Piauí abriga o Parque Nacional da Serra da Capivara, com milhares de pinturas rupestres, Patrimônio Mundial, e o delta do rio Parnaíba.",
           "A cidade de Teresina, capital do Piauí, é a única capital do Nordeste que não fica no litoral.",
           aliases=["estado do Piauí"]),
    estado("mundo_estado_ceara", "Ceará",
           "O Ceará é um estado brasileiro que fica na região Nordeste, de sigla CE.",
           "A capital do Ceará é Fortaleza.",
           "O Ceará tem cerca de 8,8 milhões de habitantes, o terceiro estado mais populoso do Nordeste, e área de cerca de 149 mil km².",
           "O Ceará é conhecido pelas praias, como Jericoacoara e Canoa Quebrada, e grande parte do seu território tem clima semiárido.",
           "O Ceará aboliu a escravidão em 1884, quatro anos antes da Lei Áurea; o humor cearense e o artesanato de renda são traços culturais conhecidos.",
           aliases=["estado do Ceará"]),
    estado("mundo_estado_rio_grande_do_norte", "Rio Grande do Norte",
           "O Rio Grande do Norte é um estado brasileiro que fica na região Nordeste, de sigla RN, na esquina nordeste do continente sul-americano.",
           "A capital do Rio Grande do Norte é Natal.",
           "O Rio Grande do Norte tem cerca de 3,3 milhões de habitantes e área de cerca de 53 mil km².",
           "O Rio Grande do Norte é grande produtor de sal marinho, petróleo em terra e energia eólica, e é conhecido pelas dunas de Genipabu.",
           "A cidade de Natal, capital do Rio Grande do Norte, abrigou uma base aérea dos Estados Unidos na Segunda Guerra Mundial; o Forte dos Reis Magos é seu marco histórico.",
           aliases=["estado do Rio Grande do Norte"]),
    estado("mundo_estado_paraiba", "Paraíba",
           "A Paraíba é um estado brasileiro que fica na região Nordeste, de sigla PB.",
           "A capital da Paraíba é João Pessoa.",
           "A Paraíba tem cerca de 4 milhões de habitantes e área de cerca de 56 mil km².",
           "Na Paraíba fica a Ponta do Seixas, ponto mais oriental das Américas, em João Pessoa.",
           "A cidade de Campina Grande, na Paraíba, realiza uma das maiores festas de São João do Brasil; o escritor Ariano Suassuna era paraibano.",
           aliases=["estado da Paraíba"]),
    estado("mundo_estado_pernambuco", "estado de Pernambuco",
           "Pernambuco é um estado brasileiro que fica na região Nordeste, de sigla PE.",
           "A capital de Pernambuco é Recife.",
           "Pernambuco tem cerca de 9,1 milhões de habitantes, o segundo estado mais populoso do Nordeste, e área de cerca de 98 mil km², incluindo o arquipélago de Fernando de Noronha.",
           "A economia de Pernambuco inclui o Porto de Suape, o polo de tecnologia Porto Digital, no Recife, e a fruticultura irrigada no vale do São Francisco.",
           "Pernambuco é berço do frevo e do maracatu, e o Carnaval de Recife e Olinda é um dos mais famosos do país; no século XVII, a região foi ocupada pelos holandeses.",
           aliases=["Pernambuco"]),
    estado("mundo_estado_alagoas", "estado de Alagoas",
           "Alagoas é um estado brasileiro que fica na região Nordeste, de sigla AL.",
           "A capital de Alagoas é Maceió.",
           "Alagoas tem cerca de 3,1 milhões de habitantes e área de cerca de 28 mil km², um dos menores estados do Brasil.",
           "A economia de Alagoas tem forte peso da cana-de-açúcar e do turismo, com praias de águas claras e piscinas naturais.",
           "Em Alagoas ficava o Quilombo dos Palmares, na Serra da Barriga, liderado por Zumbi no século XVII; Alagoas também é terra natal de Deodoro da Fonseca, primeiro presidente do Brasil.",
           aliases=["Alagoas"]),
    estado("mundo_estado_sergipe", "estado de Sergipe",
           "Sergipe é um estado brasileiro que fica na região Nordeste, de sigla SE, e o menor estado brasileiro em área.",
           "A capital de Sergipe é Aracaju.",
           "Sergipe tem cerca de 22 mil km² e cerca de 2,2 milhões de habitantes.",
           "A economia de Sergipe inclui petróleo e gás, agricultura e o rio São Francisco, que marca sua divisa com Alagoas.",
           "A cidade de Aracaju, capital de Sergipe, foi uma das primeiras capitais planejadas do Brasil, fundada em 1855.",
           aliases=["Sergipe"]),
    estado("mundo_estado_bahia", "Bahia",
           "A Bahia é um estado brasileiro que fica na região Nordeste, de sigla BA, o maior e mais populoso do Nordeste.",
           "A capital da Bahia é Salvador.",
           "A Bahia tem cerca de 14,1 milhões de habitantes, o quarto estado mais populoso do Brasil, e área de cerca de 565 mil km².",
           "A economia da Bahia inclui o polo petroquímico de Camaçari, a agricultura do oeste baiano e o turismo, com a Chapada Diamantina e o litoral.",
           "Salvador, capital da Bahia, foi a primeira capital do Brasil, de 1549 a 1763; a Bahia tem forte herança africana, presente no candomblé, na capoeira e no acarajé.",
           aliases=["estado da Bahia"]),

    # Região Centro-Oeste
    estado("mundo_estado_goias", "estado de Goiás",
           "Goiás é um estado brasileiro que fica na região Centro-Oeste, de sigla GO, que envolve quase todo o Distrito Federal.",
           "A capital de Goiás é Goiânia.",
           "Goiás tem cerca de 7,1 milhões de habitantes, o estado mais populoso do Centro-Oeste, e área de cerca de 340 mil km².",
           "A economia de Goiás é baseada no agronegócio, com soja, milho, cana e gado, e o estado abriga a Chapada dos Veadeiros, no Cerrado.",
           "Goiás surgiu com a mineração de ouro no século XVIII; a cidade de Goiás, antiga capital, é Patrimônio Mundial, e Goiânia foi planejada na década de 1930.",
           aliases=["Goiás"]),
    estado("mundo_estado_mato_grosso", "Mato Grosso",
           "Mato Grosso é um estado brasileiro que fica na região Centro-Oeste, de sigla MT, o terceiro maior estado brasileiro em área.",
           "A capital de Mato Grosso é Cuiabá.",
           "Mato Grosso tem cerca de 903 mil km² e cerca de 3,7 milhões de habitantes.",
           "Mato Grosso é o maior produtor de soja do Brasil e reúne três biomas: Amazônia, Cerrado e Pantanal.",
           "Em Mato Grosso fica o Parque Indígena do Xingu, criado em 1961 com apoio dos irmãos Villas-Bôas.",
           aliases=["estado de Mato Grosso"]),
    estado("mundo_estado_mato_grosso_do_sul", "Mato Grosso do Sul",
           "Mato Grosso do Sul é um estado brasileiro que fica na região Centro-Oeste, de sigla MS, criado em 1977 pela divisão de Mato Grosso.",
           "A capital de Mato Grosso do Sul é Campo Grande.",
           "Mato Grosso do Sul tem cerca de 2,8 milhões de habitantes e área de cerca de 357 mil km², na fronteira com o Paraguai e a Bolívia.",
           "Mato Grosso do Sul abriga grande parte do Pantanal e o ecoturismo de Bonito, famoso por rios de águas cristalinas; a pecuária e a soja dominam a economia.",
           "Mato Grosso do Sul tem forte influência paraguaia, presente no tereré e na música, e uma das maiores populações indígenas do país, como os Guarani-Kaiowá e os Terena.",
           aliases=["estado de Mato Grosso do Sul"]),
    estado("mundo_distrito_federal", "Distrito Federal",
           "O Distrito Federal é a unidade da federação onde fica a capital do Brasil, de sigla DF, na região Centro-Oeste, e não é dividido em municípios.",
           "A capital do Distrito Federal é Brasília, que também é a capital do Brasil.",
           "O Distrito Federal tem cerca de 2,8 milhões de habitantes em cerca de 5,8 mil km², a menor unidade da federação em área.",
           "A economia do Distrito Federal é dominada pela administração pública e pelos serviços, e tem a maior renda por pessoa do país.",
           "A cidade de Brasília, no Distrito Federal, foi inaugurada em 21 de abril de 1960 pelo presidente Juscelino Kubitschek, com projeto urbanístico de Lucio Costa e arquitetura de Oscar Niemeyer.",
           aliases=["DF"]),

    # Região Sudeste
    estado("mundo_estado_sao_paulo", "estado de São Paulo",
           "O estado de São Paulo é um estado brasileiro que fica na região Sudeste, de sigla SP, e o mais populoso do país.",
           "A capital do estado de São Paulo é a cidade de São Paulo.",
           "O estado de São Paulo tem cerca de 44 milhões de habitantes, mais de um quinto da população brasileira, e área de cerca de 248 mil km².",
           "O estado de São Paulo tem a maior economia do Brasil, cerca de um terço do PIB, com indústria, serviços, finanças, o Porto de Santos e grande produção de cana e laranja.",
           "O estado de São Paulo cresceu com o café no século XIX e recebeu imigrantes italianos, japoneses e de muitas outras origens; a Revolução Constitucionalista de 1932 é marco de sua história.",
           aliases=["SP", "São Paulo"]),
    estado("mundo_estado_rio_de_janeiro", "estado do Rio de Janeiro",
           "O estado do Rio de Janeiro é um estado brasileiro que fica na região Sudeste, de sigla RJ.",
           "A capital do estado do Rio de Janeiro é a cidade do Rio de Janeiro.",
           "O estado do Rio de Janeiro tem cerca de 16 milhões de habitantes, o terceiro mais populoso do Brasil, e área de cerca de 44 mil km².",
           "O estado do Rio de Janeiro é o maior produtor de petróleo do Brasil, extraído sobretudo no mar, nas bacias de Campos e de Santos.",
           "A cidade do Rio de Janeiro, capital do estado do Rio de Janeiro, foi capital do Brasil de 1763 a 1960 e é famosa pelo Cristo Redentor, pelo Pão de Açúcar e pelo Carnaval.",
           aliases=["RJ", "Rio de Janeiro"]),
    estado("mundo_estado_minas_gerais", "estado de Minas Gerais",
           "Minas Gerais é um estado brasileiro que fica na região Sudeste, de sigla MG, sem litoral.",
           "A capital de Minas Gerais é Belo Horizonte.",
           "Minas Gerais tem cerca de 20,5 milhões de habitantes, o segundo estado mais populoso do Brasil, e área de cerca de 586 mil km², a quarta maior.",
           "A economia de Minas Gerais se destaca na mineração de ferro, na siderurgia, na produção de café e de leite, e o estado tem o maior número de municípios do país, 853.",
           "Minas Gerais viveu o ciclo do ouro no século XVIII, que deixou cidades barrocas como Ouro Preto, e foi palco da Inconfidência Mineira, de Tiradentes, em 1789.",
           aliases=["MG", "Minas Gerais"]),
    estado("mundo_estado_espirito_santo", "estado do Espírito Santo",
           "O estado do Espírito Santo é um estado brasileiro que fica na região Sudeste, de sigla ES, no litoral entre a Bahia e o Rio de Janeiro.",
           "A capital do estado do Espírito Santo é Vitória.",
           "O estado do Espírito Santo tem cerca de 3,8 milhões de habitantes e área de cerca de 46 mil km².",
           "A economia do estado do Espírito Santo inclui portos exportadores de minério de ferro, petróleo, rochas ornamentais como granito e mármore, e café, sobretudo o conilon.",
           "A cidade de Vitória, capital do estado do Espírito Santo, fica numa ilha; a moqueca capixaba, feita em panela de barro, é símbolo da culinária do estado.",aliases=["Espírito Santo"]),

    # Região Sul
    estado("mundo_estado_parana", "Paraná",
           "O Paraná é um estado brasileiro que fica na região Sul, de sigla PR.",
           "A capital do Paraná é Curitiba.",
           "O Paraná tem cerca de 11,4 milhões de habitantes, o estado mais populoso do Sul, e área de cerca de 199 mil km².",
           "O Paraná abriga as Cataratas do Iguaçu, na fronteira com a Argentina, e a usina de Itaipu, na fronteira com o Paraguai, e é grande produtor de grãos e de carne de frango.",
           "O Paraná recebeu muitos imigrantes poloneses, ucranianos, alemães, italianos e japoneses; Curitiba é conhecida pelo planejamento urbano e pelo transporte por ônibus.",
           aliases=["estado do Paraná"]),
    estado("mundo_estado_santa_catarina", "estado de Santa Catarina",
           "Santa Catarina é um estado brasileiro que fica na região Sul, de sigla SC.",
           "A capital de Santa Catarina é Florianópolis.",
           "Santa Catarina tem cerca de 7,6 milhões de habitantes e área de cerca de 95 mil km².",
           "A economia de Santa Catarina é diversificada, com indústria têxtil, metalmecânica, carnes de suínos e aves, e turismo de praia e de serra.",
           "Santa Catarina tem forte herança alemã, italiana e açoriana, e Blumenau sedia a Oktoberfest, uma das maiores festas alemãs fora da Alemanha; Florianópolis fica em grande parte numa ilha.",
           aliases=["Santa Catarina"]),
    estado("mundo_estado_rio_grande_do_sul", "Rio Grande do Sul",
           "O Rio Grande do Sul é um estado brasileiro que fica na região Sul, de sigla RS, o mais meridional do país.",
           "A capital do Rio Grande do Sul é Porto Alegre.",
           "O Rio Grande do Sul tem cerca de 10,9 milhões de habitantes e área de cerca de 282 mil km², na fronteira com Uruguai e Argentina.",
           "A economia do Rio Grande do Sul inclui agropecuária, com soja, arroz e gado, indústria e produção de vinho na Serra Gaúcha; no sul do estado predomina o Pampa.",
           "O Rio Grande do Sul tem a cultura gaúcha do chimarrão e do churrasco e foi palco da Revolução Farroupilha, de 1835 a 1845; em 2024 sofreu enchentes históricas.",
           aliases=["RS", "estado do Rio Grande do Sul"]),
]

if __name__ == "__main__":
    import sys
    salvar(sys.argv[1], "Sínteses próprias sobre as cinco regiões, os 26 estados e o Distrito Federal do Brasil, com dados "
           "aproximados do Censo 2022 e do panorama do IBGE Cidades e Estados (referência). Números são arredondados.",
           FONTES, ITENS)
