from comum import conceito, fonte_existente, dominio_publico, openstax, referencia, salvar

NOAA = "noaa_ocean_facts"
NASA = "nasa_earth_observatory_biomas"
IBGE = "ibge_portal"
BIO = "openstax_biologia_2e"
FONTES = [
    dominio_publico(NOAA, "NOAA Ocean Service — Ocean Facts", "https://oceanservice.noaa.gov/facts/",
                    "National Oceanic and Atmospheric Administration (NOAA), EUA", "https://www.noaa.gov/disclaimer"),
    dominio_publico(NASA, "NASA Earth Observatory — Mission: Biomes", "https://earthobservatory.nasa.gov/biome",
                    "NASA Earth Observatory", "https://earthobservatory.nasa.gov/image-use-policy"),
    referencia(IBGE, "Instituto Brasileiro de Geografia e Estatística (IBGE)", "https://www.ibge.gov.br/",
               "IBGE", "https://www.ibge.gov.br/"),
    fonte_existente(BIO),
]
C = "cientifico"
S = "social"
A = "geografia"

ITENS = [
    conceito("mundo_geografia", "geografia", A, IBGE, S,
             "Geografia é a ciência que estuda o espaço terrestre, as paisagens e as relações entre sociedade e natureza.",
             "Costuma ser dividida em geografia física, que trata de relevo, clima, solos e água, e geografia humana, que trata de população, cidades e economia."),
    conceito("mundo_continente", "continente", A, NOAA, C,
             "Continente é cada uma das grandes massas de terra emersa do planeta.",
             "Uma divisão comum reconhece sete: África, Antártida, Ásia, Europa, América do Norte, América do Sul e Oceania; no Brasil também se ensina a América como um continente único.",
             "Os limites entre continentes são convenções; Europa e Ásia, por exemplo, formam uma só massa de terra, a Eurásia.",
             papeis={1: "limite"}),
    conceito("mundo_oceano", "oceano", A, NOAA, C,
             "Oceano é a grande massa de água salgada que cobre cerca de 71% da superfície da Terra.",
             "Costuma-se distinguir cinco oceanos: Pacífico, Atlântico, Índico, Antártico (ou Austral) e Ártico, embora todos estejam interligados.",
             "O Pacífico é o maior e o mais profundo; a Fossa das Marianas, nele, ultrapassa 10.900 metros de profundidade.",
             "Os oceanos absorvem grande parte do calor e do dióxido de carbono em excesso na atmosfera.",
             aliases=["oceanos", "mar aberto"]),
    conceito("mundo_placas_tectonicas", "placas tectônicas", A, NOAA, C,
             "Placas tectônicas são os grandes blocos rígidos em que se divide a litosfera, a camada externa da Terra.",
             "Elas se movem alguns centímetros por ano sobre o manto, que flui lentamente.",
             "Nos limites entre placas ocorrem terremotos, vulcões, cordilheiras e fossas oceânicas.",
             "A teoria explica por que os continentes já estiveram unidos num supercontinente, a Pangeia, há cerca de 300 milhões de anos.",
             aliases=["tectônica de placas", "deriva continental"]),
    conceito("mundo_terremoto", "terremoto", A, NOAA, C,
             "Terremoto é um tremor da crosta terrestre causado pela liberação súbita de energia acumulada em falhas geológicas.",
             "A maioria ocorre nos limites entre placas tectônicas, como no chamado Círculo de Fogo do Pacífico.",
             "Terremotos no fundo do mar podem gerar tsunamis, ondas que atravessam oceanos.",
             aliases=["sismo", "abalo sísmico"], papeis={0: "causa"}),
    conceito("mundo_vulcao", "vulcão", A, NOAA, C,
             "Vulcão é uma abertura na crosta por onde magma, gases e cinzas chegam à superfície.",
             "Forma-se principalmente em limites de placas e em pontos quentes, como o que originou o Havaí.",
             "Erupções podem fertilizar solos a longo prazo, mas também causam destruição e alterações temporárias no clima.",
             aliases=["vulcões"]),
    conceito("mundo_relevo", "relevo", A, IBGE, C,
             "Relevo é o conjunto de formas da superfície terrestre, como montanhas, planaltos, planícies e depressões.",
             "É moldado por forças internas, como a tectônica, e externas, como chuva, vento, rios e geleiras.",
             "O relevo brasileiro é dominado por planaltos e planícies antigos e desgastados; não há cordilheiras jovens no território.",
             aliases=["formas de relevo"]),
    conceito("mundo_bioma", "bioma", A, NASA, C,
             "Bioma é uma grande comunidade de seres vivos adaptada a um tipo de clima e vegetação predominante.",
             "Exemplos globais são florestas tropicais, savanas, desertos, tundra, taiga e campos temperados.",
             "Temperatura e quantidade de chuva são os principais fatores que definem onde cada bioma ocorre.",
             aliases=["biomas"], papeis={1: "causa"}),
    conceito("mundo_floresta_tropical", "floresta tropical", A, NASA, C,
             "Floresta tropical é o bioma de clima quente e chuvoso o ano todo, perto da linha do Equador.",
             "Abriga mais da metade das espécies terrestres conhecidas, embora ocupe uma pequena fração da superfície.",
             "O solo costuma ser pobre: a maior parte dos nutrientes está na própria vegetação e é reciclada rapidamente.",
             aliases=["floresta equatorial"]),
    conceito("mundo_deserto", "deserto", A, NASA, C,
             "Deserto é uma região que recebe muito pouca chuva, em geral menos de 250 milímetros por ano.",
             "Nem todo deserto é quente: a Antártida é o maior deserto do mundo, por causa da baixíssima precipitação.",
             "O Saara é o maior deserto quente, no norte da África.",
             aliases=["desertos"]),
    conceito("mundo_amazonia", "Amazônia", A, IBGE, C,
             "Amazônia é o bioma de floresta tropical que ocupa a bacia do rio Amazonas, a maior floresta tropical do mundo.",
             "Ocupa cerca de metade do território brasileiro e se estende por mais oito países da América do Sul.",
             "O rio Amazonas tem a maior vazão do planeta e despeja no Atlântico cerca de um quinto de toda a água doce que chega aos oceanos.",
             "O desmatamento ameaça sua biodiversidade, os povos que nela vivem e seu papel na regulação do clima e das chuvas.",
             aliases=["floresta amazônica", "Amazônia brasileira"]),
    conceito("mundo_cerrado", "Cerrado", A, IBGE, C,
             "Cerrado é a savana tropical do Brasil central, o segundo maior bioma do país.",
             "Tem árvores baixas e retorcidas, cascas grossas e raízes profundas, adaptadas à estação seca e ao fogo natural.",
             "Abriga nascentes de grandes bacias hidrográficas, por isso é chamado de berço das águas.",
             "É um dos biomas mais ameaçados pela expansão agropecuária.",
             aliases=["savana brasileira"]),
    conceito("mundo_mata_atlantica", "Mata Atlântica", A, IBGE, C,
             "Mata Atlântica é o bioma de florestas que se estende ao longo da costa brasileira.",
             "É onde vive a maior parte da população do Brasil, e restam cerca de 12% de sua cobertura original.",
             "Mesmo reduzida, tem altíssima biodiversidade e muitas espécies que só existem nela."),
    conceito("mundo_caatinga", "Caatinga", A, IBGE, C,
             "Caatinga é o bioma do semiárido nordestino, o único exclusivamente brasileiro.",
             "Sua vegetação perde as folhas na estação seca e rebrota rapidamente com as chuvas.",
             "O nome vem do tupi e costuma ser traduzido como 'mata branca', pela aparência da vegetação seca."),
    conceito("mundo_pantanal", "Pantanal", A, IBGE, C,
             "Pantanal é a maior planície alagável contínua do planeta, no centro-oeste do Brasil, com partes na Bolívia e no Paraguai.",
             "Na estação chuvosa, grandes áreas ficam inundadas; na seca, as águas recuam e formam lagoas.",
             "É famoso pela facilidade de observar fauna, como onças-pintadas, jacarés, capivaras e tuiuiús."),
    conceito("mundo_pampa", "Pampa", A, IBGE, C,
             "Pampa é o bioma de campos do sul do Rio Grande do Sul, que continua no Uruguai e na Argentina.",
             "Predominam gramíneas e vegetação rasteira, em relevo de coxilhas suaves.",
             "A pecuária extensiva marca a história e a cultura da região.",
             aliases=["campos sulinos"]),
    conceito("mundo_brasil", "Brasil", A, IBGE, S,
             "Brasil é o maior país da América do Sul, com cerca de 8,5 milhões de quilômetros quadrados.",
             "Segundo o Censo de 2022 do IBGE, tinha cerca de 203 milhões de habitantes.",
             "É uma república federativa com 26 estados e o Distrito Federal, onde fica a capital, Brasília.",
             "O IBGE divide o país em cinco regiões: Norte, Nordeste, Centro-Oeste, Sudeste e Sul.",
             aliases=["República Federativa do Brasil"]),
    conceito("mundo_regioes_brasil", "regiões do Brasil", A, IBGE, S,
             "As regiões do Brasil são as cinco grandes divisões do território definidas pelo IBGE: Norte, Nordeste, Centro-Oeste, Sudeste e Sul.",
             "O Norte é a maior em área e concentra a Amazônia; o Sudeste é a mais populosa.",
             "O Nordeste tem nove estados, o maior número entre as regiões.",
             aliases=["regiões brasileiras", "cinco regiões"]),
    conceito("mundo_bacia_hidrografica", "bacia hidrográfica", A, IBGE, C,
             "Bacia hidrográfica é a área cujas águas da chuva escoam para um mesmo rio principal e seus afluentes.",
             "As bacias são separadas por divisores de água, geralmente terrenos mais altos.",
             "No Brasil, as maiores são a Amazônica, a do Tocantins-Araguaia, a do Paraná e a do São Francisco.",
             aliases=["bacias hidrográficas"]),
    # “clima” fica com a resposta editorial antiga (diferença entre clima e
    # tempo); esta ficha trata da classificação dos climas.
    conceito("mundo_tipos_de_clima", "tipos de clima", A, NASA, C,
             "Tipos de clima são categorias que agrupam regiões com padrões semelhantes de temperatura e chuva ao longo de muitos anos, em geral três décadas ou mais.",
             "Dependem de latitude, altitude, distância do mar, correntes oceânicas e massas de ar.",
             "A classificação de Köppen é uma das mais usadas e distingue grandes grupos, como tropical, árido, temperado, continental e polar.",
             aliases=["classificação climática", "classificação de Köppen"]),
    conceito("mundo_latitude_longitude", "latitude e longitude", A, NOAA, C,
             "Latitude e longitude são as coordenadas que localizam qualquer ponto da superfície da Terra.",
             "A latitude mede a distância angular ao norte ou ao sul da linha do Equador, de 0° a 90°.",
             "A longitude mede a distância angular a leste ou a oeste do meridiano de Greenwich, de 0° a 180°.",
             aliases=["coordenadas geográficas", "latitude", "longitude"]),
    conceito("mundo_populacao_mundial", "população mundial", A, IBGE, S,
             "População mundial é o número total de pessoas vivendo no planeta, que ultrapassou 8 bilhões em 2022, segundo a ONU.",
             "Índia e China são os países mais populosos, cada um com mais de 1,4 bilhão de habitantes.",
             "O crescimento desacelerou nas últimas décadas, com a queda das taxas de fecundidade em grande parte do mundo.",
             aliases=["população do mundo"]),
    conceito("mundo_rio_nilo", "rio Nilo", A, NOAA, C,
             "Nilo é um rio do nordeste da África, com cerca de 6.650 km, frequentemente citado como o mais longo do mundo.",
             "Algumas medições apontam o Amazonas como mais longo; a diferença depende de onde se define a nascente.",
             "Seus dois principais formadores são o Nilo Branco e o Nilo Azul, que se encontram em Cartum, no Sudão.",
             aliases=["Nilo"], papeis={0: "limite"}),
    conceito("mundo_monte_everest", "monte Everest", A, NOAA, C,
             "Everest é a montanha mais alta do mundo acima do nível do mar, com cerca de 8.849 metros.",
             "Fica na cordilheira do Himalaia, na fronteira entre Nepal e China (Tibete).",
             "O Himalaia continua a se elevar por causa da colisão entre as placas Indiana e Euroasiática.",
             aliases=["Everest"]),
    conceito("mundo_urbanizacao_brasil", "urbanização no Brasil", A, IBGE, S,
             "A urbanização no Brasil foi a rápida transferência da população do campo para as cidades, sobretudo a partir de 1950.",
             "Em 1950, a maioria vivia no campo; hoje, mais de 80% dos brasileiros vivem em áreas urbanas.",
             "O crescimento rápido, sem planejamento suficiente, ampliou moradias precárias e desigualdades nas metrópoles.",
             aliases=["êxodo rural"]),
]

COMPARACOES = [
    {"origem": "mundo_cerrado", "destino": "mundo_caatinga", "indice_fato": 0},
    {"origem": "mundo_amazonia", "destino": "mundo_mata_atlantica", "indice_fato": 0},
]

if __name__ == "__main__":
    import sys
    salvar(sys.argv[1], "Sínteses próprias de geografia física e humana, com fatos de agências científicas públicas "
           "(NOAA, NASA), do IBGE e de manuais abertos. Números são valores de referência arredondados e mudam com "
           "novas medições e censos.", FONTES, ITENS, (), COMPARACOES)
