"""Catálogo complementar de história e personagens históricos (06/10/2026).

Completa lacunas dos catálogos ``historia`` e ``pessoas`` sem repetir fichas.
Uso: ``cd scripts/catalogos && python historia_complementar.py ../../conhecimento_historia_complementar.json``.
"""
from comum import conceito, dominio_publico, openstax, referencia, salvar

H1 = "hc_openstax_historia_mundial_v1"
H2 = "hc_openstax_historia_mundial_v2"
US = "hc_openstax_historia_eua"
AN = "hc_arquivo_nacional"
NASA = "hc_nasa_apollo"
BC = "hc_banco_central"
CAM = "hc_camara_deputados"
FONTES = [
    openstax(H1, "World History Volume 1: to 1500", "world-history-volume-1",
             "OpenStax, Rice University; Ann Kordas, Ryan J. Lynch, Brooke Nelson, Julie Tatlock"),
    openstax(H2, "World History Volume 2: from 1400", "world-history-volume-2",
             "OpenStax, Rice University; Ann Kordas, Ryan J. Lynch, Brooke Nelson, Julie Tatlock"),
    openstax(US, "U.S. History", "us-history",
             "OpenStax, Rice University; P. Scott Corbett, Volker Janssen, John M. Lund, Todd Pfannestiel, Sylvie Waskiewicz, Paul Vickery"),
    referencia(AN, "Arquivo Nacional — acervo e história do Brasil", "https://www.gov.br/arquivonacional/pt-br",
               "Arquivo Nacional (Brasil)", "https://www.gov.br/pt-br/termos-de-uso"),
    dominio_publico(NASA, "NASA — Apollo 11 mission overview", "https://www.nasa.gov/mission/apollo-11/",
                    "National Aeronautics and Space Administration (NASA)",
                    "https://www.nasa.gov/nasa-brand-center/images-and-media/"),
    referencia(BC, "Banco Central do Brasil — Plano Real e história do real", "https://www.bcb.gov.br/",
               "Banco Central do Brasil", "https://www.gov.br/pt-br/termos-de-uso"),
    referencia(CAM, "Câmara dos Deputados — história e memória do Legislativo", "https://www.camara.leg.br/",
               "Câmara dos Deputados (Brasil)", "https://www.gov.br/pt-br/termos-de-uso"),
]
S = "social"
HI = "historia"
PE = "pessoas"


def fato(ident, nome, fonte, definicao, *detalhes, aliases=()):
    return conceito(ident, nome, HI, fonte, S, definicao, *detalhes, aliases=aliases)


def pessoa(ident, nome, fonte, definicao, *detalhes, aliases=()):
    return conceito(ident, nome, PE, fonte, S, definicao, *detalhes, aliases=aliases)


ITENS = [
    # ---------------- Brasil ----------------
    fato("mundo_chegada_portugueses_brasil", "chegada dos portugueses ao Brasil", AN,
         "A chegada dos portugueses ao Brasil, tradicionalmente chamada de descobrimento do Brasil, ocorreu em 22 de abril de 1500, quando a esquadra de Pedro Álvares Cabral avistou o litoral da atual Bahia.",
         "A esquadra de Pedro Álvares Cabral que chegou ao Brasil tinha 13 embarcações e cerca de 1.500 homens e seguia para as Índias quando se afastou para oeste no Atlântico.",
         "Na chegada dos portugueses ao Brasil, o primeiro ponto avistado foi um monte batizado de Monte Pascoal; a frota ancorou depois na região de Porto Seguro, onde foi rezada a primeira missa, em 26 de abril de 1500.",
         "A Carta de Pero Vaz de Caminha, escrita em 1º de maio de 1500 ao rei D. Manuel I, é o primeiro relato escrito sobre a terra que viria a ser o Brasil.",
         "Os portugueses chamaram a nova terra de Ilha de Vera Cruz e depois de Terra de Santa Cruz; o nome Brasil veio do pau-brasil, madeira explorada nas primeiras décadas.",
         "O termo descobrimento do Brasil é criticado porque o território já era habitado por milhões de indígenas; por isso muitos historiadores preferem falar em chegada ou conquista portuguesa.",
         aliases=["descobrimento do Brasil", "descoberta do Brasil", "achamento do Brasil", "chegada de Cabral ao Brasil"]),
    pessoa("mundo_pedro_alvares_cabral", "Pedro Álvares Cabral", AN,
           "Pedro Álvares Cabral (c. 1467–c. 1520) foi um navegador e comandante português que chefiou a esquadra que chegou ao Brasil em 22 de abril de 1500.",
           "Pedro Álvares Cabral nasceu em Belmonte, em Portugal, numa família da pequena nobreza, e foi escolhido pelo rei D. Manuel I para comandar a segunda grande viagem portuguesa às Índias.",
           "Depois de passar pelo Brasil, a frota de Pedro Álvares Cabral seguiu para Calicute, na Índia; no caminho perdeu vários navios numa tempestade, entre eles o comandado por Bartolomeu Dias.",
           "Pedro Álvares Cabral morreu por volta de 1520 em Santarém, Portugal, onde está sepultado.",
           aliases=["Cabral", "Pedro Alvares Cabral"]),
    pessoa("mundo_dom_pedro_i", "D. Pedro I", AN,
           "D. Pedro I (1798–1834) foi o príncipe português que proclamou a independência do Brasil, em 7 de setembro de 1822, e se tornou o primeiro imperador do país.",
           "D. Pedro I nasceu em Queluz, Portugal, e veio para o Brasil em 1808 com a corte portuguesa; em 1821 ficou como príncipe regente quando seu pai, D. João VI, voltou a Portugal.",
           "Em 9 de janeiro de 1822, no Dia do Fico, D. Pedro I recusou-se a voltar a Portugal; em 7 de setembro de 1822, às margens do riacho Ipiranga, em São Paulo, declarou a independência.",
           "D. Pedro I foi coroado imperador em 1º de dezembro de 1822 e outorgou a Constituição de 1824, que criou o Poder Moderador.",
           "D. Pedro I abdicou do trono brasileiro em 7 de abril de 1831 em favor do filho, o futuro D. Pedro II, então com 5 anos; em Portugal, foi rei como D. Pedro IV e morreu em 1834.",
           aliases=["Pedro I", "Dom Pedro I"]),
    fato("mundo_inconfidencia_mineira", "Inconfidência Mineira", AN,
         "Inconfidência Mineira foi um movimento de 1789, na capitania de Minas Gerais, que planejava separar a região do domínio de Portugal e criar uma república.",
         "A Inconfidência Mineira foi motivada pela cobrança de impostos sobre o ouro e pela ameaça da derrama, cobrança forçada dos tributos atrasados, em Vila Rica, atual Ouro Preto.",
         "Participaram da Inconfidência Mineira Tiradentes, os poetas Cláudio Manuel da Costa, Tomás Antônio Gonzaga e Alvarenga Peixoto, além de padres, militares e proprietários.",
         "A Inconfidência Mineira foi denunciada por Joaquim Silvério dos Reis em 1789, antes de começar; os envolvidos foram presos e vários foram condenados ao exílio na África.",
         "Tiradentes, único inconfidente executado, foi enforcado no Rio de Janeiro em 21 de abril de 1792; a data é feriado nacional no Brasil.",
         "A Inconfidência Mineira foi inspirada pelo Iluminismo e pela independência dos Estados Unidos; seu lema, Libertas quae sera tamen, está na bandeira de Minas Gerais.",
         aliases=["Conjuração Mineira"]),
    fato("mundo_revolucao_farroupilha", "Revolução Farroupilha", AN,
         "Revolução Farroupilha foi uma revolta no Rio Grande do Sul contra o governo imperial brasileiro, que durou de 1835 a 1845, sendo a mais longa do período regencial e do Império.",
         "A Revolução Farroupilha teve entre suas causas os altos impostos sobre o charque gaúcho e a insatisfação dos estancieiros com a centralização do poder no Rio de Janeiro.",
         "Durante a Revolução Farroupilha, os rebeldes proclamaram a República Rio-Grandense em 1836; entre os líderes estavam Bento Gonçalves e o italiano Giuseppe Garibaldi.",
         "A Revolução Farroupilha terminou com a Paz de Ponche Verde, em 1º de março de 1845; o início do movimento, 20 de setembro, é data comemorada no Rio Grande do Sul.",
         aliases=["Guerra dos Farrapos", "Farroupilha"]),
    fato("mundo_guerra_do_paraguai", "Guerra do Paraguai", AN,
         "Guerra do Paraguai foi o conflito de 1864 a 1870 entre o Paraguai, governado por Francisco Solano López, e a Tríplice Aliança formada por Brasil, Argentina e Uruguai.",
         "A Guerra do Paraguai começou depois que o Paraguai apreendeu o navio brasileiro Marquês de Olinda e invadiu o Mato Grosso, em 1864, e depois a província argentina de Corrientes.",
         "Na Guerra do Paraguai, a Batalha Naval do Riachuelo, em 11 de junho de 1865, deu aos aliados o controle dos rios; Duque de Caxias comandou as forças brasileiras em parte do conflito.",
         "A Guerra do Paraguai terminou em 1º de março de 1870, com a morte de Solano López em Cerro Corá.",
         "A Guerra do Paraguai devastou o país derrotado, que perdeu grande parte da população e territórios; no Brasil, fortaleceu o Exército e aumentou a dívida do Império.",
         aliases=["Guerra da Tríplice Aliança"]),
    fato("mundo_guerra_de_canudos", "Guerra de Canudos", AN,
         "Guerra de Canudos foi o conflito de 1896 a 1897, no sertão da Bahia, entre o Exército da República e o arraial de Belo Monte, liderado pelo pregador Antônio Conselheiro.",
         "O arraial de Canudos chegou a reunir cerca de 20 a 25 mil moradores, em sua maioria sertanejos pobres atraídos pela liderança religiosa de Antônio Conselheiro.",
         "Na Guerra de Canudos, o governo enviou quatro expedições militares; as três primeiras foram derrotadas, e a quarta destruiu o arraial em outubro de 1897, com milhares de mortos.",
         "A Guerra de Canudos foi narrada por Euclides da Cunha no livro Os Sertões, publicado em 1902.",
         aliases=["Canudos", "Revolta de Canudos"]),
    pessoa("mundo_getulio_vargas", "Getúlio Vargas", AN,
           "Getúlio Vargas (1882–1954) foi um político gaúcho que governou o Brasil de 1930 a 1945 e de 1951 a 1954, sendo o presidente que mais tempo ficou no poder no país.",
           "Getúlio Vargas nasceu em São Borja, no Rio Grande do Sul, e chegou ao poder com a Revolução de 1930; em 1937 implantou a ditadura do Estado Novo, que durou até 1945.",
           "No governo de Getúlio Vargas foram criados o salário mínimo, em 1940, e a Consolidação das Leis do Trabalho (CLT), em 1943, além da Companhia Siderúrgica Nacional.",
           "Getúlio Vargas voltou à presidência eleito pelo voto direto em 1950 e criou a Petrobras em 1953, com a campanha 'O petróleo é nosso'.",
           "Getúlio Vargas suicidou-se em 24 de agosto de 1954, no Palácio do Catete, no Rio de Janeiro, deixando uma carta-testamento com a frase 'saio da vida para entrar na história'.",
           aliases=["Vargas", "Getúlio", "Getulio Vargas"]),
    pessoa("mundo_juscelino_kubitschek", "Juscelino Kubitschek", AN,
           "Juscelino Kubitschek (1902–1976), conhecido como JK, foi presidente do Brasil de 1956 a 1961 e responsável pela construção de Brasília.",
           "Juscelino Kubitschek nasceu em Diamantina, Minas Gerais, era médico e foi prefeito de Belo Horizonte, onde criou o conjunto da Pampulha com Oscar Niemeyer, e governador de Minas Gerais.",
           "O governo de Juscelino Kubitschek adotou o Plano de Metas, com o lema '50 anos em 5', e incentivou a indústria automobilística, a energia e as rodovias.",
           "Juscelino Kubitschek teve os direitos políticos cassados pelo regime militar em 1964 e morreu num acidente de carro na Via Dutra em 22 de agosto de 1976.",
           aliases=["JK", "Juscelino", "Kubitschek"]),
    fato("mundo_construcao_brasilia", "construção de Brasília", AN,
         "A construção de Brasília foi a criação de uma nova capital no Planalto Central, entre 1956 e 1960, no governo de Juscelino Kubitschek; a cidade foi inaugurada em 21 de abril de 1960.",
         "Na construção de Brasília, o plano urbanístico, chamado Plano Piloto, foi feito por Lúcio Costa, e os principais edifícios foram projetados por Oscar Niemeyer.",
         "A ideia de levar a capital para o interior já constava da Constituição de 1891; com a construção de Brasília, a capital do Brasil deixou de ser o Rio de Janeiro.",
         "Os trabalhadores que vieram de várias regiões do país para a construção de Brasília ficaram conhecidos como candangos.",
         "O conjunto urbanístico de Brasília foi declarado Patrimônio Mundial pela UNESCO em 1987.",
         aliases=["inauguração de Brasília", "fundação de Brasília", "mudança da capital para Brasília"]),
    fato("mundo_diretas_ja", "Diretas Já", CAM,
         "Diretas Já foi a campanha popular de 1983 e 1984 que pediu a volta das eleições diretas para presidente da República no Brasil, durante o fim da ditadura militar.",
         "A campanha Diretas Já apoiava a emenda constitucional do deputado Dante de Oliveira e reuniu comícios gigantescos, como o do Vale do Anhangabaú, em São Paulo, em 16 de abril de 1984.",
         "A emenda das Diretas Já foi votada na Câmara em 25 de abril de 1984 e recebeu 298 votos favoráveis, 22 a menos que os dois terços necessários, sendo rejeitada.",
         "Depois das Diretas Já, Tancredo Neves foi eleito pelo Colégio Eleitoral em janeiro de 1985, mas morreu antes da posse; José Sarney assumiu a presidência.",
         "A primeira eleição direta para presidente depois da ditadura ocorreu em 1989.",
         aliases=["Diretas Já!", "campanha das Diretas"]),
    fato("mundo_plano_real", "Plano Real", BC,
         "Plano Real foi o plano econômico de 1994 que acabou com a hiperinflação no Brasil e criou a moeda real, em vigor desde 1º de julho de 1994.",
         "O Plano Real foi lançado no governo de Itamar Franco e elaborado por uma equipe do Ministério da Fazenda, comandado por Fernando Henrique Cardoso até 1994.",
         "Antes da nova moeda, o Plano Real criou em 1º de março de 1994 a URV (Unidade Real de Valor), que serviu como referência para preços e salários.",
         "Na troca de moeda do Plano Real, cada real equivalia a 2.750 cruzeiros reais.",
         "Antes do Plano Real, a inflação no Brasil passou de 2.000% ao ano em 1993; depois dele, caiu para menos de 10% ao ano em poucos anos.",
         aliases=["Plano Real de 1994"]),
    # ---------------- Mundo: Idade Média e Moderna ----------------
    fato("mundo_cruzadas", "Cruzadas", H1,
         "Cruzadas foram expedições militares de cristãos europeus, convocadas pela Igreja Católica entre 1096 e 1291, para conquistar Jerusalém e a Terra Santa.",
         "As Cruzadas foram convocadas pelo papa Urbano II no Concílio de Clermont, em 1095; a Primeira Cruzada tomou Jerusalém em 1099.",
         "Nas Cruzadas, o sultão Saladino retomou Jerusalém em 1187, e a queda de Acre, em 1291, pôs fim aos Estados cruzados no Oriente.",
         "A Quarta Cruzada desviou-se de seu objetivo e saqueou Constantinopla, cidade cristã, em 1204.",
         aliases=["Cruzada"]),
    pessoa("mundo_joana_darc", "Joana d'Arc", H1,
           "Joana d'Arc (c. 1412–1431) foi uma camponesa francesa que liderou tropas da França na Guerra dos Cem Anos contra a Inglaterra e se tornou santa e heroína nacional francesa.",
           "Joana d'Arc nasceu em Domrémy e dizia ouvir vozes de santos que a mandavam libertar a França; em 1429 ajudou a romper o cerco inglês à cidade de Orléans.",
           "As vitórias de Joana d'Arc permitiram a coroação do rei Carlos VII em Reims, em julho de 1429.",
           "Joana d'Arc foi capturada em 1430, entregue aos ingleses, julgada por heresia e queimada viva em Rouen, em 30 de maio de 1431, com cerca de 19 anos.",
           "A condenação de Joana d'Arc foi anulada em 1456, e ela foi canonizada pela Igreja Católica em 1920.",
           aliases=["Joana Darc", "Jeanne d'Arc", "Donzela de Orléans"]),
    fato("mundo_queda_constantinopla", "queda de Constantinopla", H1,
         "A queda de Constantinopla foi a conquista da capital do Império Bizantino pelo Império Otomano, liderado pelo sultão Maomé II, em 29 de maio de 1453.",
         "A queda de Constantinopla pôs fim ao Império Bizantino, herdeiro do Império Romano do Oriente; a cidade tornou-se capital otomana e é a atual Istambul, na Turquia.",
         "A queda de Constantinopla é usada por muitos historiadores como um dos marcos do fim da Idade Média.",
         aliases=["tomada de Constantinopla"]),
    pessoa("mundo_martinho_lutero", "Martinho Lutero", H2,
           "Martinho Lutero (1483–1546) foi um monge e professor de teologia alemão que iniciou a Reforma Protestante.",
           "Em 1517, em Wittenberg, Martinho Lutero divulgou as 95 teses, que criticavam a venda de indulgências pela Igreja Católica.",
           "Martinho Lutero foi excomungado pelo papa em 1521 e, no mesmo ano, recusou-se a renegar suas ideias na Dieta de Worms.",
           "Martinho Lutero traduziu a Bíblia para o alemão e defendia que a salvação vem pela fé e que a Bíblia é a autoridade central do cristão.",
           aliases=["Lutero"]),
    pessoa("mundo_cristovao_colombo", "Cristóvão Colombo", H2,
           "Cristóvão Colombo (1451–1506) foi um navegador genovês que, a serviço dos reis da Espanha, chegou à América em 12 de outubro de 1492.",
           "Cristóvão Colombo partiu de Palos, na Espanha, em 3 de agosto de 1492, com as embarcações Santa María, Pinta e Niña, buscando chegar à Ásia navegando para oeste.",
           "Cristóvão Colombo acreditou até o fim da vida ter chegado às Índias; por isso os habitantes da América foram chamados de índios.",
           "Cristóvão Colombo fez quatro viagens à América entre 1492 e 1504 e morreu em Valladolid, na Espanha, em 1506.",
           aliases=["Colombo", "Cristovão Colombo", "Cristóbal Colón", "Christopher Columbus"]),
    fato("mundo_chegada_america_1492", "chegada de Colombo à América", H2,
         "A chegada de Colombo à América, tradicionalmente chamada de descobrimento da América, ocorreu em 12 de outubro de 1492, quando sua frota alcançou uma ilha das Bahamas, chamada pelos nativos de Guanahani.",
         "Na chegada de Colombo à América, a ilha de Guanahani foi rebatizada de San Salvador; a viagem foi financiada pelos Reis Católicos da Espanha, Fernando e Isabel.",
         "Após a chegada de Colombo à América, Portugal e Espanha dividiram as terras descobertas pelo Tratado de Tordesilhas, em 1494.",
         "O nome América vem do navegador Américo Vespúcio, que defendeu que as terras eram um novo continente, e não a Ásia.",
         "Antes da chegada de Colombo à América, a região já era habitada por milhões de indígenas, e navegadores nórdicos haviam chegado à América do Norte por volta do ano 1000.",
         aliases=["descobrimento da América", "descoberta da América", "viagem de Colombo"]),
    # ---------------- Séculos XVIII e XIX ----------------
    pessoa("mundo_napoleao_bonaparte", "Napoleão Bonaparte", H2,
           "Napoleão Bonaparte (1769–1821) foi um militar e governante francês que tomou o poder em 1799 e foi imperador da França de 1804 a 1814 e em 1815.",
           "Napoleão Bonaparte nasceu em Ajaccio, na Córsega, e chegou ao poder com o golpe de 18 de Brumário, em 1799, tornando-se Primeiro Cônsul.",
           "Napoleão Bonaparte criou o Código Civil francês de 1804, conhecido como Código Napoleônico, que influenciou leis de muitos países.",
           "O Bloqueio Continental decretado por Napoleão Bonaparte em 1806 levou à invasão de Portugal e à vinda da família real portuguesa para o Brasil em 1808.",
           "Napoleão Bonaparte fracassou na invasão da Rússia em 1812, abdicou em 1814, voltou ao poder por cem dias e foi derrotado na Batalha de Waterloo, em 1815.",
           "Napoleão Bonaparte morreu exilado na ilha de Santa Helena, no Atlântico Sul, em 1821.",
           aliases=["Napoleão", "Napoleão I", "Napoleon Bonaparte"]),
    pessoa("mundo_simon_bolivar", "Simón Bolívar", H2,
           "Simón Bolívar (1783–1830) foi um líder militar e político venezuelano que comandou a independência de vários países da América do Sul, sendo chamado de O Libertador.",
           "Simón Bolívar liderou as lutas de independência da Venezuela, Colômbia, Equador, Peru e Bolívia, país que recebeu esse nome em sua homenagem.",
           "Simón Bolívar presidiu a Grã-Colômbia e sonhava com a união dos países hispano-americanos; morreu em Santa Marta, na Colômbia, em 1830.",
           aliases=["Bolívar", "O Libertador"]),
    fato("mundo_guerra_civil_americana", "Guerra Civil Americana", US,
         "Guerra Civil Americana, ou Guerra de Secessão, foi o conflito de 1861 a 1865 entre os estados do Norte dos Estados Unidos (a União) e os estados escravistas do Sul que formaram os Estados Confederados.",
         "A principal causa da Guerra Civil Americana foi a escravidão e sua expansão para os novos territórios, após a eleição de Abraham Lincoln em 1860.",
         "A Guerra Civil Americana começou com o ataque confederado ao Forte Sumter, em abril de 1861; a Batalha de Gettysburg, em julho de 1863, foi um ponto de virada.",
         "A Guerra Civil Americana terminou com a rendição do general confederado Robert E. Lee ao general Ulysses Grant em Appomattox, em 9 de abril de 1865.",
         "A Guerra Civil Americana matou cerca de 620 mil soldados, e em 1865 a 13ª Emenda aboliu a escravidão nos Estados Unidos.",
         aliases=["Guerra de Secessão", "Guerra Civil dos Estados Unidos"]),
    pessoa("mundo_abraham_lincoln", "Abraham Lincoln", US,
           "Abraham Lincoln (1809–1865) foi o 16º presidente dos Estados Unidos, de 1861 a 1865, e governou o país durante a Guerra Civil Americana.",
           "Abraham Lincoln assinou a Proclamação de Emancipação, que entrou em vigor em 1º de janeiro de 1863 e declarou livres os escravizados dos estados rebeldes.",
           "Abraham Lincoln fez em 1863 o Discurso de Gettysburg, que definiu a democracia como governo do povo, pelo povo e para o povo.",
           "Abraham Lincoln foi assassinado por John Wilkes Booth no Teatro Ford, em Washington, e morreu em 15 de abril de 1865.",
           aliases=["Lincoln"]),
    # ---------------- Século XX ----------------
    pessoa("mundo_vladimir_lenin", "Vladimir Lenin", H2,
           "Vladimir Lenin (1870–1924) foi um revolucionário russo que liderou os bolcheviques na Revolução Russa de outubro de 1917 e fundou o Estado soviético.",
           "Vladimir Lenin era marxista e chefiou o primeiro governo soviético, que retirou a Rússia da Primeira Guerra Mundial e enfrentou uma guerra civil.",
           "Em 1921, Vladimir Lenin adotou a Nova Política Econômica (NEP), que permitiu algum comércio privado; morreu em 21 de janeiro de 1924.",
           aliases=["Lenin", "Lênin", "Vladimir Ilitch Lenin"]),
    pessoa("mundo_josef_stalin", "Josef Stalin", H2,
           "Josef Stalin (1878–1953) foi o líder da União Soviética da segunda metade dos anos 1920 até sua morte, em 5 de março de 1953.",
           "Josef Stalin impôs a coletivização forçada da agricultura e planos quinquenais de industrialização, que causaram fome e milhões de mortes.",
           "No governo de Josef Stalin, os Grandes Expurgos de 1936 a 1938 e os campos de trabalho forçado conhecidos como gulags perseguiram milhões de pessoas.",
           "Josef Stalin aliou-se a Reino Unido e Estados Unidos contra a Alemanha nazista na Segunda Guerra Mundial.",
           aliases=["Stalin", "Stálin", "Estaline"]),
    fato("mundo_nazismo", "nazismo", H2,
         "Nazismo, ou nacional-socialismo, foi a ideologia e o regime totalitário do Partido Nazista, que governou a Alemanha de 1933 a 1945 sob Adolf Hitler.",
         "O nazismo pregava o racismo e o antissemitismo, a ideia de uma suposta raça ariana superior, o nacionalismo extremo e a expansão territorial da Alemanha.",
         "O regime do nazismo eliminou partidos e liberdades, perseguiu judeus, ciganos, homossexuais e opositores, e promoveu o Holocausto.",
         "O nazismo terminou com a derrota da Alemanha na Segunda Guerra Mundial, em maio de 1945.",
         aliases=["nacional-socialismo", "regime nazista"]),
    pessoa("mundo_adolf_hitler", "Adolf Hitler", H2,
           "Adolf Hitler (1889–1945) foi o líder do Partido Nazista e ditador da Alemanha de 1933 a 1945, responsável pela Segunda Guerra Mundial na Europa e pelo Holocausto.",
           "Adolf Hitler nasceu em Braunau am Inn, na Áustria, e foi nomeado chanceler da Alemanha em 30 de janeiro de 1933; em 1934 passou a se chamar Führer.",
           "A invasão da Polônia por Adolf Hitler em 1º de setembro de 1939 deu início à Segunda Guerra Mundial na Europa.",
           "O regime de Adolf Hitler matou cerca de 6 milhões de judeus no Holocausto, além de milhões de outras vítimas.",
           "Adolf Hitler suicidou-se em seu bunker em Berlim, em 30 de abril de 1945, poucos dias antes da rendição da Alemanha.",
           aliases=["Hitler"]),
    pessoa("mundo_winston_churchill", "Winston Churchill", H2,
           "Winston Churchill (1874–1965) foi um político britânico, primeiro-ministro do Reino Unido de 1940 a 1945 e de 1951 a 1955, que liderou o país na Segunda Guerra Mundial.",
           "Winston Churchill ficou conhecido por discursos que incentivaram a resistência britânica contra a Alemanha nazista, como o que prometia 'sangue, labuta, lágrimas e suor'.",
           "Em 1946, Winston Churchill popularizou a expressão 'cortina de ferro' para descrever a divisão da Europa no início da Guerra Fria.",
           "Winston Churchill recebeu o Prêmio Nobel de Literatura em 1953 e morreu em 24 de janeiro de 1965.",
           aliases=["Churchill"]),
    fato("mundo_bombas_hiroshima_nagasaki", "bombardeios de Hiroshima e Nagasaki", H2,
         "Os bombardeios de Hiroshima e Nagasaki foram os ataques com bombas atômicas feitos pelos Estados Unidos contra essas cidades japonesas em 6 e 9 de agosto de 1945, no fim da Segunda Guerra Mundial.",
         "Os bombardeios de Hiroshima e Nagasaki foram os únicos usos de armas nucleares em guerra e mataram, até o fim de 1945, cerca de 140 mil pessoas em Hiroshima e cerca de 70 mil em Nagasaki.",
         "Após os bombardeios de Hiroshima e Nagasaki, o Japão anunciou sua rendição em 15 de agosto de 1945 e a assinou em 2 de setembro de 1945.",
         aliases=["bomba de Hiroshima", "bomba atômica de Hiroshima", "Hiroshima e Nagasaki"]),
    fato("mundo_revolucao_cubana", "Revolução Cubana", H2,
         "Revolução Cubana foi o movimento armado liderado por Fidel Castro e Che Guevara que derrubou o ditador Fulgencio Batista em 1º de janeiro de 1959.",
         "A Revolução Cubana começou com o ataque ao quartel Moncada, em 26 de julho de 1953, e com a guerrilha na Sierra Maestra a partir de 1956.",
         "Após a Revolução Cubana, o novo governo nacionalizou empresas, aproximou-se da União Soviética e declarou-se socialista em 1961.",
         "Depois da Revolução Cubana, os Estados Unidos impuseram um embargo econômico a Cuba e apoiaram a fracassada invasão da Baía dos Porcos, em 1961; em 1962 houve a Crise dos Mísseis.",
         aliases=["revolução de Cuba"]),
    pessoa("mundo_fidel_castro", "Fidel Castro", H2,
           "Fidel Castro (1926–2016) foi um revolucionário cubano que liderou a Revolução Cubana e governou Cuba de 1959 a 2008.",
           "Fidel Castro foi primeiro-ministro de Cuba a partir de 1959 e presidente de 1976 a 2008, implantando um regime socialista de partido único aliado à União Soviética.",
           "Fidel Castro passou o poder ao irmão Raúl Castro, provisoriamente em 2006 e definitivamente em 2008, e morreu em 25 de novembro de 2016.",
           aliases=["Fidel"]),
    fato("mundo_guerra_do_vietna", "Guerra do Vietnã", US,
         "Guerra do Vietnã foi o conflito entre o Vietnã do Norte, comunista, e o Vietnã do Sul, apoiado pelos Estados Unidos, que durou de meados dos anos 1950 até 1975.",
         "Na Guerra do Vietnã, os Estados Unidos ampliaram a participação após o incidente do Golfo de Tonkin, em 1964, chegando a ter mais de 500 mil soldados no país em 1969.",
         "A Guerra do Vietnã provocou grandes protestos nos Estados Unidos; os Acordos de Paz de Paris, de 1973, levaram à retirada das tropas americanas.",
         "A Guerra do Vietnã terminou com a tomada de Saigon pelos norte-vietnamitas em 30 de abril de 1975; o país foi reunificado como república socialista em 1976.",
         "A Guerra do Vietnã matou cerca de 58 mil militares americanos e milhões de vietnamitas.",
         aliases=["Guerra do Vietname"]),
    fato("mundo_corrida_espacial", "corrida espacial", NASA,
         "Corrida espacial foi a disputa entre Estados Unidos e União Soviética, durante a Guerra Fria, por conquistas na exploração do espaço, entre o fim dos anos 1950 e os anos 1970.",
         "Na corrida espacial, a União Soviética lançou o primeiro satélite artificial, o Sputnik 1, em 4 de outubro de 1957, e levou o primeiro ser humano ao espaço, Yuri Gagarin, em 1961.",
         "Os Estados Unidos criaram a NASA em 1958 e venceram a etapa principal da corrida espacial ao pousar astronautas na Lua com a Apollo 11, em 1969.",
         aliases=["corrida pelo espaço"]),
    pessoa("mundo_yuri_gagarin", "Yuri Gagarin", NASA,
           "Yuri Gagarin (1934–1968) foi um cosmonauta soviético, o primeiro ser humano a viajar ao espaço, em 12 de abril de 1961.",
           "Yuri Gagarin voou na nave Vostok 1 e deu uma volta completa em torno da Terra em cerca de 108 minutos.",
           "Yuri Gagarin morreu em 27 de março de 1968, na queda de um avião de treinamento militar.",
           aliases=["Gagarin", "Iuri Gagarin"]),
    fato("mundo_apollo_11", "Apollo 11", NASA,
         "Apollo 11 foi a missão espacial da NASA que levou o homem à Lua pela primeira vez: os astronautas Neil Armstrong e Buzz Aldrin chegaram à Lua em 20 de julho de 1969.",
         "A Apollo 11 foi lançada em 16 de julho de 1969 pelo foguete Saturno V, do Centro Espacial Kennedy, na Flórida, com os astronautas Neil Armstrong, Buzz Aldrin e Michael Collins.",
         "Na Apollo 11, o módulo lunar Eagle pousou no Mar da Tranquilidade; Neil Armstrong foi o primeiro a pisar na Lua e Buzz Aldrin, o segundo, enquanto Michael Collins ficou em órbita.",
         "Ao pisar na Lua durante a Apollo 11, Neil Armstrong disse: 'Este é um pequeno passo para um homem, um salto gigante para a humanidade'.",
         "Os astronautas da Apollo 11 trouxeram cerca de 21,5 kg de rochas e solo lunar e voltaram à Terra em 24 de julho de 1969, pousando no oceano Pacífico.",
         aliases=["chegada do homem à Lua", "homem na Lua", "pouso na Lua", "Apolo 11", "primeira viagem tripulada à Lua"]),
    pessoa("mundo_neil_armstrong", "Neil Armstrong", NASA,
           "Neil Armstrong (1930–2012) foi um astronauta norte-americano, o primeiro ser humano a pisar na Lua, em 20 de julho de 1969, como comandante da missão Apollo 11.",
           "Neil Armstrong nasceu em Wapakoneta, Ohio, foi piloto da Marinha dos Estados Unidos e piloto de testes de aviões experimentais, como o X-15.",
           "Em 1966, na missão Gemini 8, Neil Armstrong realizou o primeiro acoplamento entre duas naves no espaço.",
           "Depois de deixar a NASA, Neil Armstrong foi professor de engenharia aeroespacial; morreu em 25 de agosto de 2012.",
           aliases=["Armstrong"]),
    fato("mundo_queda_muro_berlim", "queda do Muro de Berlim", H2,
         "A queda do Muro de Berlim ocorreu em 9 de novembro de 1989: o Muro de Berlim caiu quando a Alemanha Oriental abriu a fronteira e os berlinenses começaram a atravessar e derrubar o muro.",
         "O Muro de Berlim foi construído pela Alemanha Oriental a partir de 13 de agosto de 1961 para impedir a fuga de seus cidadãos para Berlim Ocidental.",
         "O Muro de Berlim cercava Berlim Ocidental com cerca de 155 km de extensão, e ao menos 140 pessoas morreram tentando atravessá-lo.",
         "A queda do Muro de Berlim levou à reunificação da Alemanha em 3 de outubro de 1990 e tornou-se símbolo do fim da Guerra Fria.",
         aliases=["Muro de Berlim", "queda do muro"]),
    fato("mundo_ataques_11_setembro", "ataques de 11 de setembro de 2001", US,
         "Os ataques de 11 de setembro de 2001 foram atentados terroristas da rede al-Qaeda nos Estados Unidos, em que 19 sequestradores tomaram quatro aviões comerciais.",
         "Nos ataques de 11 de setembro de 2001, dois aviões atingiram as Torres Gêmeas do World Trade Center, em Nova York, que desabaram, e outro atingiu o Pentágono, perto de Washington.",
         "Nos ataques de 11 de setembro de 2001, o quarto avião caiu num campo na Pensilvânia depois que passageiros reagiram aos sequestradores.",
         "Os ataques de 11 de setembro de 2001 mataram cerca de 3 mil pessoas, o maior atentado terrorista da história dos Estados Unidos.",
         "Após os ataques de 11 de setembro de 2001, os Estados Unidos lançaram a chamada guerra ao terror e invadiram o Afeganistão; Osama bin Laden foi morto em 2011, no Paquistão.",
         aliases=["11 de setembro", "atentados de 11 de setembro", "ataque às Torres Gêmeas", "11/9"]),
]

if __name__ == "__main__":
    import sys
    for it in ITENS:
        assert 3 <= len(it["fatos"]) <= 6, it["id"]
        for f in it["fatos"]:
            assert len(f["texto"]) <= 300, (it["id"], len(f["texto"]), f["texto"][:60])
    salvar(sys.argv[1], "Sínteses próprias de fatos e personagens históricos do Brasil e do mundo, com base em manuais "
           "abertos (OpenStax, CC BY 4.0), NASA (domínio público) e referências institucionais brasileiras. Datas e "
           "números são aproximações correntes da historiografia.", FONTES, ITENS)
