from comum import conceito, openstax, referencia, salvar

H1 = "openstax_historia_mundial_v1"
H2 = "openstax_historia_mundial_v2"
AN = "arquivo_nacional"
FONTES = [
    openstax(H1, "World History Volume 1: to 1500", "world-history-volume-1",
             "OpenStax, Rice University; Ann Kordas, Ryan J. Lynch, Brooke Nelson, Julie Tatlock"),
    openstax(H2, "World History Volume 2: from 1400", "world-history-volume-2",
             "OpenStax, Rice University; Ann Kordas, Ryan J. Lynch, Brooke Nelson, Julie Tatlock"),
    referencia(AN, "Arquivo Nacional — acervo e história do Brasil", "https://www.gov.br/arquivonacional/pt-br",
               "Arquivo Nacional (Brasil)", "https://www.gov.br/pt-br/termos-de-uso"),
]
S = "social"
A = "historia"

ITENS = [
    # “história” fica livre para o sentido de narrativa, usado pela escrita
    # (“continue a história”); a disciplina responde por historiografia.
    conceito("mundo_historia", "historiografia", A, H1, S,
             "Historiografia, ou história como disciplina, é o estudo do passado humano a partir de fontes como documentos, objetos, construções e relatos.",
             "Historiadores comparam fontes, avaliam quem as produziu e com que propósito, e constroem interpretações que podem ser revistas com novas evidências.",
             "A divisão em Pré-História, Antiguidade, Idade Média, Idade Moderna e Idade Contemporânea é uma convenção de origem europeia, não uma fronteira natural.",
             aliases=["ciência histórica", "estudo da história"]),
    conceito("mundo_pre_historia", "Pré-História", A, H1, S,
             "Pré-História é o longo período da trajetória humana anterior ao surgimento da escrita.",
             "É conhecida sobretudo por vestígios arqueológicos: ferramentas de pedra, ossos, pinturas rupestres e restos de acampamentos.",
             "O termo é criticado por sugerir que povos sem escrita não teriam história; muitos pesquisadores preferem falar em sociedades sem escrita.",
             ),
    conceito("mundo_revolucao_neolitica", "Revolução Neolítica", A, H1, S,
             "Revolução Neolítica é a transição de grupos caçadores-coletores para a agricultura e a domesticação de animais.",
             "Começou há cerca de 12 mil anos no Crescente Fértil, no Oriente Médio, e surgiu de forma independente em outras regiões, como China, Mesoamérica e Andes.",
             "A produção de excedentes favoreceu aldeias permanentes, aumento populacional e, mais tarde, cidades e hierarquias sociais.",
             aliases=["revolução agrícola", "neolítico"]),
    conceito("mundo_mesopotamia", "Mesopotâmia", A, H1, S,
             "Mesopotâmia é a região entre os rios Tigre e Eufrates, no atual Iraque, onde surgiram algumas das primeiras cidades.",
             "Os sumérios desenvolveram ali a escrita cuneiforme, por volta de 3200 a.C., inicialmente para registros administrativos.",
             "O Código de Hamurábi, da Babilônia, por volta de 1750 a.C., é um dos conjuntos de leis escritas mais antigos conhecidos."),
    conceito("mundo_egito_antigo", "Egito Antigo", A, H1, S,
             "Egito Antigo foi a civilização que se desenvolveu às margens do rio Nilo por cerca de três mil anos.",
             "As cheias anuais do Nilo depositavam solo fértil e sustentavam a agricultura.",
             "O faraó era considerado governante e figura sagrada; as pirâmides de Gizé foram construídas como túmulos reais por volta de 2500 a.C.",
             "A escrita hieroglífica foi decifrada no século XIX com auxílio da Pedra de Roseta.",
             aliases=["antigo Egito"]),
    conceito("mundo_grecia_antiga", "Grécia Antiga", A, H1, S,
             "Grécia Antiga foi o conjunto de cidades-estado gregas, como Atenas e Esparta, que floresceu sobretudo entre os séculos VIII e IV a.C.",
             "Atenas desenvolveu no século V a.C. uma forma de democracia direta, restrita a cidadãos homens livres.",
             "A cultura grega influenciou profundamente a filosofia, o teatro, a matemática e a política do mundo ocidental.",
             aliases=["Grécia clássica"]),
    conceito("mundo_democracia_ateniense", "democracia ateniense", A, H1, S,
             "Democracia ateniense foi o sistema em que os cidadãos de Atenas votavam diretamente nas decisões da cidade.",
             "As reformas de Clístenes, por volta de 508 a.C., são consideradas seu marco inicial.",
             "Mulheres, escravizados e estrangeiros residentes não tinham direito de participação.", papeis={1: "limite"}),
    conceito("mundo_roma_antiga", "Roma Antiga", A, H1, S,
             "Roma Antiga foi a civilização que, a partir da cidade de Roma, dominou a bacia do Mediterrâneo.",
             "Passou por monarquia, república e império; Augusto tornou-se o primeiro imperador em 27 a.C.",
             "O direito romano, o latim e a engenharia de estradas e aquedutos deixaram heranças duradouras.",
             "O Império Romano do Ocidente terminou em 476 d.C.; o do Oriente, conhecido como Império Bizantino, durou até 1453.",
             aliases=["Império Romano"]),
    conceito("mundo_china_imperial", "China imperial", A, H1, S,
             "China imperial é o longo período em que a China foi governada por dinastias de imperadores, de 221 a.C. a 1912.",
             "A dinastia Qin unificou o território e padronizou escrita, moedas e medidas.",
             "A dinastia Han consolidou a burocracia baseada em princípios confucianos e expandiu as rotas comerciais.",
             "Invenções como o papel, a bússola, a pólvora e a impressão com tipos móveis surgiram na China."),
    conceito("mundo_rota_da_seda", "Rota da Seda", A, H1, S,
             "Rota da Seda foi a rede de caminhos comerciais terrestres e marítimos que ligava a China ao Mediterrâneo.",
             "Por ela circulavam seda, especiarias, metais, ideias, religiões e também doenças.",
             "O nome foi criado no século XIX; na época, não havia uma estrada única, mas muitas rotas interligadas."),
    conceito("mundo_idade_media", "Idade Média", A, H1, S,
             "Idade Média é o período da história europeia entre a queda do Império Romano do Ocidente, em 476, e meados do século XV.",
             "Na Europa ocidental, foi marcada pelo feudalismo e pela forte presença da Igreja Católica.",
             "A imagem de uma 'idade das trevas' é contestada: houve universidades, comércio, catedrais e intensa troca com o mundo islâmico.",
             aliases=["período medieval", "era medieval"], papeis={1: "limite"}),
    conceito("mundo_feudalismo", "feudalismo", A, H1, S,
             "Feudalismo foi a organização social e política da Europa medieval baseada em laços pessoais entre senhores e vassalos e no trabalho dos servos na terra.",
             "O vassalo recebia terras (feudos) em troca de lealdade e serviço militar.",
             "Os servos estavam presos à terra e deviam parte da produção e trabalho ao senhor."),
    conceito("mundo_islamismo_expansao", "expansão islâmica", A, H1, S,
             "Expansão islâmica foi a difusão do islamismo e dos califados a partir da Península Arábica, depois da morte de Maomé em 632.",
             "Em pouco mais de um século, o domínio muçulmano ia da Península Ibérica à Ásia Central.",
             "Cidades como Bagdá e Córdoba tornaram-se centros de ciência, tradução e filosofia, preservando e ampliando obras gregas.",
             aliases=["califado"]),
    conceito("mundo_imperio_mongol", "Império Mongol", A, H1, S,
             "Império Mongol foi o maior império terrestre contínuo da história, formado no século XIII.",
             "Gengis Khan unificou as tribos mongóis em 1206 e iniciou conquistas na Ásia e na Europa oriental.",
             "Ao unificar grandes áreas, facilitou o comércio na Rota da Seda."),
    conceito("mundo_peste_negra", "Peste Negra", A, H1, S,
             "Peste Negra foi a pandemia de peste bubônica que atingiu a Eurásia e o norte da África no século XIV.",
             "Entre 1347 e 1351, matou estimadamente entre um terço e metade da população da Europa.",
             "Era causada pela bactéria Yersinia pestis, transmitida principalmente por pulgas de roedores.", papeis={1: "causa"}),
    conceito("mundo_renascimento", "Renascimento", A, H2, S,
             "Renascimento foi o movimento cultural europeu, iniciado na Itália no século XIV, que valorizou o humanismo e a herança greco-romana.",
             "Artistas como Leonardo da Vinci e Michelangelo combinaram observação da natureza, perspectiva e anatomia.",
             "A imprensa de tipos móveis de Gutenberg, por volta de 1450, ampliou a circulação de livros e ideias.",
             aliases=["renascença"]),
    conceito("mundo_reforma_protestante", "Reforma Protestante", A, H2, S,
             "Reforma Protestante foi o movimento religioso do século XVI que rompeu com a autoridade do papa e originou igrejas protestantes.",
             "Começou em 1517, quando Martinho Lutero divulgou suas 95 teses contra a venda de indulgências.",
             "A Igreja Católica respondeu com a Contrarreforma, incluindo o Concílio de Trento.",
             aliases=["Reforma"]),
    conceito("mundo_grandes_navegacoes", "Grandes Navegações", A, H2, S,
             "Grandes Navegações foram as viagens marítimas europeias dos séculos XV e XVI que ampliaram rotas comerciais e iniciaram a colonização de outros continentes.",
             "Portugal e Espanha lideraram, com viagens como a de Vasco da Gama à Índia (1498) e a de Colombo à América (1492).",
             "A expedição de Fernão de Magalhães completou a primeira circunavegação do planeta em 1522.",
             aliases=["expansão marítima", "era dos descobrimentos"]),
    conceito("mundo_intercambio_colombiano", "intercâmbio colombiano", A, H2, S,
             "Intercâmbio colombiano é a troca de plantas, animais, pessoas e doenças entre Américas, Europa e África depois de 1492.",
             "Milho, batata, tomate e cacau foram levados da América; cavalos, gado, trigo e cana-de-açúcar chegaram às Américas.",
             "Doenças como a varíola causaram enorme mortalidade entre povos indígenas.", papeis={1: "causa"}),
    conceito("mundo_trafico_atlantico", "tráfico atlântico de escravizados", A, H2, S,
             "Tráfico atlântico de escravizados foi o comércio forçado de africanos para as Américas, entre os séculos XVI e XIX.",
             "Estima-se que cerca de 12,5 milhões de pessoas tenham sido embarcadas na África; muitas morreram na travessia.",
             "O Brasil foi o destino que mais recebeu africanos escravizados, cerca de 40% do total.",
             aliases=["tráfico negreiro", "escravidão atlântica"]),
    conceito("mundo_revolucao_cientifica", "Revolução Científica", A, H2, S,
             "Revolução Científica foi a transformação, nos séculos XVI e XVII, na forma de investigar a natureza, com ênfase em observação, experimento e matemática.",
             "Copérnico propôs o modelo heliocêntrico; Galileu, Kepler e Newton deram a ele base observacional e matemática.",
             "Os Principia de Newton, de 1687, unificaram o movimento na Terra e nos céus."),
    conceito("mundo_iluminismo", "Iluminismo", A, H2, S,
             "Iluminismo foi o movimento intelectual europeu do século XVIII que defendia a razão, a ciência, a tolerância e os direitos individuais.",
             "Pensadores como Locke, Montesquieu, Voltaire e Rousseau criticaram o absolutismo e a intolerância religiosa.",
             "Suas ideias influenciaram a independência dos Estados Unidos e a Revolução Francesa.",
             aliases=["Século das Luzes", "Ilustração"]),
    conceito("mundo_revolucao_francesa", "Revolução Francesa", A, H2, S,
             "Revolução Francesa foi o processo revolucionário iniciado em 1789 que derrubou a monarquia absolutista na França.",
             "A tomada da Bastilha, em 14 de julho de 1789, tornou-se seu símbolo.",
             "A Declaração dos Direitos do Homem e do Cidadão proclamou igualdade perante a lei e soberania popular.",
             "O período terminou com a ascensão de Napoleão Bonaparte, que tomou o poder em 1799."),
    conceito("mundo_independencia_eua", "independência dos Estados Unidos", A, H2, S,
             "A independência dos Estados Unidos foi a separação das Treze Colônias britânicas da América do Norte, declarada em 4 de julho de 1776.",
             "A guerra com a Grã-Bretanha terminou com o Tratado de Paris, em 1783.",
             "A Constituição de 1787 estabeleceu uma república federal com separação de poderes.",
             aliases=["Revolução Americana"]),
    conceito("mundo_revolucao_haitiana", "Revolução Haitiana", A, H2, S,
             "Revolução Haitiana foi a rebelião de pessoas escravizadas na colônia francesa de São Domingos, iniciada em 1791.",
             "Liderada inicialmente por Toussaint Louverture, levou à independência do Haiti em 1804.",
             "O Haiti foi o primeiro país das Américas a abolir a escravidão e a primeira república fundada por ex-escravizados."),
    conceito("mundo_revolucao_industrial", "Revolução Industrial", A, H2, S,
             "Revolução Industrial foi a transformação da produção, iniciada na Grã-Bretanha no século XVIII, com máquinas, fábricas e novas fontes de energia.",
             "A máquina a vapor aperfeiçoada por James Watt e a mecanização da indústria têxtil foram marcos iniciais.",
             "Provocou urbanização acelerada, crescimento da classe operária e longas jornadas de trabalho, inclusive infantil.",
             "Uma segunda fase, no fim do século XIX, trouxe eletricidade, aço, química e petróleo."),
    conceito("mundo_imperialismo", "imperialismo", A, H2, S,
             "Imperialismo é a política de expansão de um Estado sobre outros territórios, por domínio político, econômico ou militar.",
             "No século XIX, potências europeias dividiram grande parte da África e da Ásia.",
             "A Conferência de Berlim (1884–1885) estabeleceu regras para a partilha da África entre países europeus, sem participação africana.",
             aliases=["neocolonialismo"]),
    conceito("mundo_primeira_guerra", "Primeira Guerra Mundial", A, H2, S,
             "Primeira Guerra Mundial foi o conflito de 1914 a 1918 entre os Aliados, como França, Reino Unido e Rússia, e os Impérios Centrais, como Alemanha e Áustria-Hungria.",
             "O assassinato do arquiduque Francisco Ferdinando, em Sarajevo, em 1914, desencadeou o conflito, num contexto de alianças militares e rivalidades imperialistas.",
             "A guerra de trincheiras e novas armas, como metralhadoras e gases, causaram cerca de 15 a 20 milhões de mortes.",
             "O Tratado de Versalhes, de 1919, impôs duras condições à Alemanha.",
             aliases=["Grande Guerra", "1ª Guerra Mundial"], papeis={0: "causa"}),
    conceito("mundo_revolucao_russa", "Revolução Russa", A, H2, S,
             "Revolução Russa foi o conjunto de revoluções de 1917 que derrubou o czarismo e levou os bolcheviques ao poder.",
             "Liderados por Lênin, os bolcheviques tomaram o poder em outubro de 1917 (novembro pelo calendário ocidental).",
             "Após a guerra civil, formou-se a União Soviética, em 1922."),
    conceito("mundo_grande_depressao", "Grande Depressão", A, H2, S,
             "Grande Depressão foi a grave crise econômica mundial iniciada com a quebra da Bolsa de Nova York, em 1929.",
             "Provocou desemprego em massa, falências e queda do comércio internacional.",
             "No Brasil, a crise derrubou os preços do café, base da economia exportadora.",
             aliases=["crise de 1929"]),
    conceito("mundo_segunda_guerra", "Segunda Guerra Mundial", A, H2, S,
             "Segunda Guerra Mundial foi o conflito de 1939 a 1945 entre os Aliados e o Eixo, formado por Alemanha, Itália e Japão.",
             "Começou com a invasão da Polônia pela Alemanha nazista, em setembro de 1939.",
             "Foi o conflito mais mortal da história, com estimativas de 70 a 85 milhões de mortos, incluindo civis.",
             "Terminou em 1945, após a rendição alemã em maio e a japonesa em setembro, depois das bombas atômicas sobre Hiroshima e Nagasaki.",
             aliases=["2ª Guerra Mundial"]),
    conceito("mundo_holocausto", "Holocausto", A, H2, S,
             "Holocausto foi o genocídio sistemático de cerca de seis milhões de judeus pelo regime nazista e seus colaboradores.",
             "Também foram perseguidos e assassinados ciganos (roma e sinti), pessoas com deficiência, homossexuais e opositores políticos.",
             "Campos de extermínio como Auschwitz-Birkenau tornaram-se símbolo desse crime.",
             aliases=["Shoah"]),
    conceito("mundo_guerra_fria", "Guerra Fria", A, H2, S,
             "Guerra Fria foi a rivalidade política, ideológica e militar entre Estados Unidos e União Soviética, de 1947 a 1991.",
             "Não houve guerra direta entre as duas potências, mas houve corrida armamentista nuclear, corrida espacial e guerras indiretas, como as da Coreia e do Vietnã.",
             "O Muro de Berlim, erguido em 1961 e derrubado em 1989, simbolizou a divisão; a União Soviética se dissolveu em 1991."),
    conceito("mundo_descolonizacao", "descolonização", A, H2, S,
             "Descolonização foi o processo em que colônias na Ásia e na África conquistaram independência, sobretudo entre 1945 e 1975.",
             "A Índia tornou-se independente do Reino Unido em 1947, após um movimento de massas liderado por Gandhi e outros.",
             "Em 1960, dezessete países africanos se tornaram independentes, no chamado Ano da África."),
    conceito("mundo_onu", "Organização das Nações Unidas", A, H2, S,
             "Organização das Nações Unidas (ONU) é a organização internacional criada em 1945 para manter a paz e promover a cooperação entre países.",
             "Seu Conselho de Segurança tem cinco membros permanentes com poder de veto: Estados Unidos, Rússia, China, Reino Unido e França.",
             "A Declaração Universal dos Direitos Humanos foi adotada pela Assembleia Geral em 1948.",
             aliases=["ONU", "Nações Unidas"]),
    conceito("mundo_povos_originarios_brasil", "povos indígenas do Brasil", A, AN, S,
             "Povos indígenas do Brasil são os povos que habitavam o território antes da chegada dos europeus e seus descendentes.",
             "Em 1500, estima-se que viviam milhões de pessoas no território, falando centenas de línguas.",
             "Hoje há mais de 300 povos indígenas no Brasil, com cerca de 270 línguas, segundo o Censo de 2010 do IBGE.",
             aliases=["indígenas brasileiros", "povos originários"]),
    conceito("mundo_brasil_colonia", "Brasil Colônia", A, AN, S,
             "Brasil Colônia é o período de 1500 a 1822, em que o território foi colônia de Portugal.",
             "A esquadra de Pedro Álvares Cabral chegou ao litoral da atual Bahia em abril de 1500.",
             "A economia passou pelo pau-brasil, pela cana-de-açúcar no Nordeste e pela mineração de ouro em Minas Gerais no século XVIII, baseada no trabalho escravizado.",
             aliases=["período colonial brasileiro"]),
    conceito("mundo_quilombo_dos_palmares", "Quilombo dos Palmares", A, AN, S,
             "Quilombo dos Palmares foi a maior comunidade de pessoas que fugiram da escravidão no Brasil colonial, na serra da Barriga, em Alagoas.",
             "Resistiu por quase um século, no século XVII, e chegou a reunir milhares de habitantes.",
             "Zumbi, seu último líder, foi morto em 20 de novembro de 1695; a data é hoje o Dia Nacional de Zumbi e da Consciência Negra.",
             aliases=["Palmares"]),
    conceito("mundo_independencia_brasil", "independência do Brasil", A, AN, S,
             "A independência do Brasil foi a separação política em relação a Portugal, proclamada por D. Pedro em 7 de setembro de 1822.",
             "A vinda da família real portuguesa ao Rio de Janeiro, em 1808, havia transformado a colônia em sede do reino.",
             "Houve guerras de independência em províncias como Bahia, Piauí e Maranhão; na Bahia, a vitória é celebrada em 2 de julho de 1823.",
             "O país tornou-se uma monarquia, o Império do Brasil, com D. Pedro I como imperador."),
    conceito("mundo_abolicao_brasil", "abolição da escravidão no Brasil", A, AN, S,
             "A abolição da escravidão no Brasil ocorreu com a Lei Áurea, assinada pela princesa Isabel em 13 de maio de 1888.",
             "O Brasil foi o último país das Américas a abolir a escravidão.",
             "Leis anteriores, como a Eusébio de Queirós (1850), a do Ventre Livre (1871) e a dos Sexagenários (1885), foram etapas graduais; a luta abolicionista e a resistência dos escravizados pressionaram pelo fim.",
             "A abolição não foi acompanhada de políticas de terra, educação ou trabalho para os libertos.",
             aliases=["Lei Áurea"], papeis={2: "limite"}),
    conceito("mundo_proclamacao_republica", "Proclamação da República", A, AN, S,
             "A Proclamação da República no Brasil ocorreu em 15 de novembro de 1889, quando militares liderados pelo marechal Deodoro da Fonseca depuseram D. Pedro II.",
             "A Primeira República (1889–1930) foi marcada pelo poder das oligarquias e pela chamada política do café com leite.",
             aliases=["República Velha"]),
    conceito("mundo_era_vargas", "Era Vargas", A, AN, S,
             "Era Vargas é o período de 1930 a 1945 em que Getúlio Vargas governou o Brasil.",
             "Incluiu o Estado Novo (1937–1945), uma ditadura com censura e centralização do poder.",
             "Foram criadas a Consolidação das Leis do Trabalho (CLT), em 1943, e empresas estatais como a Companhia Siderúrgica Nacional.",
             "Vargas voltou eleito em 1951 e morreu em 1954, durante uma crise política."),
    conceito("mundo_ditadura_militar_brasil", "ditadura militar no Brasil", A, AN, S,
             "A ditadura militar no Brasil foi o regime autoritário instaurado pelo golpe de 1964 e que durou até 1985.",
             "O AI-5, de 1968, fechou o Congresso temporariamente, suspendeu o habeas corpus para crimes políticos e intensificou a censura.",
             "Houve prisões, tortura, mortes e desaparecimentos de opositores, documentados pela Comissão Nacional da Verdade em 2014.",
             "A campanha Diretas Já (1983–1984) mobilizou milhões de pessoas pela volta das eleições diretas.",
             aliases=["regime militar brasileiro", "golpe de 1964"]),
    conceito("mundo_constituicao_1988", "Constituição de 1988", A, AN, S,
             "A Constituição de 1988 é a lei fundamental do Brasil, promulgada em 5 de outubro de 1988, após a redemocratização.",
             "É chamada de Constituição Cidadã por ampliar direitos sociais e garantias individuais.",
             "Criou o Sistema Único de Saúde (SUS), estabeleceu o voto facultativo para analfabetos e jovens de 16 e 17 anos e definiu o racismo como crime inafiançável.",
             aliases=["Constituição Cidadã"]),
]

LIGACOES = [
    {"origem": "mundo_iluminismo", "destino": "mundo_revolucao_francesa", "indice_fato": 2, "verbos": ["influenciou", "inspirou"]},
    {"origem": "mundo_iluminismo", "destino": "mundo_independencia_eua", "indice_fato": 2, "verbos": ["influenciou", "inspirou"]},
]
COMPARACOES = [
    {"origem": "mundo_primeira_guerra", "destino": "mundo_segunda_guerra", "indice_fato": 0},
    {"origem": "mundo_grecia_antiga", "destino": "mundo_roma_antiga", "indice_fato": 0},
]

if __name__ == "__main__":
    import sys
    salvar(sys.argv[1], "Sínteses próprias de história mundial e do Brasil, com fatos consolidados em manuais abertos "
           "(OpenStax, CC BY 4.0) e referência institucional brasileira. Datas e números são aproximações correntes da "
           "historiografia; interpretações podem mudar com novas evidências.", FONTES, ITENS, LIGACOES, COMPARACOES, aprofundamento="historia")
