from comum import conceito, openstax, referencia, salvar

WG = "openstax_writing_guide"
H1 = "openstax_historia_mundial_v1"
H2 = "openstax_historia_mundial_v2"
ABL = "academia_brasileira_letras"
ANT = "openstax_antropologia"
FONTES = [
    openstax(WG, "Writing Guide with Handbook", "writing-guide",
             "OpenStax, Rice University; Michelle Bachelor Robinson, Maria Jerskey e outros"),
    openstax(H1, "World History Volume 1: to 1500", "world-history-volume-1",
             "OpenStax, Rice University; Ann Kordas, Ryan J. Lynch, Brooke Nelson, Julie Tatlock"),
    openstax(H2, "World History Volume 2: from 1400", "world-history-volume-2",
             "OpenStax, Rice University; Ann Kordas, Ryan J. Lynch, Brooke Nelson, Julie Tatlock"),
    referencia(ABL, "Academia Brasileira de Letras — acadêmicos e patronos", "https://www.academia.org.br/",
               "Academia Brasileira de Letras", "https://www.academia.org.br/"),
    openstax(ANT, "Introduction to Anthropology", "introduction-anthropology",
             "OpenStax, Rice University; Jennifer Hasty, David G. Lewis, Marjorie M. Snipes"),
]
S = "social"
A = "literatura"

ITENS = [
    conceito("mundo_narrativa", "narrativa", A, WG, S,
             "Narrativa é o relato de acontecimentos, reais ou imaginários, organizados numa sequência com personagens, tempo e espaço.",
             "Seus elementos básicos são enredo, personagens, narrador, tempo, espaço e conflito.",
             "Uma estrutura comum tem situação inicial, conflito ou complicação, clímax e desfecho.",
             aliases=["texto narrativo", "história narrada"]),
    conceito("mundo_enredo", "enredo", A, WG, S,
             "Enredo é a sequência de acontecimentos de uma narrativa, ligados por relações de causa e consequência.",
             "Costuma avançar a partir de um conflito que desestabiliza a situação inicial.",
             "O clímax é o momento de maior tensão, antes do desfecho.",
             aliases=["trama", "intriga"]),
    conceito("mundo_personagem", "personagem", A, WG, S,
             "Personagem é um ser que age, fala ou sofre ações numa narrativa.",
             "O protagonista é a personagem central; o antagonista se opõe a ele.",
             "Personagens planas têm poucos traços e mudam pouco; personagens redondas são complexas e podem se transformar ao longo da história.",
             aliases=["personagens", "protagonista"]),
    conceito("mundo_narrador", "narrador", A, WG, S,
             "Narrador é a voz que conta a história, que não se confunde com o autor.",
             "O narrador em primeira pessoa participa dos fatos; o narrador em terceira pessoa os observa de fora.",
             "O narrador onisciente conhece pensamentos e sentimentos das personagens.",
             aliases=["foco narrativo", "ponto de vista narrativo"]),
    conceito("mundo_conflito_narrativo", "conflito narrativo", A, WG, S,
             "Conflito narrativo é a tensão ou o problema que move a história e exige uma resolução.",
             "Pode ser externo, entre personagens ou contra a natureza e a sociedade, ou interno, dentro da própria personagem.",
             "Sem conflito, não há transformação nem expectativa sobre o desfecho.", papeis={1: "limite"}),
    conceito("mundo_jornada_do_heroi", "jornada do herói", A, WG, S,
             "Jornada do herói é um modelo de estrutura narrativa, descrito por Joseph Campbell, em que o herói deixa seu mundo, enfrenta provações e retorna transformado.",
             "Etapas comuns são o chamado à aventura, a travessia de um limiar, as provações, a crise e o retorno.",
             "É um modelo descritivo de muitas histórias, não uma regra obrigatória de escrita.",
             aliases=["monomito"], papeis={1: "limite"}),
    conceito("mundo_genero_literario", "gênero literário", A, WG, S,
             "Gênero literário é uma categoria que agrupa obras com características semelhantes de forma e conteúdo.",
             "A divisão clássica, herdada de Aristóteles, distingue o épico ou narrativo, o lírico e o dramático.",
             "Dentro deles há subgêneros, como romance, conto, crônica, poema e peça teatral.",
             aliases=["gêneros literários"]),
    conceito("mundo_romance_literario", "romance", A, WG, S,
             "Romance é uma narrativa longa em prosa, com várias personagens, conflitos e um desenvolvimento amplo de tempo e espaço.",
             "Tornou-se o gênero literário mais popular a partir do século XIX.",
             aliases=["romance literário"]),
    conceito("mundo_conto", "conto", A, WG, S,
             "Conto é uma narrativa curta, em geral com um único conflito central, poucas personagens e tempo concentrado.",
             "Busca causar um efeito único e intenso no leitor.",
             aliases=["contos"]),
    conceito("mundo_cronica", "crônica", A, WG, S,
             "Crônica é um texto curto, em geral publicado em jornais ou revistas, que comenta fatos do cotidiano com tom pessoal, leve ou reflexivo.",
             "É um gênero muito cultivado no Brasil, por autores como Rubem Braga, Fernando Sabino e Luis Fernando Verissimo.",
             aliases=["crônicas"]),
    conceito("mundo_poesia", "poesia", A, WG, S,
             "Poesia é a arte de expressar ideias e emoções explorando ritmo, sonoridade, imagens e a forma das palavras.",
             "Um poema se organiza em versos e estrofes; pode ter rima e métrica ou usar verso livre.",
             "O soneto é uma forma fixa de catorze versos, em geral dois quartetos e dois tercetos.",
             aliases=["poema", "poemas"]),
    conceito("mundo_metafora", "metáfora", A, WG, S,
             "Metáfora é a figura de linguagem que aproxima dois elementos por semelhança, sem usar palavras de comparação.",
             "Em 'meu coração é um balão', o coração é descrito pelas qualidades do balão.",
             "Quando a comparação usa 'como' ou 'feito', a figura se chama comparação ou símile.",
             aliases=["metáforas"], papeis={1: "exemplo"}),
    conceito("mundo_mito", "mito", A, ANT, S,
             "Mito é uma narrativa tradicional que explica a origem do mundo, de seres, de costumes ou de fenômenos, em geral com seres sobrenaturais.",
             "Para os povos que os contam, mitos transmitem valores, identidades e modos de entender o mundo.",
             "Na linguagem cotidiana, 'mito' também significa crença falsa; os antropólogos usam o termo sem esse sentido.",
             aliases=["mitologia", "mitos"], papeis={2: "limite"}),
    conceito("mundo_mitologia_grega", "mitologia grega", A, H1, S,
             "Mitologia grega é o conjunto de mitos dos antigos gregos sobre deuses, heróis e a origem do mundo.",
             "Os principais deuses, liderados por Zeus, viveriam no monte Olimpo.",
             "Heróis como Héracles, Perseu e Aquiles protagonizam narrativas que influenciaram a arte e a literatura ocidentais."),
    conceito("mundo_epopeia_de_gilgamesh", "Epopeia de Gilgamesh", A, H1, S,
             "A Epopeia de Gilgamesh é um poema épico da Mesopotâmia, uma das obras literárias mais antigas conhecidas.",
             "Narra as aventuras do rei Gilgamesh, de Uruk, e sua busca pela imortalidade após a morte do amigo Enkidu.",
             "Inclui um relato de dilúvio com semelhanças com a narrativa bíblica de Noé.",
             aliases=["Gilgamesh"]),
    conceito("mundo_iliada_odisseia", "Ilíada e Odisseia", A, H1, S,
             "Ilíada e Odisseia são poemas épicos gregos atribuídos a Homero, compostos por volta do século VIII a.C.",
             "A Ilíada trata de um episódio da Guerra de Troia, centrado na ira de Aquiles.",
             "A Odisseia narra a longa viagem de volta de Ulisses (Odisseu) para casa, em Ítaca.",
             aliases=["Ilíada", "Odisseia", "Homero"]),
    conceito("mundo_mil_e_uma_noites", "Mil e Uma Noites", A, H1, S,
             "As Mil e Uma Noites é uma coletânea de contos do Oriente Médio e da Ásia reunidos ao longo de séculos.",
             "Na moldura da obra, Sherazade conta histórias ao rei a cada noite, adiando sua própria execução.",
             "Histórias como as de Aladim e de Ali Babá foram acrescentadas em versões europeias do século XVIII.",
             aliases=["As Mil e Uma Noites", "Sherazade"]),
    conceito("mundo_contos_de_fadas", "contos de fadas", A, WG, S,
             "Contos de fadas são narrativas maravilhosas, de origem popular, com elementos mágicos, provações e, em geral, final feliz.",
             "Charles Perrault, no século XVII, e os irmãos Grimm, no século XIX, registraram versões famosas, como Chapeuzinho Vermelho e Cinderela.",
             "As versões antigas costumavam ser mais sombrias do que as adaptações modernas.",
             aliases=["conto de fadas", "contos maravilhosos"]),
    conceito("mundo_folclore_brasileiro", "folclore brasileiro", A, ANT, S,
             "Folclore brasileiro é o conjunto de lendas, festas, músicas, danças e saberes populares transmitidos entre gerações no Brasil.",
             "Reúne influências indígenas, africanas e europeias.",
             "Personagens conhecidos são o Saci, a Iara, o Curupira, o Boto e a Mula sem Cabeça.",
             aliases=["lendas brasileiras", "folclore"]),
    conceito("mundo_literatura_de_cordel", "literatura de cordel", A, ABL, S,
             "Literatura de cordel é a poesia popular em folhetos, muito presente no Nordeste brasileiro.",
             "Os folhetos eram expostos pendurados em cordões nas feiras, origem do nome, e costumam ter capas em xilogravura.",
             "Em 2018, foi reconhecida como patrimônio cultural imaterial do Brasil pelo IPHAN.",
             aliases=["cordel"]),
    conceito("mundo_dom_casmurro", "Dom Casmurro", A, ABL, S,
             "Dom Casmurro é um romance de Machado de Assis, publicado em 1899.",
             "O narrador, Bento Santiago, conta sua vida e seu ciúme de Capitu, que ele suspeita tê-lo traído com o amigo Escobar.",
             "Como a história é contada só pelo ponto de vista de Bento, a suposta traição nunca é comprovada, e o leitor permanece em dúvida."),
    conceito("mundo_memorias_postumas", "Memórias Póstumas de Brás Cubas", A, ABL, S,
             "Memórias Póstumas de Brás Cubas é um romance de Machado de Assis, publicado em livro em 1881.",
             "É narrado por um 'defunto autor', que conta sua vida depois de morto, com ironia e digressões.",
             "É considerado o marco inicial do Realismo no Brasil."),
    conceito("mundo_modernismo_brasileiro", "modernismo brasileiro", A, ABL, S,
             "Modernismo brasileiro foi o movimento artístico e literário que buscou renovar a linguagem e valorizar a cultura nacional.",
             "A Semana de Arte Moderna de 1922, em São Paulo, é seu marco inicial.",
             "Mário de Andrade, Oswald de Andrade, Anita Malfatti e Tarsila do Amaral estão entre seus principais nomes.",
             aliases=["Semana de Arte Moderna", "modernismo"]),
    conceito("mundo_grande_sertao_veredas", "Grande Sertão: Veredas", A, ABL, S,
             "Grande Sertão: Veredas é um romance de João Guimarães Rosa, publicado em 1956.",
             "O ex-jagunço Riobaldo narra sua vida no sertão, sua relação com Diadorim e suas dúvidas sobre um pacto com o diabo.",
             "É conhecido pela linguagem inventiva, que recria a fala sertaneja.",
             aliases=["Guimarães Rosa"]),
    conceito("mundo_dom_quixote", "Dom Quixote", A, H2, S,
             "Dom Quixote de la Mancha é um romance de Miguel de Cervantes, publicado em 1605 e 1615.",
             "Um fidalgo, de tanto ler romances de cavalaria, decide tornar-se cavaleiro andante, acompanhado do escudeiro Sancho Pança.",
             "A cena em que ele ataca moinhos de vento achando que são gigantes tornou-se símbolo de idealismo deslocado da realidade."),
    conceito("mundo_hamlet", "Hamlet", A, H2, S,
             "Hamlet é uma tragédia de William Shakespeare, escrita por volta de 1600.",
             "O príncipe da Dinamarca busca vingar a morte do pai, assassinado pelo tio, que se casou com a rainha.",
             "O monólogo 'Ser ou não ser, eis a questão' é uma das falas mais conhecidas do teatro."),
]

if __name__ == "__main__":
    import sys
    salvar(sys.argv[1], "Sínteses próprias sobre narrativa, gêneros literários, mitos e obras de referência, com manuais "
           "abertos e fontes institucionais. Resumos de enredo não substituem a leitura das obras.", FONTES, ITENS)
