from comum import conceito, dominio_publico, referencia, salvar

CIA = "pai_cia_factbook"
IBGE = "pai_ibge_paises"
FONTES = [
    dominio_publico(CIA, "The World Factbook", "https://www.cia.gov/the-world-factbook/",
                    "Central Intelligence Agency (EUA)",
                    "https://www.cia.gov/the-world-factbook/about/copyright-notice/"),
    referencia(IBGE, "IBGE Países", "https://paises.ibge.gov.br/",
               "Instituto Brasileiro de Geografia e Estatística (IBGE)", "https://www.gov.br/pt-br/termos-de-uso"),
]
S = "social"
A = "geografia"


def pais(ident, nome, *fatos, aliases=()):
    return conceito(ident, nome, A, CIA, S, *fatos, aliases=aliases)


ITENS = [
    # América do Sul (o Brasil já tem ficha em geografia.py)
    pais("mundo_argentina", "Argentina",
         "Argentina é um país do sul da América do Sul, que faz fronteira com o Brasil, o Chile, a Bolívia, o Paraguai e o Uruguai e tem amplo litoral no Atlântico.",
         "A capital da Argentina é Buenos Aires.",
         "O idioma oficial da Argentina é o espanhol, e a moeda é o peso argentino.",
         "A Argentina tem cerca de 46 milhões de habitantes e cerca de 2,8 milhões de km², sendo o segundo maior país da América do Sul e o oitavo do mundo em área.",
         "A Argentina declarou independência da Espanha em 9 de julho de 1816; o tango nasceu na região do Rio da Prata no fim do século XIX.",
         "Na Argentina fica o Aconcágua, com cerca de 6.960 metros, a montanha mais alta das Américas.",
         aliases=["República Argentina"]),
    pais("mundo_bolivia", "Bolívia",
         "Bolívia é um país do centro-oeste da América do Sul, sem saída para o mar, que faz fronteira com o Brasil, o Peru, o Chile, a Argentina e o Paraguai.",
         "A capital da Bolívia é Sucre, capital constitucional; a sede do governo fica em La Paz.",
         "A Bolívia tem como idiomas oficiais o espanhol e dezenas de línguas indígenas, como quíchua, aimará e guarani; a moeda é o boliviano.",
         "A Bolívia tem cerca de 12 milhões de habitantes e cerca de 1,1 milhão de km²; perdeu seu litoral para o Chile na Guerra do Pacífico (1879-1884).",
         "Na Bolívia ficam o Salar de Uyuni, o maior deserto de sal do mundo, e parte do lago Titicaca, compartilhado com o Peru.",
         aliases=["Estado Plurinacional da Bolívia", "Bolivia"]),
    pais("mundo_chile", "Chile",
         "Chile é um país do oeste da América do Sul, uma faixa estreita de terra entre a Cordilheira dos Andes e o Oceano Pacífico.",
         "A capital do Chile é Santiago.",
         "O idioma oficial do Chile é o espanhol, e a moeda é o peso chileno.",
         "O Chile tem cerca de 19 milhões de habitantes e cerca de 756 mil km², com mais de 4.000 km de comprimento de norte a sul; no norte fica o deserto do Atacama, um dos lugares mais secos do planeta.",
         "O Chile é o maior produtor mundial de cobre; em 1973, um golpe militar derrubou o presidente Salvador Allende e iniciou a ditadura de Augusto Pinochet, que durou até 1990.",
         aliases=["República do Chile"]),
    pais("mundo_colombia", "Colômbia",
         "Colômbia é um país do noroeste da América do Sul, o único do continente com litoral tanto no Oceano Pacífico quanto no Mar do Caribe.",
         "A capital da Colômbia é Bogotá.",
         "O idioma oficial da Colômbia é o espanhol, e a moeda é o peso colombiano.",
         "A Colômbia tem cerca de 50 milhões de habitantes e cerca de 1,14 milhão de km²; é um dos maiores produtores de café do mundo.",
         "Em 2016, o governo da Colômbia assinou um acordo de paz com as FARC, encerrando mais de cinco décadas de conflito armado; o escritor colombiano Gabriel García Márquez recebeu o Nobel de Literatura em 1982.",
         aliases=["República da Colômbia", "Colombia"]),
    pais("mundo_equador_pais", "Equador",
         "Equador é um país do noroeste da América do Sul, banhado pelo Oceano Pacífico e atravessado pela linha do Equador, que lhe dá o nome.",
         "A capital do Equador é Quito, situada a cerca de 2.850 metros de altitude nos Andes.",
         "O idioma oficial do Equador é o espanhol, e a moeda é o dólar americano, adotado em 2000.",
         "O Equador tem cerca de 18 milhões de habitantes e cerca de 284 mil km².",
         "O Equador inclui as Ilhas Galápagos, no Pacífico, cuja fauna única ajudou Charles Darwin a formular a teoria da evolução por seleção natural.",
         aliases=["República do Equador"]),
    pais("mundo_guiana", "Guiana",
         "Guiana é um país do norte da América do Sul, no litoral do Atlântico, que faz fronteira com o Brasil, a Venezuela e o Suriname.",
         "A capital da Guiana é Georgetown.",
         "O idioma oficial da Guiana é o inglês, o que a torna o único país sul-americano com esse idioma oficial; a moeda é o dólar guianense.",
         "A Guiana tem cerca de 800 mil habitantes e cerca de 215 mil km².",
         "A Guiana foi colônia britânica, com o nome de Guiana Inglesa, e tornou-se independente em 1966; desde 2015, grandes descobertas de petróleo no mar transformaram sua economia.",
         aliases=["República Cooperativista da Guiana", "Guiana Inglesa"]),
    pais("mundo_paraguai", "Paraguai",
         "Paraguai é um país do centro da América do Sul, sem saída para o mar, que faz fronteira com o Brasil, a Argentina e a Bolívia.",
         "A capital do Paraguai é Assunção.",
         "O Paraguai tem dois idiomas oficiais, o espanhol e o guarani; a moeda também se chama guarani.",
         "O Paraguai tem cerca de 7 milhões de habitantes e cerca de 407 mil km²; divide com o Brasil a usina hidrelétrica de Itaipu, no rio Paraná.",
         "A Guerra do Paraguai (1864-1870), travada contra Brasil, Argentina e Uruguai, a Tríplice Aliança, devastou a população paraguaia.",
         aliases=["República do Paraguai"]),
    pais("mundo_peru", "Peru",
         "Peru é um país do oeste da América do Sul, banhado pelo Oceano Pacífico e atravessado pela Cordilheira dos Andes, que faz fronteira com o Brasil.",
         "A capital do Peru é Lima.",
         "Os idiomas oficiais do Peru são o espanhol, o quíchua e o aimará; a moeda é o sol.",
         "O Peru tem cerca de 33 milhões de habitantes e cerca de 1,29 milhão de km², sendo o terceiro maior país da América do Sul.",
         "O Peru foi o centro do Império Inca, cuja capital era Cusco; a cidadela de Machu Picchu, do século XV, é um dos sítios arqueológicos mais famosos do mundo.",
         aliases=["República do Peru"]),
    pais("mundo_suriname", "Suriname",
         "Suriname é um país do norte da América do Sul, no litoral do Atlântico, entre a Guiana e a Guiana Francesa, que faz fronteira com o Brasil.",
         "A capital do Suriname é Paramaribo.",
         "O idioma oficial do Suriname é o neerlandês, e a moeda é o dólar surinamês.",
         "O Suriname tem cerca de 650 mil habitantes e cerca de 164 mil km², sendo o menor país da América do Sul; florestas cobrem mais de 90% do território.",
         "O Suriname foi colônia dos Países Baixos e tornou-se independente em 1975.",
         aliases=["República do Suriname"]),
    pais("mundo_uruguai", "Uruguai",
         "Uruguai é um país do sudeste da América do Sul, entre o Brasil e a Argentina, banhado pelo Rio da Prata e pelo Oceano Atlântico.",
         "A capital do Uruguai é Montevidéu.",
         "O idioma oficial do Uruguai é o espanhol, e a moeda é o peso uruguaio.",
         "O Uruguai tem cerca de 3,4 milhões de habitantes e cerca de 176 mil km².",
         "O território do Uruguai foi anexado ao Brasil como Província Cisplatina e tornou-se independente em 1828; o país sediou e venceu a primeira Copa do Mundo de futebol, em 1930.",
         aliases=["República Oriental do Uruguai"]),
    pais("mundo_venezuela", "Venezuela",
         "Venezuela é um país do norte da América do Sul, banhado pelo Mar do Caribe, que faz fronteira com o Brasil, a Colômbia e a Guiana.",
         "A capital da Venezuela é Caracas.",
         "O idioma oficial da Venezuela é o espanhol, e a moeda é o bolívar.",
         "A Venezuela tem cerca de 30 milhões de habitantes e cerca de 912 mil km²; possui as maiores reservas comprovadas de petróleo do mundo.",
         "Na Venezuela fica o Salto Ángel, a cachoeira mais alta do mundo, com cerca de 980 metros; Simón Bolívar, líder das independências sul-americanas, nasceu em Caracas.",
         aliases=["República Bolivariana da Venezuela"]),
    # América do Norte e Caribe
    pais("mundo_estados_unidos", "Estados Unidos",
         "Os Estados Unidos são um país da América do Norte formado por 50 estados e um distrito federal, situado entre o Canadá e o México, com litoral no Atlântico e no Pacífico.",
         "A capital dos Estados Unidos é Washington, D.C.",
         "O inglês é o idioma predominante dos Estados Unidos, declarado oficial por ordem executiva em 2025; a moeda é o dólar americano.",
         "Os Estados Unidos têm cerca de 340 milhões de habitantes, a terceira maior população do mundo, e cerca de 9,8 milhões de km², estando entre os quatro maiores países em área.",
         "Os Estados Unidos declararam independência do Reino Unido em 4 de julho de 1776, e sua Constituição, de 1787, é a constituição escrita nacional mais antiga ainda em vigor.",
         aliases=["EUA", "Estados Unidos da América", "USA"]),
    pais("mundo_canada", "Canadá",
         "Canadá é um país do norte da América do Norte, que se estende do Atlântico ao Pacífico e ao Oceano Ártico e faz fronteira com os Estados Unidos.",
         "A capital do Canadá é Ottawa.",
         "Os idiomas oficiais do Canadá são o inglês e o francês, e a moeda é o dólar canadense.",
         "O Canadá tem cerca de 40 milhões de habitantes e cerca de 9,98 milhões de km², sendo o segundo maior país do mundo em área, atrás apenas da Rússia; tem o litoral mais extenso do mundo.",
         "O Canadá é uma monarquia constitucional e federação de 10 províncias e 3 territórios, cujo chefe de Estado é o monarca britânico; a província de Quebec tem maioria de língua francesa.",
         aliases=["Canada"]),
    pais("mundo_mexico", "México",
         "México é um país da América do Norte, que faz fronteira com os Estados Unidos ao norte e com a Guatemala e Belize ao sul, banhado pelo Pacífico e pelo Golfo do México.",
         "A capital do México é a Cidade do México.",
         "O espanhol é o idioma predominante do México, que também reconhece dezenas de línguas indígenas como nacionais; a moeda é o peso mexicano.",
         "O México tem cerca de 130 milhões de habitantes, o país de língua espanhola mais populoso do mundo, e cerca de 1,96 milhão de km².",
         "No território do México floresceram as civilizações maia e asteca; a capital asteca, Tenochtitlán, deu origem à Cidade do México, e a independência da Espanha foi consumada em 1821.",
         aliases=["Estados Unidos Mexicanos", "Mexico"]),
    pais("mundo_cuba", "Cuba",
         "Cuba é um país insular do Caribe, formado pela maior ilha das Antilhas e ilhas menores, situado ao sul dos Estados Unidos.",
         "A capital de Cuba é Havana.",
         "O idioma oficial de Cuba é o espanhol, e a moeda é o peso cubano.",
         "Cuba tem cerca de 11 milhões de habitantes e cerca de 110 mil km².",
         "A Revolução Cubana, liderada por Fidel Castro, tomou o poder em 1959; desde então, Cuba é um Estado socialista de partido único e sofre embargo econômico dos Estados Unidos.",
         aliases=["República de Cuba"]),
    # Europa
    pais("mundo_portugal", "Portugal",
         "Portugal é um país do sudoeste da Europa, no oeste da Península Ibérica, que faz fronteira apenas com a Espanha e inclui os arquipélagos dos Açores e da Madeira.",
         "A capital de Portugal é Lisboa.",
         "O idioma oficial de Portugal é o português, e a moeda é o euro.",
         "Portugal tem cerca de 10,5 milhões de habitantes e cerca de 92 mil km².",
         "Portugal liderou as Grandes Navegações: Vasco da Gama chegou à Índia por mar em 1498 e Pedro Álvares Cabral chegou ao Brasil em 1500; a Revolução dos Cravos, em 1974, encerrou a ditadura do Estado Novo.",
         aliases=["República Portuguesa"]),
    pais("mundo_espanha", "Espanha",
         "Espanha é um país do sudoeste da Europa que ocupa a maior parte da Península Ibérica e inclui as ilhas Baleares e Canárias.",
         "A capital da Espanha é Madri.",
         "O idioma oficial da Espanha é o espanhol (castelhano), com catalão, galego e basco cooficiais em suas regiões; a moeda é o euro.",
         "A Espanha tem cerca de 48 milhões de habitantes e cerca de 506 mil km².",
         "Em 1492, a Espanha concluiu a Reconquista com a tomada de Granada e financiou a viagem de Cristóvão Colombo à América; hoje é uma monarquia parlamentar.",
         aliases=["Reino da Espanha", "Reino de Espanha"]),
    pais("mundo_franca", "França",
         "França é um país da Europa Ocidental, banhado pelo Atlântico e pelo Mediterrâneo, que também possui territórios ultramarinos, como a Guiana Francesa, vizinha do Brasil.",
         "A capital da França é Paris.",
         "O idioma oficial da França é o francês, e a moeda é o euro.",
         "A França tem cerca de 68 milhões de habitantes e cerca de 644 mil km² contando os territórios ultramarinos; é o maior país da União Europeia em área e um dos mais visitados do mundo.",
         "A Revolução Francesa, iniciada em 1789, derrubou a monarquia absoluta e difundiu os ideais de liberdade, igualdade e fraternidade.",
         aliases=["República Francesa", "Franca"]),
    pais("mundo_italia", "Itália",
         "Itália é um país do sul da Europa formado por uma península em forma de bota no Mediterrâneo e pelas ilhas da Sicília e da Sardenha.",
         "A capital da Itália é Roma.",
         "O idioma oficial da Itália é o italiano, e a moeda é o euro.",
         "A Itália tem cerca de 59 milhões de habitantes e cerca de 301 mil km²; dentro de seu território ficam dois países independentes, o Vaticano e San Marino.",
         "A Itália foi o berço do Renascimento, nos séculos XIV a XVI, e só se unificou como país em 1861.",
         aliases=["República Italiana", "Italia"]),
    pais("mundo_alemanha", "Alemanha",
         "Alemanha é um país da Europa Central, banhado pelo Mar do Norte e pelo Mar Báltico, formado por 16 estados federados.",
         "A capital da Alemanha é Berlim.",
         "O idioma oficial da Alemanha é o alemão, e a moeda é o euro.",
         "A Alemanha tem cerca de 84 milhões de habitantes, o país mais populoso da União Europeia, e cerca de 357 mil km²; tem a maior economia da Europa.",
         "Dividida após a Segunda Guerra Mundial, a Alemanha foi reunificada em 3 de outubro de 1990, menos de um ano após a queda do Muro de Berlim.",
         aliases=["República Federal da Alemanha", "RFA"]),
    pais("mundo_reino_unido", "Reino Unido",
         "Reino Unido é um país do noroeste da Europa formado por Inglaterra, Escócia, País de Gales e Irlanda do Norte, ocupando a ilha da Grã-Bretanha e o nordeste da ilha da Irlanda.",
         "A capital do Reino Unido é Londres.",
         "O inglês é o idioma predominante do Reino Unido, e a moeda é a libra esterlina.",
         "O Reino Unido tem cerca de 69 milhões de habitantes e cerca de 244 mil km².",
         "O Reino Unido é uma monarquia constitucional onde começou a Revolução Industrial, no século XVIII; deixou a União Europeia em 31 de janeiro de 2020, no processo conhecido como Brexit.",
         aliases=["Reino Unido da Grã-Bretanha e Irlanda do Norte", "Grã-Bretanha", "UK"]),
    pais("mundo_paises_baixos", "Países Baixos",
         "Os Países Baixos são um país do noroeste da Europa, banhado pelo Mar do Norte, entre a Bélgica e a Alemanha, popularmente chamado de Holanda.",
         "A capital dos Países Baixos é Amsterdã; a sede do governo e do parlamento fica em Haia.",
         "O idioma oficial dos Países Baixos é o neerlandês, e a moeda é o euro.",
         "Os Países Baixos têm cerca de 18 milhões de habitantes e cerca de 41,5 mil km²; cerca de um quarto do território fica abaixo do nível do mar, protegido por diques.",
         "No século XVII, os Países Baixos foram uma grande potência comercial e ocuparam parte do Nordeste brasileiro, com centro em Recife, entre 1630 e 1654.",
         aliases=["Holanda", "Reino dos Países Baixos"]),
    pais("mundo_suica", "Suíça",
         "Suíça é um país da Europa Central, sem saída para o mar, dominado pelos Alpes e que faz fronteira com Alemanha, França, Itália, Áustria e Liechtenstein.",
         "A capital da Suíça é Berna.",
         "A Suíça tem quatro línguas oficiais: alemão, francês, italiano e romanche; a moeda é o franco suíço.",
         "A Suíça tem cerca de 9 milhões de habitantes e cerca de 41 mil km².",
         "A Suíça mantém neutralidade internacional desde 1815, pratica democracia direta com referendos frequentes e abriga em Genebra sedes da ONU e da Cruz Vermelha.",
         aliases=["Confederação Suíça", "Suica"]),
    pais("mundo_grecia", "Grécia",
         "Grécia é um país do sudeste da Europa, no sul da Península Balcânica, com milhares de ilhas nos mares Egeu, Jônico e Mediterrâneo.",
         "A capital da Grécia é Atenas.",
         "O idioma oficial da Grécia é o grego, e a moeda é o euro.",
         "A Grécia tem cerca de 10,4 milhões de habitantes e cerca de 132 mil km²; tem mais de 6 mil ilhas, das quais pouco mais de 200 são habitadas.",
         "A Grécia moderna tornou-se independente do Império Otomano em 1830; a civilização grega antiga é considerada berço da democracia, da filosofia ocidental e dos Jogos Olímpicos.",
         aliases=["República Helênica", "Grecia"]),
    pais("mundo_russia", "Rússia",
         "Rússia é um país que se estende pelo leste da Europa e por todo o norte da Ásia, do Mar Báltico ao Oceano Pacífico.",
         "A capital da Rússia é Moscou.",
         "O idioma oficial da Rússia é o russo, e a moeda é o rublo.",
         "A Rússia é o maior país do mundo em área, com cerca de 17,1 milhões de km² e 11 fusos horários, e tem cerca de 145 milhões de habitantes.",
         "A Revolução Russa de 1917 levou à criação da União Soviética, da qual a Rússia foi a principal república até a dissolução da URSS, em 1991.",
         aliases=["Federação Russa", "Russia"]),
    pais("mundo_ucrania", "Ucrânia",
         "Ucrânia é um país do leste da Europa, banhado pelo Mar Negro, que faz fronteira com a Rússia, a Belarus, a Polônia e outros vizinhos.",
         "A capital da Ucrânia é Kiev (Kyiv).",
         "O idioma oficial da Ucrânia é o ucraniano, e a moeda é a hryvnia.",
         "A Ucrânia tem cerca de 604 mil km², o maior país situado inteiramente na Europa, e uma população estimada em cerca de 35 milhões, número incerto por causa da guerra.",
         "A Ucrânia tornou-se independente com o fim da União Soviética, em 1991; a Rússia anexou a Crimeia em 2014 e iniciou uma invasão em larga escala em 24 de fevereiro de 2022.",
         aliases=["Ucrania"]),
    pais("mundo_turquia", "Turquia",
         "Turquia é um país transcontinental, com a maior parte do território na Ásia (Anatólia) e uma pequena parte na Europa (Trácia), separadas pelo estreito do Bósforo.",
         "A capital da Turquia é Ancara; a maior cidade é Istambul.",
         "O idioma oficial da Turquia é o turco, e a moeda é a lira turca.",
         "A Turquia tem cerca de 85 milhões de habitantes e cerca de 784 mil km².",
         "A República da Turquia foi fundada em 1923 por Mustafa Kemal Atatürk, após o fim do Império Otomano.",
         aliases=["República da Turquia", "Türkiye"]),
    # Ásia
    pais("mundo_china_pais", "China",
         "China é um país do leste da Ásia, governado pelo Partido Comunista, que faz fronteira com 14 países, entre eles Rússia, Índia e Mongólia.",
         "A capital da China é Pequim.",
         "O idioma oficial da China é o chinês mandarim, e a moeda é o renminbi, cuja unidade é o yuan.",
         "A China tem cerca de 1,4 bilhão de habitantes, a segunda maior população do mundo depois da Índia, e cerca de 9,6 milhões de km², estando entre os quatro maiores países em área.",
         "A República Popular da China foi proclamada por Mao Tsé-tung em 1º de outubro de 1949; desde 2010, o país é a segunda maior economia do mundo.",
         aliases=["República Popular da China", "RPC"]),
    pais("mundo_japao", "Japão",
         "Japão é um país insular do leste da Ásia, no Oceano Pacífico, formado por quatro ilhas principais (Honshu, Hokkaido, Kyushu e Shikoku) e milhares de ilhas menores.",
         "A capital do Japão é Tóquio.",
         "O idioma oficial do Japão é o japonês, e a moeda é o iene.",
         "O Japão tem cerca de 123 milhões de habitantes e cerca de 378 mil km²; é uma das maiores economias do mundo e tem uma das populações mais idosas.",
         "O Japão foi atingido por bombas atômicas em Hiroshima e Nagasaki em agosto de 1945; a imigração japonesa para o Brasil começou em 1908, com o navio Kasato Maru.",
         aliases=["Japao", "Nippon"]),
    pais("mundo_coreia_do_sul", "Coreia do Sul",
         "Coreia do Sul é um país do leste da Ásia que ocupa a metade sul da Península Coreana e faz fronteira com a Coreia do Norte.",
         "A capital da Coreia do Sul é Seul.",
         "O idioma oficial da Coreia do Sul é o coreano, escrito com o alfabeto hangul, e a moeda é o won sul-coreano.",
         "A Coreia do Sul tem cerca de 52 milhões de habitantes e cerca de 100 mil km².",
         "A Guerra da Coreia (1950-1953) terminou com um armistício, sem tratado de paz; depois dela, a Coreia do Sul tornou-se uma potência industrial e tecnológica.",
         aliases=["República da Coreia"]),
    pais("mundo_india", "Índia",
         "Índia é um país do sul da Ásia, que ocupa a maior parte do subcontinente indiano, entre o Himalaia e o Oceano Índico.",
         "A capital da Índia é Nova Délhi.",
         "Os idiomas oficiais do governo da Índia são o hindi e o inglês, e a Constituição reconhece 22 línguas; a moeda é a rupia indiana.",
         "A Índia é o país mais populoso do mundo desde 2023, com cerca de 1,4 bilhão de habitantes, e tem cerca de 3,3 milhões de km², o sétimo maior em área.",
         "A Índia tornou-se independente do Reino Unido em 15 de agosto de 1947, após um movimento em que se destacou Mahatma Gandhi; é considerada a maior democracia do mundo.",
         aliases=["República da Índia", "India"]),
    pais("mundo_indonesia", "Indonésia",
         "Indonésia é um país do Sudeste Asiático formado pelo maior arquipélago do mundo, com mais de 17 mil ilhas entre os oceanos Índico e Pacífico.",
         "A capital da Indonésia é Jacarta, na ilha de Java; o país constrói uma nova capital, Nusantara, na ilha de Bornéu.",
         "O idioma oficial da Indonésia é o indonésio, e a moeda é a rupia indonésia.",
         "A Indonésia tem cerca de 280 milhões de habitantes, a quarta maior população do mundo e a maior população muçulmana, e cerca de 1,9 milhão de km².",
         "A Indonésia proclamou independência dos Países Baixos em 1945.",
         aliases=["República da Indonésia", "Indonesia"]),
    pais("mundo_israel", "Israel",
         "Israel é um país do Oriente Médio, na costa leste do Mar Mediterrâneo, que faz fronteira com Líbano, Síria, Jordânia e Egito.",
         "A capital de Israel, segundo o governo israelense, é Jerusalém; o status da cidade é disputado, e a maioria dos países mantém embaixadas em Tel Aviv.",
         "O idioma oficial de Israel é o hebraico, e o árabe tem status especial; a moeda é o novo shekel.",
         "Israel tem cerca de 10 milhões de habitantes e cerca de 22 mil km².",
         "O Estado de Israel foi proclamado em 14 de maio de 1948; sua criação e as guerras seguintes estão no centro do conflito israelo-palestino.",
         aliases=["Estado de Israel"]),
    pais("mundo_ira", "Irã",
         "Irã é um país do Oriente Médio, entre o Mar Cáspio e o Golfo Pérsico, governado como república islâmica.",
         "A capital do Irã é Teerã.",
         "O idioma oficial do Irã é o persa (farsi), e a moeda é o rial iraniano.",
         "O Irã tem cerca de 90 milhões de habitantes e cerca de 1,65 milhão de km²; possui algumas das maiores reservas de petróleo e gás natural do mundo.",
         "O Irã era conhecido internacionalmente como Pérsia até 1935; a Revolução Islâmica de 1979, liderada pelo aiatolá Khomeini, derrubou a monarquia do xá.",
         aliases=["República Islâmica do Irã", "Irão"]),
    pais("mundo_arabia_saudita", "Arábia Saudita",
         "Arábia Saudita é um país do Oriente Médio que ocupa a maior parte da Península Arábica, entre o Mar Vermelho e o Golfo Pérsico.",
         "A capital da Arábia Saudita é Riad.",
         "O idioma oficial da Arábia Saudita é o árabe, e a moeda é o rial saudita.",
         "A Arábia Saudita tem cerca de 35 milhões de habitantes e cerca de 2,15 milhões de km²; está entre os maiores produtores e exportadores de petróleo do mundo.",
         "A Arábia Saudita é uma monarquia absoluta fundada em 1932 e abriga Meca e Medina, as duas cidades mais sagradas do islã.",
         aliases=["Reino da Arábia Saudita", "Arabia Saudita"]),
    # África
    pais("mundo_egito", "Egito",
         "Egito é um país que fica no nordeste da África, atravessado pelo rio Nilo, que também inclui a Península do Sinai, na Ásia.",
         "A capital do Egito é o Cairo.",
         "O idioma oficial do Egito é o árabe, e a moeda é a libra egípcia.",
         "O Egito tem cerca de 110 milhões de habitantes e cerca de 1 milhão de km²; a grande maioria da população vive perto do Nilo, já que quase todo o resto do território é deserto.",
         "O Canal de Suez, inaugurado no Egito em 1869, liga o Mar Mediterrâneo ao Mar Vermelho; as pirâmides de Gizé, da época dos faraós, ficam perto do Cairo.",
         aliases=["República Árabe do Egito"]),
    pais("mundo_africa_do_sul", "África do Sul",
         "África do Sul é o país mais ao sul do continente africano, banhado pelos oceanos Atlântico e Índico.",
         "A capital da África do Sul é Pretória, sede do Poder Executivo; Cidade do Cabo é a capital legislativa e Bloemfontein, a judiciária.",
         "A África do Sul tem 12 idiomas oficiais, entre eles zulu, xhosa, africâner e inglês; a moeda é o rand.",
         "A África do Sul tem cerca de 63 milhões de habitantes e cerca de 1,22 milhão de km².",
         "A África do Sul viveu o apartheid, regime de segregação racial, de 1948 até o início dos anos 1990; Nelson Mandela tornou-se seu primeiro presidente negro em 1994.",
         aliases=["República da África do Sul"]),
    pais("mundo_nigeria", "Nigéria",
         "Nigéria é um país da África Ocidental, banhado pelo Golfo da Guiné, no Oceano Atlântico.",
         "A capital da Nigéria é Abuja, que substituiu Lagos em 1991.",
         "O idioma oficial da Nigéria é o inglês, e a moeda é a naira.",
         "A Nigéria é o país mais populoso da África, com cerca de 230 milhões de habitantes, e tem cerca de 924 mil km².",
         "A Nigéria tornou-se independente do Reino Unido em 1960; é grande produtora de petróleo e tem uma das maiores indústrias de cinema do mundo, conhecida como Nollywood.",
         aliases=["República Federal da Nigéria", "Nigeria"]),
    pais("mundo_angola", "Angola",
         "Angola é um país do sudoeste da África, banhado pelo Oceano Atlântico, e um dos países de língua portuguesa.",
         "A capital de Angola é Luanda.",
         "O idioma oficial de Angola é o português, e a moeda é o kwanza.",
         "Angola tem cerca de 37 milhões de habitantes e cerca de 1,25 milhão de km²; é um dos maiores produtores de petróleo da África.",
         "Angola tornou-se independente de Portugal em 11 de novembro de 1975, com reconhecimento imediato do Brasil, e viveu uma guerra civil que durou até 2002.",
         aliases=["República de Angola"]),
    pais("mundo_mocambique", "Moçambique",
         "Moçambique é um país do sudeste da África, com longo litoral no Oceano Índico, e um dos países de língua portuguesa.",
         "A capital de Moçambique é Maputo.",
         "O idioma oficial de Moçambique é o português, e a moeda é o metical.",
         "Moçambique tem cerca de 34 milhões de habitantes e cerca de 800 mil km².",
         "Moçambique tornou-se independente de Portugal em 25 de junho de 1975 e viveu uma guerra civil entre 1977 e 1992.",
         aliases=["República de Moçambique", "Mocambique"]),
    pais("mundo_marrocos", "Marrocos",
         "Marrocos é um país do noroeste da África, banhado pelo Atlântico e pelo Mediterrâneo, separado da Espanha pelo Estreito de Gibraltar.",
         "A capital de Marrocos é Rabat.",
         "Os idiomas oficiais de Marrocos são o árabe e o berbere (amazigh), e a moeda é o dirham marroquino.",
         "Marrocos tem cerca de 37 milhões de habitantes e cerca de 447 mil km², sem contar o Saara Ocidental, território cuja soberania é disputada.",
         "Marrocos é uma monarquia que se tornou independente da França em 1956; na Copa do Mundo de 2022, foi a primeira seleção africana a chegar a uma semifinal.",
         aliases=["Reino de Marrocos"]),
    # Oceania
    pais("mundo_australia", "Austrália",
         "Austrália é um país da Oceania que ocupa todo o território continental australiano, além da Tasmânia e de ilhas menores, entre os oceanos Índico e Pacífico.",
         "A capital da Austrália é Camberra (Canberra).",
         "O inglês é o idioma predominante da Austrália, e a moeda é o dólar australiano.",
         "A Austrália tem cerca de 27 milhões de habitantes e cerca de 7,7 milhões de km², sendo o sexto maior país do mundo em área.",
         "Os povos aborígenes habitam a Austrália há dezenas de milhares de anos; o país tornou-se uma federação em 1901 e abriga a Grande Barreira de Corais, o maior sistema de recifes do mundo.",
         aliases=["Comunidade da Austrália", "Australia"]),
    pais("mundo_nova_zelandia", "Nova Zelândia",
         "Nova Zelândia é um país da Oceania, no sudoeste do Oceano Pacífico, formado principalmente por duas grandes ilhas, a Ilha Norte e a Ilha Sul.",
         "A capital da Nova Zelândia é Wellington.",
         "Os idiomas oficiais da Nova Zelândia são o inglês, o maori e a língua de sinais neozelandesa; a moeda é o dólar neozelandês.",
         "A Nova Zelândia tem cerca de 5,3 milhões de habitantes e cerca de 269 mil km².",
         "A Nova Zelândia foi o primeiro país a conceder às mulheres o direito de votar em eleições nacionais, em 1893; os maori chegaram às ilhas por volta do século XIII.",
         aliases=["Aotearoa", "Nova Zelandia"]),
]

if __name__ == "__main__":
    import sys
    salvar(sys.argv[1], "Fichas próprias sobre países (localização, capital, idioma, moeda, população, área e um marco "
           "histórico), sintetizadas do CIA World Factbook (domínio público) com o IBGE Países como referência. "
           "População e área são aproximações correntes e mudam com novas estimativas.", FONTES, ITENS)
