from comum import conceito, fonte_existente, openstax, referencia, salvar

NOBEL = "nobelprize_laureados"
H1 = "openstax_historia_mundial_v1"
H2 = "openstax_historia_mundial_v2"
BIO = "openstax_biologia_2e"
AN = "arquivo_nacional"
ABL = "academia_brasileira_letras"
FONTES = [
    referencia(NOBEL, "The Nobel Prize — laureates and biographies", "https://www.nobelprize.org/prizes/lists/all-nobel-prizes/",
               "Nobel Prize Outreach", "https://www.nobelprize.org/terms-of-use"),
    openstax(H1, "World History Volume 1: to 1500", "world-history-volume-1",
             "OpenStax, Rice University; Ann Kordas, Ryan J. Lynch, Brooke Nelson, Julie Tatlock"),
    openstax(H2, "World History Volume 2: from 1400", "world-history-volume-2",
             "OpenStax, Rice University; Ann Kordas, Ryan J. Lynch, Brooke Nelson, Julie Tatlock"),
    fonte_existente(BIO),
    referencia(AN, "Arquivo Nacional — acervo e história do Brasil", "https://www.gov.br/arquivonacional/pt-br",
               "Arquivo Nacional (Brasil)", "https://www.gov.br/pt-br/termos-de-uso"),
    referencia(ABL, "Academia Brasileira de Letras — acadêmicos e patronos", "https://www.academia.org.br/",
               "Academia Brasileira de Letras", "https://www.academia.org.br/"),
]
S = "social"
A = "pessoas"


def pessoa(ident, nome, fonte, definicao, *detalhes, aliases=()):
    return conceito(ident, nome, A, fonte, S, definicao, *detalhes, aliases=aliases)


ITENS = [
    pessoa("mundo_socrates", "Sócrates", H1,
           "Sócrates (c. 470–399 a.C.) foi um filósofo de Atenas considerado um dos fundadores da filosofia ocidental.",
           "Não deixou escritos; suas ideias são conhecidas principalmente pelos diálogos de seu discípulo Platão.",
           "Ficou conhecido pelo método de fazer perguntas para examinar crenças, e pela frase atribuída a ele: 'só sei que nada sei'.",
           "Foi condenado à morte por um tribunal ateniense, acusado de impiedade e de corromper a juventude."),
    pessoa("mundo_platao", "Platão", H1,
           "Platão (c. 428–348 a.C.) foi um filósofo grego, discípulo de Sócrates e mestre de Aristóteles.",
           "Fundou a Academia, em Atenas, uma das primeiras instituições de ensino superior do Ocidente.",
           "Em obras como A República, discutiu justiça, conhecimento e a teoria das formas."),
    pessoa("mundo_aristoteles", "Aristóteles", H1,
           "Aristóteles (384–322 a.C.) foi um filósofo grego que escreveu sobre lógica, ética, política, biologia e poética.",
           "Foi aluno de Platão e preceptor de Alexandre, o Grande.",
           "Sistematizou a lógica dedutiva com o silogismo, que dominou o estudo da lógica por cerca de dois mil anos."),
    pessoa("mundo_confucio", "Confúcio", H1,
           "Confúcio (551–479 a.C.) foi um pensador chinês cujos ensinamentos sobre ética e governo originaram o confucionismo.",
           "Valorizava a educação, o respeito às relações familiares e a virtude dos governantes.",
           "Seus ensinamentos foram reunidos por discípulos nos Analectos e moldaram a burocracia imperial chinesa por séculos."),
    pessoa("mundo_buda", "Siddhartha Gautama", H1,
           "Siddhartha Gautama, o Buda, foi um mestre espiritual do norte da Índia, que viveu por volta dos séculos VI–V a.C., fundador do budismo.",
           "Segundo a tradição, era um príncipe que abandonou o palácio ao conhecer o sofrimento humano e alcançou a iluminação após meditar.",
           "Ensinou as Quatro Nobres Verdades e o Caminho Óctuplo como meio de superar o sofrimento.",
           aliases=["Buda", "Buddha"]),
    pessoa("mundo_alexandre_magno", "Alexandre Magno", H1,
           "Alexandre, o Grande (356–323 a.C.) foi rei da Macedônia e conquistou um império que ia da Grécia ao noroeste da Índia.",
           "Suas conquistas difundiram a língua e a cultura gregas, dando início ao período helenístico.",
           "Fundou várias cidades, como Alexandria, no Egito, que se tornou um grande centro de saber.",
           aliases=["Alexandre, o Grande", "Alexandre o Grande"]),
    pessoa("mundo_julio_cesar", "Júlio César", H1,
           "Júlio César (100–44 a.C.) foi um general e político romano cuja ascensão contribuiu para o fim da República Romana.",
           "Conquistou a Gália e, em 49 a.C., cruzou o rio Rubicão com suas tropas, iniciando uma guerra civil.",
           "Foi assassinado por senadores em 15 de março de 44 a.C.; seu herdeiro, Otaviano, tornou-se o imperador Augusto."),
    pessoa("mundo_leonardo_da_vinci", "Leonardo da Vinci", H2,
           "Leonardo da Vinci (1452–1519) foi um pintor, inventor e estudioso italiano do Renascimento.",
           "Pintou a Mona Lisa e A Última Ceia.",
           "Seus cadernos reúnem estudos de anatomia, engenharia, voo e óptica, muitos à frente de seu tempo."),
    pessoa("mundo_michelangelo", "Michelangelo", H2,
           "Michelangelo Buonarroti (1475–1564) foi um escultor, pintor e arquiteto italiano do Renascimento.",
           "Esculpiu o Davi e a Pietà e pintou o teto da Capela Sistina, no Vaticano."),
    pessoa("mundo_galileu", "Galileu Galilei", H2,
           "Galileu Galilei (1564–1642) foi um astrônomo, físico e matemático italiano, figura central da Revolução Científica.",
           "Com um telescópio aperfeiçoado por ele, observou as luas de Júpiter, as fases de Vênus e as montanhas da Lua.",
           "Defendeu o heliocentrismo e foi condenado pela Inquisição em 1633, vivendo seus últimos anos em prisão domiciliar.",
           aliases=["Galileu"]),
    pessoa("mundo_isaac_newton", "Isaac Newton", H2,
           "Isaac Newton (1643–1727) foi um físico e matemático inglês que formulou as leis do movimento e a gravitação universal.",
           "Publicou os Principia em 1687.",
           "Desenvolveu o cálculo, de forma independente de Leibniz, e fez estudos fundamentais sobre a luz e as cores.",
           aliases=["Newton"]),
    pessoa("mundo_charles_darwin", "Charles Darwin", BIO,
           "Charles Darwin (1809–1882) foi um naturalista inglês que propôs a teoria da evolução por seleção natural.",
           "A viagem no navio Beagle, incluindo as Ilhas Galápagos, forneceu observações importantes para suas ideias.",
           "Publicou A Origem das Espécies em 1859; Alfred Russel Wallace chegou a conclusões semelhantes de forma independente.",
           aliases=["Darwin"]),
    pessoa("mundo_gregor_mendel", "Gregor Mendel", BIO,
           "Gregor Mendel (1822–1884) foi um monge e cientista da Morávia, considerado o pai da genética.",
           "Cruzando ervilhas, descobriu padrões regulares de herança de características, hoje conhecidos como leis de Mendel.",
           "Seu trabalho, publicado em 1866, só foi reconhecido por volta de 1900.",
           aliases=["Mendel"]),
    pessoa("mundo_marie_curie", "Marie Curie", NOBEL,
           "Marie Curie (1867–1934) foi uma física e química polonesa naturalizada francesa, pioneira no estudo da radioatividade.",
           "Foi a primeira mulher a ganhar um Nobel e a única pessoa premiada em duas ciências diferentes: Física (1903) e Química (1911).",
           "Descobriu, com Pierre Curie, os elementos polônio e rádio.",
           aliases=["Madame Curie", "Maria Skłodowska-Curie"]),
    pessoa("mundo_albert_einstein", "Albert Einstein", NOBEL,
           "Albert Einstein (1879–1955) foi um físico de origem alemã que formulou as teorias da relatividade restrita e geral.",
           "Recebeu o Nobel de Física de 1921 pela explicação do efeito fotoelétrico, não pela relatividade.",
           "Em 1919, observações de um eclipse feitas em Sobral, no Ceará, e na ilha de Príncipe ajudaram a confirmar a relatividade geral.",
           "Deixou a Alemanha com a ascensão do nazismo e viveu nos Estados Unidos a partir de 1933.",
           aliases=["Einstein"]),
    pessoa("mundo_ada_lovelace", "Ada Lovelace", H2,
           "Ada Lovelace (1815–1852) foi uma matemática inglesa considerada uma das primeiras pessoas a escrever um algoritmo para uma máquina.",
           "Trabalhou nas notas sobre a Máquina Analítica, projetada por Charles Babbage.",
           "Previu que máquinas assim poderiam manipular símbolos em geral, não só números."),
    pessoa("mundo_alan_turing", "Alan Turing", H2,
           "Alan Turing (1912–1954) foi um matemático britânico, pioneiro da computação e da inteligência artificial.",
           "Formulou a máquina de Turing, modelo teórico do que pode ser computado.",
           "Na Segunda Guerra, contribuiu para decifrar a máquina alemã Enigma, em Bletchley Park.",
           "Foi condenado em 1952 por sua homossexualidade; recebeu perdão póstumo do governo britânico em 2013."),
    pessoa("mundo_mahatma_gandhi", "Mahatma Gandhi", H2,
           "Mohandas Gandhi (1869–1948), chamado de Mahatma, liderou o movimento pela independência da Índia com resistência não violenta.",
           "A Marcha do Sal, em 1930, protestou contra o monopólio britânico do sal.",
           "Foi assassinado em 1948, poucos meses depois da independência.",
           aliases=["Gandhi"]),
    pessoa("mundo_nelson_mandela", "Nelson Mandela", NOBEL,
           "Nelson Mandela (1918–2013) foi um líder sul-africano da luta contra o apartheid e o primeiro presidente negro da África do Sul.",
           "Ficou preso por 27 anos, de 1962 a 1990.",
           "Recebeu o Nobel da Paz em 1993, com Frederik de Klerk, e governou de 1994 a 1999.",
           aliases=["Mandela"]),
    pessoa("mundo_martin_luther_king", "Martin Luther King Jr.", NOBEL,
           "Martin Luther King Jr. (1929–1968) foi um pastor e líder do movimento pelos direitos civis dos negros nos Estados Unidos.",
           "Defendia a desobediência civil não violenta e fez o discurso 'Eu tenho um sonho' em 1963, em Washington.",
           "Recebeu o Nobel da Paz em 1964 e foi assassinado em 1968.",
           aliases=["Martin Luther King"]),
    pessoa("mundo_malala", "Malala Yousafzai", NOBEL,
           "Malala Yousafzai (nascida em 1997) é uma ativista paquistanesa pelo direito das meninas à educação.",
           "Sobreviveu a um atentado do Talibã em 2012.",
           "Em 2014, aos 17 anos, tornou-se a pessoa mais jovem a receber o Nobel da Paz.",
           aliases=["Malala"]),
    pessoa("mundo_zumbi_dos_palmares", "Zumbi dos Palmares", AN,
           "Zumbi dos Palmares (c. 1655–1695) foi o último líder do Quilombo dos Palmares, símbolo da resistência negra à escravidão no Brasil.",
           "Foi morto em 20 de novembro de 1695, data que se tornou o Dia Nacional de Zumbi e da Consciência Negra.",
           aliases=["Zumbi"]),
    pessoa("mundo_tiradentes", "Tiradentes", AN,
           "Joaquim José da Silva Xavier, o Tiradentes (1746–1792), foi um dos participantes da Inconfidência Mineira, conspiração contra o domínio português.",
           "Foi o único condenado à morte entre os inconfidentes e executado em 21 de abril de 1792, no Rio de Janeiro.",
           "Na República, foi transformado em herói nacional; 21 de abril é feriado.",
           aliases=["Joaquim José da Silva Xavier"]),
    pessoa("mundo_dom_pedro_ii", "D. Pedro II", AN,
           "D. Pedro II (1825–1891) foi o segundo e último imperador do Brasil, reinando de 1840 a 1889.",
           "Assumiu o trono aos 14 anos, com a antecipação de sua maioridade.",
           "Interessava-se por ciências e artes; foi deposto pela Proclamação da República e morreu exilado em Paris.",
           aliases=["Pedro II", "Dom Pedro II"]),
    pessoa("mundo_princesa_isabel", "Princesa Isabel", AN,
           "Isabel de Bragança (1846–1921), a Princesa Isabel, foi herdeira do trono brasileiro e assinou a Lei Áurea em 1888, como regente.",
           "Também assinou a Lei do Ventre Livre, em 1871.",
           "A abolição resultou de longa luta de abolicionistas e de pessoas escravizadas, não de um ato isolado.",
           aliases=["Isabel de Bragança"]),
    pessoa("mundo_luiz_gama", "Luiz Gama", AN,
           "Luiz Gama (1830–1882) foi um advogado autodidata, jornalista e poeta abolicionista brasileiro.",
           "Nascido livre, foi vendido ilegalmente como escravizado pelo próprio pai; conquistou a liberdade e aprendeu Direito por conta própria.",
           "Atuando nos tribunais, ajudou a libertar centenas de pessoas escravizadas."),
    pessoa("mundo_santos_dumont", "Santos Dumont", AN,
           "Alberto Santos Dumont (1873–1932) foi um inventor e aviador brasileiro, pioneiro da aviação.",
           "Em 1906, em Paris, voou com o 14-Bis numa demonstração pública homologada, considerada por muitos o primeiro voo de um avião que decolou por meios próprios.",
           "Os irmãos Wright haviam voado em 1903, nos Estados Unidos; a primazia é debatida por critérios como decolagem sem catapulta e testemunhas.",
           aliases=["Alberto Santos Dumont"]),
    pessoa("mundo_oswaldo_cruz", "Oswaldo Cruz", AN,
           "Oswaldo Cruz (1872–1917) foi um médico sanitarista brasileiro, pioneiro da saúde pública no país.",
           "Comandou campanhas contra a febre amarela, a peste e a varíola no Rio de Janeiro no início do século XX.",
           "A vacinação obrigatória contra a varíola provocou a Revolta da Vacina, em 1904."),
    pessoa("mundo_carlos_chagas", "Carlos Chagas", AN,
           "Carlos Chagas (1879–1934) foi um médico e cientista brasileiro que descreveu a doença de Chagas em 1909.",
           "Identificou o agente causador, o protozoário Trypanosoma cruzi, seu transmissor, o barbeiro, e o quadro clínico — feito raro para um único pesquisador."),
    pessoa("mundo_chico_mendes", "Chico Mendes", AN,
           "Chico Mendes (1944–1988) foi um seringueiro e ativista ambiental do Acre que lutou pela preservação da Amazônia e pelos povos da floresta.",
           "Defendeu a criação de reservas extrativistas.",
           "Foi assassinado em 1988 a mando de um fazendeiro, o que deu repercussão internacional à sua luta."),
    pessoa("mundo_machado_de_assis", "Machado de Assis", ABL,
           "Machado de Assis (1839–1908) foi um escritor brasileiro, considerado um dos maiores da literatura em língua portuguesa.",
           "Neto de escravizados libertos, de origem pobre, foi o primeiro presidente da Academia Brasileira de Letras, fundada em 1897.",
           "Escreveu Memórias Póstumas de Brás Cubas, Dom Casmurro e Quincas Borba, marcados por ironia e análise psicológica."),
    pessoa("mundo_clarice_lispector", "Clarice Lispector", ABL,
           "Clarice Lispector (1920–1977) foi uma escritora brasileira nascida na Ucrânia, conhecida por uma prosa introspectiva e inovadora.",
           "Chegou ao Brasil ainda bebê, com a família que fugia de perseguições.",
           "Entre suas obras estão Perto do Coração Selvagem, A Paixão Segundo G.H. e A Hora da Estrela."),
    pessoa("mundo_carolina_maria_de_jesus", "Carolina Maria de Jesus", ABL,
           "Carolina Maria de Jesus (1914–1977) foi uma escritora brasileira, autora de Quarto de Despejo: Diário de uma Favelada (1960).",
           "Escrevia em cadernos recolhidos no lixo enquanto trabalhava como catadora na favela do Canindé, em São Paulo.",
           "O livro vendeu muito, foi traduzido para mais de uma dezena de línguas e deu voz à vida nas periferias."),
    pessoa("mundo_shakespeare", "William Shakespeare", H2,
           "William Shakespeare (1564–1616) foi um dramaturgo e poeta inglês, considerado um dos maiores escritores da língua inglesa.",
           "Escreveu tragédias como Hamlet, Romeu e Julieta, Otelo e Macbeth, além de comédias e sonetos.",
           aliases=["Shakespeare"]),
    pessoa("mundo_cervantes", "Miguel de Cervantes", H2,
           "Miguel de Cervantes (1547–1616) foi um escritor espanhol, autor de Dom Quixote de la Mancha.",
           "Dom Quixote, publicado em duas partes (1605 e 1615), é frequentemente apontado como o primeiro romance moderno.",
           aliases=["Cervantes"]),
    pessoa("mundo_frida_kahlo", "Frida Kahlo", H2,
           "Frida Kahlo (1907–1954) foi uma pintora mexicana conhecida por autorretratos que exploram dor, identidade e cultura mexicana.",
           "Um grave acidente de ônibus na juventude deixou sequelas que marcaram sua vida e sua obra."),
    pessoa("mundo_tarsila_do_amaral", "Tarsila do Amaral", ABL,
           "Tarsila do Amaral (1886–1973) foi uma pintora brasileira, figura central do modernismo.",
           "Pintou Abaporu (1928), que inspirou o Manifesto Antropófago de Oswald de Andrade.",
           "Outras obras conhecidas são Operários e A Negra."),
    pessoa("mundo_villa_lobos", "Heitor Villa-Lobos", ABL,
           "Heitor Villa-Lobos (1887–1959) foi um compositor brasileiro que uniu música erudita e elementos da música popular e folclórica.",
           "Compôs as Bachianas Brasileiras e os Choros, e participou da Semana de Arte Moderna de 1922.",
           aliases=["Villa-Lobos"]),
]

if __name__ == "__main__":
    import sys
    salvar(sys.argv[1], "Biografias curtas, em síntese própria, de pessoas de grande relevância histórica, científica e "
           "cultural, com fontes institucionais e manuais abertos. Datas seguem referências correntes; aspectos "
           "debatidos são indicados como tais.", FONTES, ITENS)
