from comum import conceito, openstax, referencia, salvar

AP = "sb_openstax_anatomia_fisiologia_2e"
MI = "sb_openstax_microbiologia"
MS = "sb_ministerio_saude"
OMS = "sb_oms"
FC = "sb_fiocruz"
FONTES = [
    openstax(AP, "Anatomy and Physiology 2e", "anatomy-and-physiology-2e",
             "OpenStax, Rice University; J. Gordon Betts, Kelly A. Young, James A. Wise et al."),
    openstax(MI, "Microbiology", "microbiology",
             "OpenStax, Rice University; Nina Parker, Mark Schneegurt, Anh-Hue Thi Tu, Philip Lister, Brian M. Forster"),
    referencia(MS, "Ministério da Saúde — saúde de A a Z", "https://www.gov.br/saude/pt-br",
               "Ministério da Saúde (Brasil)", "https://www.gov.br/pt-br/termos-de-uso"),
    referencia(OMS, "Organização Mundial da Saúde — fichas informativas", "https://www.who.int/",
               "Organização Mundial da Saúde (OMS)", "https://www.who.int/about/policies/publishing/copyright"),
    referencia(FC, "Fiocruz — portal institucional", "https://portal.fiocruz.br/",
               "Fundação Oswaldo Cruz (Fiocruz)", "https://www.gov.br/pt-br/termos-de-uso"),
]
A = "saude"
C = "cientifico"
O = "orientacao"


def ficha(ident, nome, fonte, definicao, *detalhes, aliases=(), orientacao=(), fontes=None, papeis=None):
    """Como `conceito`, mas os detalhes de índice em `orientacao` (contados a
    partir do primeiro detalhe) recebem natureza "orientacao", e `fontes`
    permite trocar a fonte de um detalhe."""
    item = conceito(ident, nome, A, fonte, C, definicao, *detalhes, aliases=aliases, papeis=papeis)
    for i in orientacao:
        item["fatos"][i + 1]["natureza"] = O
    for i, f in (fontes or {}).items():
        item["fatos"][i + 1]["fonte"] = f
    return item


ITENS = [
    ficha("mundo_cancer", "câncer", AP,
          "Câncer é o nome dado a um conjunto de doenças em que células do corpo passam a se multiplicar de forma descontrolada e podem invadir tecidos vizinhos e se espalhar para outros órgãos (metástase).",
          "O câncer surge de alterações no DNA das células, que podem ser causadas por fatores como tabaco, álcool, radiação ultravioleta, alguns vírus (como o HPV), obesidade e envelhecimento, além de predisposição hereditária.",
          "Os sintomas do câncer variam conforme o órgão afetado; sinais de alerta comuns incluem nódulos ou caroços, perda de peso sem explicação, sangramentos anormais, feridas que não cicatrizam e tosse ou rouquidão persistentes.",
          "O tratamento do câncer pode combinar cirurgia, quimioterapia, radioterapia, imunoterapia e terapias-alvo; quanto mais cedo o diagnóstico, maiores as chances de cura.",
          "Para reduzir o risco de câncer, recomenda-se não fumar, evitar álcool, proteger-se do sol, manter peso saudável, vacinar-se contra HPV e hepatite B e fazer os exames de rastreamento indicados, como o preventivo do colo do útero.",
          "Sinais persistentes por mais de algumas semanas, como caroço, sangramento sem causa ou emagrecimento inexplicado, devem ser avaliados por um profissional de saúde.",
          aliases=["neoplasia maligna", "tumor maligno", "cancro"], orientacao=(3, 4), fontes={3: MS, 4: MS}),
    ficha("mundo_gripe", "gripe", MI,
          "Gripe, ou influenza, é uma infecção respiratória aguda causada pelos vírus influenza, transmitida por gotículas e aerossóis de tosse, espirro e fala, e por mãos e objetos contaminados.",
          "Os sintomas da gripe costumam começar de repente: febre, dor no corpo, dor de cabeça, cansaço, tosse seca e dor de garganta; em geral melhora em cerca de uma semana.",
          "A gripe pode se complicar com pneumonia, sobretudo em idosos, gestantes, crianças pequenas e pessoas com doenças crônicas.",
          "A principal prevenção contra a gripe é a vacina anual, oferecida pelo SUS em campanhas para grupos prioritários, porque os vírus influenza mudam com frequência; lavar as mãos e cobrir a boca ao tossir também ajudam.",
          "Na gripe, recomenda-se repouso, boa hidratação e antitérmicos se necessário; antibióticos não tratam gripe. Procure atendimento se houver falta de ar, dor no peito, febre que não cede ou piora após alguns dias.",
          aliases=["influenza", "vírus da gripe"], orientacao=(2, 3), fontes={2: MS, 3: MS}),
    ficha("mundo_resfriado_comum", "resfriado comum", MI,
          "Resfriado comum é uma infecção leve das vias aéreas superiores causada por diversos vírus, principalmente os rinovírus.",
          "Os sintomas do resfriado comum são nariz entupido ou escorrendo, espirros, dor de garganta e tosse leve; febre, quando ocorre, é baixa.",
          "O resfriado comum costuma ser mais brando que a gripe e se resolve sozinho em cerca de 7 a 10 dias.",
          "Não há vacina nem antiviral específico para o resfriado comum; o cuidado é aliviar sintomas com repouso, líquidos e lavagem nasal com soro, e antibióticos não ajudam porque a causa é viral.",
          "Lavar as mãos com frequência e evitar tocar olhos, nariz e boca reduzem a transmissão do resfriado comum. Procure atendimento se houver falta de ar, febre alta ou sintomas que duram mais de dez dias.",
          aliases=["resfriado", "resfriados"], orientacao=(2, 3), fontes={3: MS}),
    ficha("mundo_covid_19", "COVID-19", MI,
          "COVID-19 é a doença respiratória causada pelo coronavírus SARS-CoV-2, identificado no fim de 2019 na China; a OMS declarou pandemia em março de 2020.",
          "A COVID-19 é transmitida principalmente por gotículas e aerossóis expelidos ao falar, tossir e espirrar, sobretudo em ambientes fechados e mal ventilados.",
          "Os sintomas mais comuns da COVID-19 são febre, tosse, dor de garganta, cansaço, dor no corpo e perda de olfato ou paladar; casos graves podem ter falta de ar e pneumonia.",
          "As vacinas contra a COVID-19 reduzem muito o risco de casos graves e mortes e estão disponíveis no SUS; doses de reforço são recomendadas para grupos com maior risco.",
          "Quem tem sintomas de COVID-19 deve se testar, evitar contato próximo com outras pessoas e usar máscara; procure atendimento com urgência se houver falta de ar, dor no peito, lábios arroxeados ou confusão mental.",
          "A pandemia de COVID-19 causou milhões de mortes no mundo; no Brasil, foram mais de 700 mil óbitos registrados.",
          aliases=["covid", "coronavírus", "SARS-CoV-2", "novo coronavírus"], orientacao=(3,), fontes={2: MS, 3: MS, 4: MS}),
    ficha("mundo_avc", "acidente vascular cerebral", AP,
          "Acidente vascular cerebral (AVC), popularmente chamado de derrame, é a interrupção do fluxo de sangue para uma parte do cérebro, por entupimento (AVC isquêmico) ou rompimento (AVC hemorrágico) de um vaso.",
          "O AVC isquêmico, causado pelo bloqueio de uma artéria por coágulo ou placa de gordura, é o tipo mais comum, responsável por cerca de 85% dos casos.",
          "Os principais fatores de risco para AVC são hipertensão, tabagismo, diabetes, colesterol alto, sedentarismo, obesidade, consumo excessivo de álcool e arritmias como a fibrilação atrial.",
          "Os sinais de AVC surgem de repente: boca torta, fraqueza ou dormência em um lado do corpo, dificuldade para falar ou entender, perda de visão, tontura e dor de cabeça intensa.",
          "Diante de sinais de AVC, chame o SAMU (192) imediatamente: o tratamento nas primeiras horas pode desfazer o coágulo e reduzir sequelas. Um teste rápido é pedir para a pessoa sorrir, levantar os dois braços e repetir uma frase.",
          aliases=["AVC", "derrame", "derrame cerebral"], orientacao=(3,), fontes={2: MS, 3: MS}),
    ficha("mundo_infarto", "infarto agudo do miocárdio", AP,
          "Infarto agudo do miocárdio, ou infarto, é a morte de parte do músculo do coração causada pela interrupção do fluxo de sangue em uma artéria coronária, geralmente por um coágulo sobre uma placa de gordura.",
          "O sintoma mais típico do infarto é dor ou aperto no peito que pode irradiar para braço esquerdo, mandíbula ou costas, acompanhada de suor frio, falta de ar, náusea ou mal-estar.",
          "Em mulheres, idosos e pessoas com diabetes, o infarto pode se manifestar com sintomas menos típicos, como cansaço, falta de ar ou desconforto no estômago.",
          "Os fatores de risco para infarto incluem tabagismo, hipertensão, colesterol alto, diabetes, obesidade, sedentarismo, estresse e histórico familiar.",
          "Diante de suspeita de infarto, chame o SAMU (192) imediatamente: quanto mais rápido a artéria for desobstruída, menor o dano ao coração.",
          aliases=["infarto", "ataque cardíaco", "enfarte", "infarto do coração"], orientacao=(3,), fontes={3: MS}),
    ficha("mundo_colesterol", "colesterol", AP,
          "Colesterol é um tipo de gordura (lipídio) produzido pelo fígado e obtido dos alimentos de origem animal, necessário para formar membranas celulares, hormônios e vitamina D.",
          "O colesterol circula no sangue ligado a lipoproteínas: o LDL, chamado de colesterol ruim, deposita gordura nas artérias, e o HDL, chamado de colesterol bom, ajuda a removê-la.",
          "Colesterol alto geralmente não causa sintomas, mas favorece a aterosclerose, que aumenta o risco de infarto e AVC; por isso é detectado por exame de sangue.",
          "Para controlar o colesterol, recomenda-se alimentação com menos gorduras saturadas e trans e alimentos ultraprocessados, mais fibras, atividade física regular e não fumar; em alguns casos o médico indica remédios como as estatinas.",
          aliases=["colesterol alto", "LDL", "HDL", "hipercolesterolemia"], orientacao=(2,), fontes={2: MS}),
    ficha("mundo_obesidade", "obesidade", OMS,
          "Obesidade é o acúmulo excessivo de gordura corporal que prejudica a saúde; em adultos, é definida pelo índice de massa corporal (IMC) igual ou maior que 30.",
          "O IMC é calculado dividindo o peso em quilos pela altura em metros ao quadrado; entre 25 e 29,9 indica sobrepeso, e a medida da cintura ajuda a avaliar a gordura abdominal.",
          "A obesidade resulta da combinação de alimentação com excesso de calorias, sedentarismo, fatores genéticos, hormonais, emocionais e ambientais, como a oferta de alimentos ultraprocessados.",
          "A obesidade aumenta o risco de diabetes tipo 2, hipertensão, doenças do coração, AVC, alguns tipos de câncer, problemas nas articulações e apneia do sono.",
          "A prevenção e o tratamento da obesidade envolvem alimentação baseada em alimentos naturais, atividade física e acompanhamento profissional; em alguns casos há remédios ou cirurgia bariátrica, oferecidos também pelo SUS.",
          aliases=["sobrepeso", "índice de massa corporal", "IMC"], orientacao=(3,), fontes={3: MS}),
    ficha("mundo_sistema_imunologico", "sistema imunológico", AP,
          "Sistema imunológico, ou sistema imune, é o conjunto de órgãos, células e moléculas que defende o corpo contra microrganismos, toxinas e células anormais.",
          "O sistema imunológico funciona com uma defesa inata, rápida e inespecífica, que inclui pele, mucosas, inflamação e células como neutrófilos e macrófagos, e uma defesa adaptativa, específica e com memória, feita pelos linfócitos T e B.",
          "Os linfócitos B produzem anticorpos, e a memória imunológica explica por que, depois de uma infecção ou vacina, o corpo responde mais rápido ao mesmo agente.",
          "Órgãos do sistema imunológico incluem a medula óssea, o timo, o baço, os linfonodos (ínguas) e as amígdalas.",
          "Falhas no sistema imunológico podem causar imunodeficiências, como a aids; alergias, quando reage exageradamente a substâncias inofensivas; e doenças autoimunes, quando ataca o próprio corpo.",
          "Sono adequado, alimentação equilibrada, atividade física, vacinação em dia e não fumar mantêm as defesas do corpo saudáveis; não há alimento ou suplemento que sozinho turbine a imunidade.",
          aliases=["sistema imune", "sistema imunitário", "imunidade", "defesas do corpo"], orientacao=(4,), fontes={4: MS}),
    ficha("mundo_hidratacao", "hidratação", MS,
          "Hidratação é a reposição da água que o corpo perde pela urina, suor, respiração e fezes; a água corresponde a cerca de 60% do peso de um adulto.",
          "Sobre quanta água se deve beber por dia, uma referência comum é cerca de 2 litros, mas a necessidade varia com o peso, a idade, o clima, a atividade física e o estado de saúde; parte da água também vem dos alimentos.",
          "Um sinal prático de boa hidratação é urina clara e em volume normal; urina escura e sede intensa indicam que é preciso beber mais líquido.",
          "Recomenda-se beber água ao longo do dia, sem esperar a sede, e aumentar a ingestão em dias quentes, durante exercícios e em caso de febre, vômito ou diarreia; idosos e crianças precisam de atenção especial.",
          "Água pura é a melhor forma de hidratação; refrigerantes e sucos adoçados trazem açúcar em excesso, e pessoas com doenças renais ou cardíacas devem seguir a orientação médica sobre quanto beber.",
          aliases=["ingestão de água", "beber água", "consumo de água", "quanto beber de água", "água por dia", "litros de água por dia"], orientacao=(1, 2, 3)),
    ficha("mundo_desidratacao", "desidratação", MS,
          "Desidratação é a perda de água e sais minerais do corpo em quantidade maior do que a ingerida.",
          "As causas mais comuns de desidratação são diarreia, vômitos, febre, suor intenso no calor ou em exercícios e pouca ingestão de líquidos.",
          "Os sinais de desidratação incluem sede, boca seca, urina escura e escassa, cansaço, tontura e, em casos graves, olhos fundos, confusão e pulso rápido; em bebês, choro sem lágrimas e moleira afundada.",
          "A desidratação leve é tratada com água e soro de reidratação oral, distribuído gratuitamente nos postos de saúde; crianças, idosos e casos com vômitos persistentes, sonolência ou ausência de urina precisam de atendimento rápido.",
          aliases=["corpo desidratado"], orientacao=(2,)),
    ficha("mundo_asma", "asma", AP,
          "Asma é uma doença crônica dos pulmões em que os brônquios ficam inflamados e se estreitam, dificultando a passagem do ar.",
          "Os sintomas da asma são falta de ar, chiado no peito, tosse (frequentemente à noite) e sensação de aperto no peito, que vêm em crises.",
          "As crises de asma podem ser desencadeadas por alergênicos como poeira, ácaros, mofo e pelos de animais, além de fumaça, poluição, infecções respiratórias, frio e exercício.",
          "A asma não tem cura, mas pode ser controlada com remédios inalatórios, as bombinhas: os de controle reduzem a inflamação e os de alívio abrem os brônquios na crise; o SUS oferece medicamentos para asma.",
          "Procure atendimento de urgência se a falta de ar na crise de asma não melhorar com a bombinha, se houver dificuldade para falar ou lábios arroxeados.",
          aliases=["bronquite asmática", "crise de asma"], orientacao=(3,), fontes={2: MS, 3: MS}),
    ficha("mundo_alergia", "alergia", AP,
          "Alergia é uma reação exagerada do sistema imunológico a substâncias geralmente inofensivas, chamadas alérgenos, como pólen, ácaros, alimentos, picadas de insetos e medicamentos.",
          "Na alergia, o organismo produz anticorpos do tipo IgE que, ao reencontrar o alérgeno, liberam histamina e outras substâncias que causam os sintomas.",
          "Os sintomas de alergia incluem espirros, coriza, coceira, olhos vermelhos, manchas na pele (urticária), inchaço e, nas alergias alimentares, vômitos e diarreia.",
          "Anafilaxia é a forma mais grave de alergia, com inchaço da garganta, falta de ar e queda de pressão; é uma emergência e exige atendimento imediato.",
          "O controle da alergia envolve identificar e evitar o alérgeno e usar remédios como anti-histamínicos com orientação profissional; procure um serviço de saúde se surgir falta de ar ou inchaço no rosto.",
          aliases=["alergias", "reação alérgica", "anafilaxia"], orientacao=(3,), fontes={3: MS}),
    ficha("mundo_anemia", "anemia", AP,
          "Anemia é a condição em que a quantidade de hemoglobina ou de glóbulos vermelhos no sangue está abaixo do normal, reduzindo o transporte de oxigênio para os tecidos.",
          "A causa mais comum de anemia é a falta de ferro (anemia ferropriva), por alimentação pobre em ferro ou perda de sangue; também há anemias por falta de vitamina B12 ou ácido fólico e anemias hereditárias, como a falciforme.",
          "Os sintomas de anemia incluem cansaço, fraqueza, palidez, falta de ar aos esforços, tontura e unhas frágeis; o diagnóstico é feito pelo hemograma.",
          "Para prevenir a anemia ferropriva, recomenda-se consumir carnes, feijão, lentilha e verduras verde-escuras, com frutas ricas em vitamina C para aumentar a absorção; suplementos de ferro devem ser usados com orientação profissional.",
          aliases=["anemia ferropriva", "falta de ferro no sangue"], orientacao=(2,), fontes={2: MS}),
    ficha("mundo_osteoporose", "osteoporose", AP,
          "Osteoporose é uma doença em que os ossos perdem massa e ficam porosos e frágeis, aumentando o risco de fraturas.",
          "A osteoporose é mais comum em mulheres após a menopausa, pela queda do estrogênio, e em idosos; outros fatores de risco são sedentarismo, tabagismo, álcool, baixo consumo de cálcio e uso prolongado de corticoides.",
          "A osteoporose geralmente não causa sintomas até ocorrer uma fratura, frequentemente no quadril, no punho ou nas vértebras; o diagnóstico é feito pela densitometria óssea.",
          "Para prevenir a osteoporose, recomenda-se alimentação com cálcio, como leite e derivados, exposição moderada ao sol para produzir vitamina D, atividade física com impacto ou musculação e evitar fumo e excesso de álcool.",
          aliases=["ossos fracos"], orientacao=(2,), fontes={2: MS}),
    ficha("mundo_alzheimer", "doença de Alzheimer", AP,
          "Doença de Alzheimer é uma doença neurodegenerativa progressiva do cérebro e a causa mais comum de demência, descrita em 1906 pelo médico alemão Alois Alzheimer.",
          "Na doença de Alzheimer, acúmulos anormais das proteínas beta-amiloide e tau levam à morte de neurônios, começando por regiões ligadas à memória, como o hipocampo.",
          "O primeiro sinal da doença de Alzheimer costuma ser a perda de memória recente; com a progressão surgem desorientação, dificuldade de linguagem, mudanças de comportamento e dependência para atividades diárias.",
          "A doença de Alzheimer não tem cura; remédios e estímulos cognitivos podem aliviar sintomas, e o maior fator de risco é a idade avançada.",
          "Esquecimentos frequentes que atrapalham a rotina, desorientação ou mudança de comportamento em pessoa idosa devem ser avaliados por um médico; controlar pressão, diabetes, praticar atividade física e manter a mente ativa ajudam a reduzir o risco de demência.",
          aliases=["Alzheimer", "mal de Alzheimer"], orientacao=(3,), fontes={3: MS}),
    ficha("mundo_enxaqueca", "enxaqueca", AP,
          "Enxaqueca, ou migrânea, é um tipo de dor de cabeça recorrente, geralmente latejante e de um lado da cabeça, que dura de horas a até três dias.",
          "A enxaqueca costuma vir com náusea, vômitos e sensibilidade à luz e ao som; algumas pessoas têm aura antes da dor, com alterações visuais como pontos luminosos.",
          "A enxaqueca tem forte componente genético e é mais comum em mulheres; crises podem ser desencadeadas por estresse, falta ou excesso de sono, jejum, alguns alimentos, álcool e variações hormonais.",
          "O tratamento da enxaqueca inclui analgésicos e remédios específicos na crise e, quando as crises são frequentes, remédios preventivos indicados pelo médico; o uso excessivo de analgésicos pode piorar as dores.",
          "Procure atendimento de urgência se a dor de cabeça for súbita e muito intensa, a pior da vida, ou vier com febre, rigidez no pescoço, fraqueza, confusão ou alteração da fala.",
          aliases=["migrânea", "enxaquecas"], orientacao=(3,), fontes={3: MS}),
    ficha("mundo_aids", "aids", MI,
          "Aids (síndrome da imunodeficiência adquirida) é a fase avançada da infecção pelo HIV, o vírus da imunodeficiência humana, que destrói linfócitos T CD4 e enfraquece o sistema imunológico.",
          "O HIV, vírus causador da aids, é transmitido (pega-se) por relações sexuais sem preservativo, compartilhamento de seringas, transfusão de sangue contaminado e da mãe para o filho na gestação, no parto ou na amamentação; não é transmitido por abraço, beijo, talheres ou picada de inseto.",
          "Sem tratamento, a infecção pelo HIV pode passar anos sem sintomas até a aids, quando surgem infecções oportunistas, como tuberculose e pneumonias, e alguns tipos de câncer.",
          "Não há cura para o HIV, mas o tratamento antirretroviral, gratuito no SUS desde 1996, controla o vírus; pessoas com carga viral indetectável por tratamento não transmitem o HIV por via sexual.",
          "A prevenção do HIV inclui camisinha, testagem, PrEP (remédio antes da exposição) e PEP (até 72 horas após uma exposição de risco), oferecidas pelo SUS; o teste rápido é gratuito nos postos de saúde.",
          aliases=["HIV", "síndrome da imunodeficiência adquirida", "vírus da imunodeficiência humana", "SIDA"], orientacao=(3,), fontes={2: MS, 3: MS}),
    ficha("mundo_sarampo", "sarampo", MI,
          "Sarampo é uma doença infecciosa viral grave e altamente contagiosa, transmitida pelo ar quando a pessoa doente tosse, fala ou espirra.",
          "Os sintomas do sarampo são febre alta, tosse, coriza, olhos vermelhos e manchas vermelhas na pele que começam no rosto e se espalham pelo corpo.",
          "O sarampo pode causar complicações como pneumonia, diarreia grave, encefalite e morte, sobretudo em crianças pequenas e desnutridas.",
          "A prevenção do sarampo é a vacina tríplice viral (sarampo, caxumba e rubéola), aplicada pelo SUS aos 12 meses com reforço aos 15 meses pela tetra viral; adultos não vacinados também devem se vacinar.",
          "Pessoas com febre e manchas vermelhas pelo corpo devem procurar um serviço de saúde e evitar contato com outras pessoas até a avaliação.",
          orientacao=(2, 3), fontes={2: MS, 3: MS}),
    ficha("mundo_hepatite", "hepatite", MI,
          "Hepatite é a inflamação do fígado, causada principalmente por vírus (hepatites A, B, C, D e E), mas também por álcool, medicamentos e doenças autoimunes.",
          "As hepatites A e E são transmitidas por água e alimentos contaminados; as hepatites B, C e D, por sangue, relações sexuais sem preservativo, objetos cortantes compartilhados e da mãe para o bebê.",
          "Muitas hepatites não causam sintomas; quando aparecem, incluem cansaço, febre, enjoo, pele e olhos amarelados (icterícia), urina escura e fezes claras.",
          "As hepatites B e C podem se tornar crônicas e levar a cirrose e câncer de fígado; a hepatite C tem tratamento com alta taxa de cura, e a B pode ser controlada com remédios, ambos no SUS.",
          "Há vacinas contra hepatite A e B no SUS; usar camisinha, não compartilhar seringas, lâminas e alicates e fazer o teste rápido gratuito para hepatites B e C são formas de prevenção.",
          aliases=["hepatites virais", "hepatite A", "hepatite B", "hepatite C"], orientacao=(3,), fontes={3: MS}),
    ficha("mundo_tuberculose", "tuberculose", MI,
          "Tuberculose é uma doença infecciosa causada pela bactéria Mycobacterium tuberculosis, o bacilo de Koch, que atinge principalmente os pulmões.",
          "A tuberculose é transmitida pelo ar, quando a pessoa com a doença pulmonar ativa tosse, fala ou espirra.",
          "O principal sintoma da tuberculose é tosse por três semanas ou mais, acompanhada de febre no fim do dia, suor noturno, emagrecimento e cansaço.",
          "A tuberculose tem cura, com tratamento gratuito no SUS que dura pelo menos seis meses e não deve ser interrompido, mesmo com a melhora dos sintomas.",
          "A vacina BCG, aplicada ao nascer, protege contra as formas graves de tuberculose em crianças; quem tem tosse por três semanas ou mais deve procurar um posto de saúde para fazer o exame.",
          aliases=["bacilo de Koch", "Mycobacterium tuberculosis"], orientacao=(2, 3), fontes={3: MS}),
    ficha("mundo_catapora", "catapora", MI,
          "Catapora, ou varicela, é uma doença infecciosa muito contagiosa causada pelo vírus varicela-zóster, comum na infância.",
          "A catapora é transmitida pelo ar e pelo contato com o líquido das bolhas; os sintomas são febre, mal-estar e manchas que viram bolhas com coceira e depois crostas.",
          "O vírus da catapora permanece no corpo e pode se reativar anos depois, causando o herpes-zóster, conhecido como cobreiro.",
          "A vacina contra catapora faz parte do calendário do SUS; na doença, recomenda-se cortar as unhas, manter a pele limpa, não coçar as bolhas e não usar ácido acetilsalicílico (AAS).",
          "Procure atendimento se a catapora vier com febre alta persistente, bolhas infeccionadas, dificuldade para respirar, sonolência excessiva ou se atingir gestantes, bebês ou pessoas com imunidade baixa.",
          aliases=["varicela"], orientacao=(2, 3), fontes={2: MS, 3: MS}),
    ficha("mundo_dengue", "dengue", FC,
          "Dengue é uma doença viral transmitida pela picada da fêmea do mosquito Aedes aegypti, comum em regiões tropicais como o Brasil.",
          "Os sintomas da dengue são febre alta de início súbito, dor de cabeça, dor atrás dos olhos, dores no corpo e nas articulações, manchas vermelhas e cansaço.",
          "Na dengue, deve-se procurar o médico com urgência diante dos sinais de alarme: dor abdominal intensa, vômitos persistentes, sangramentos, tontura ao levantar e sonolência ou irritabilidade, que surgem em geral quando a febre baixa.",
          "Na dengue, recomenda-se repouso e muita hidratação; não se deve usar remédios com ácido acetilsalicílico (AAS) nem anti-inflamatórios, pelo risco de sangramento.",
          "A prevenção da dengue é eliminar água parada, onde o mosquito se reproduz; o SUS também oferece vacina contra dengue para faixas etárias definidas pelo Ministério da Saúde.",
          aliases=["febre da dengue"], orientacao=(1, 2, 3), fontes={1: MS, 2: MS, 3: MS}),
    ficha("mundo_zika", "zika", FC,
          "Zika é uma doença causada pelo vírus zika, transmitido principalmente pela picada do mosquito Aedes aegypti e também por via sexual e da gestante para o bebê.",
          "Os sintomas da zika costumam ser leves: manchas vermelhas com coceira, febre baixa, olhos vermelhos sem secreção e dores nas articulações; muitas pessoas não têm sintomas.",
          "A infecção por zika durante a gravidez pode causar microcefalia e outras malformações no bebê; essa relação foi identificada no Brasil em 2015, com participação de pesquisadores brasileiros e da Fiocruz.",
          "Não há vacina contra zika; a prevenção é combater o mosquito eliminando água parada, usar repelente e roupas compridas e, para gestantes e seus parceiros, usar camisinha.",
          "Gestantes com manchas vermelhas ou febre devem procurar atendimento de saúde para avaliação.",
          aliases=["vírus zika", "zika vírus"], orientacao=(2, 3), fontes={3: MS}),
    ficha("mundo_chikungunya", "chikungunya", FC,
          "Chikungunya é uma doença causada pelo vírus chikungunya e transmitida pelos mosquitos Aedes aegypti e Aedes albopictus.",
          "O sintoma marcante da chikungunya é febre alta com dor intensa nas articulações, sobretudo de mãos, pés e tornozelos, que pode deixar a pessoa curvada; o nome vem de uma língua africana e significa algo como 'aquele que se dobra'.",
          "Em parte dos casos, as dores articulares da chikungunya persistem por meses ou anos após a fase aguda.",
          "Na chikungunya, recomenda-se repouso, hidratação e analgésicos indicados por profissional de saúde; procure atendimento se a febre persistir, as dores impedirem atividades ou houver sinais de gravidade.",
          "A prevenção da chikungunya é a mesma da dengue e da zika: eliminar água parada e usar repelente.",
          aliases=["febre chikungunya"], orientacao=(2, 3), fontes={2: MS, 3: MS}),
    ficha("mundo_pneumonia", "pneumonia", MI,
          "Pneumonia é uma infecção que inflama os alvéolos dos pulmões, que podem se encher de líquido ou pus, dificultando a respiração.",
          "A pneumonia pode ser causada por bactérias (como o pneumococo), vírus (como influenza e o coronavírus) e, mais raramente, fungos.",
          "Os sintomas da pneumonia incluem tosse com catarro, febre, calafrios, dor no peito ao respirar e falta de ar; em idosos pode aparecer só confusão ou prostração.",
          "A pneumonia bacteriana é tratada com antibióticos prescritos pelo médico; as vacinas contra pneumococo, gripe e COVID-19 ajudam a preveni-la.",
          "Procure atendimento se houver falta de ar, respiração rápida, febre alta persistente ou dor no peito, principalmente em crianças pequenas, idosos e pessoas com doenças crônicas.",
          aliases=["infecção pulmonar"], orientacao=(3,), fontes={3: MS}),
    ficha("mundo_alimentacao_saudavel", "alimentação saudável", MS,
          "Alimentação saudável é uma alimentação variada, equilibrada e baseada principalmente em alimentos in natura ou minimamente processados, como recomenda o Guia Alimentar para a População Brasileira, do Ministério da Saúde.",
          "O Guia Alimentar para a População Brasileira recomenda fazer de alimentos in natura, como arroz, feijão, frutas, legumes, verduras, ovos, leite e carnes, a base da alimentação.",
          "Recomenda-se usar óleo, sal e açúcar em pequenas quantidades ao cozinhar e evitar alimentos ultraprocessados, como refrigerantes, salgadinhos, biscoitos recheados e embutidos.",
          "Comer com regularidade e atenção, em ambientes apropriados e, sempre que possível, em companhia, e preferir preparar a própria comida também fazem parte das recomendações do Guia Alimentar.",
          "Uma alimentação saudável ajuda a prevenir obesidade, diabetes tipo 2, hipertensão, doenças do coração e alguns tipos de câncer.",
          aliases=["alimentação equilibrada", "dieta saudável", "Guia Alimentar para a População Brasileira", "comer bem"],
          orientacao=(1, 2, 3)),
    ficha("mundo_saude_bucal", "saúde bucal", MS,
          "Saúde bucal é o cuidado com dentes, gengivas e boca, importante para mastigar, falar e para a saúde geral.",
          "Recomenda-se escovar os dentes ao menos três vezes ao dia, principalmente após as refeições e antes de dormir, com creme dental com flúor, e usar fio dental diariamente.",
          "Reduzir o consumo de açúcar, sobretudo entre as refeições, não fumar e visitar o dentista regularmente ajudam a prevenir cárie e doenças da gengiva.",
          "Sangramento na gengiva, mau hálito persistente, dor de dente ou feridas na boca que não cicatrizam em cerca de duas semanas devem ser avaliados por um dentista; o SUS oferece atendimento odontológico pelo programa Brasil Sorridente.",
          aliases=["higiene bucal", "escovação dos dentes", "escovar os dentes", "saúde dos dentes"], orientacao=(0, 1, 2)),
    ficha("mundo_carie", "cárie", AP,
          "Cárie é a destruição progressiva do dente causada por ácidos produzidos por bactérias da placa bacteriana a partir dos açúcares da alimentação.",
          "A cárie começa como uma mancha branca no esmalte e, sem tratamento, forma cavidades que podem atingir a dentina e a polpa, causando dor e infecção.",
          "A prevenção da cárie inclui escovar os dentes com creme dental com flúor, usar fio dental, reduzir açúcares e ir regularmente ao dentista; a água tratada com flúor também ajuda.",
          "A cárie é tratada pelo dentista com remoção da parte afetada e restauração (obturação); casos avançados podem exigir tratamento de canal ou extração.",
          aliases=["cárie dentária", "cáries", "dente cariado"], orientacao=(1,), fontes={1: MS, 2: MS}),
]

if __name__ == "__main__":
    import sys
    salvar(sys.argv[1], "Sínteses próprias sobre saúde do dia a dia e doenças comuns, com base em manuais abertos "
           "(OpenStax, CC BY 4.0) e referências institucionais (Ministério da Saúde, OMS, Fiocruz). Informação geral "
           "e educativa: não substitui avaliação de profissional de saúde.", FONTES, ITENS)
